### ISSUE TITLE
Sorting does not work in BO catalog page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10168]
**Describe the bug**
On backoffice Catalog page, I click on the blue arrows try to sort the products by ID, name, category name ... and nothing seems to work.

**To Reproduce**
Go to backoffice Catalog page, click on blue arrows next to "ID" or "Name", or "Category". This should sort the products displayed in the listing. Page is reloaded but not sorted.

**Screenshots**
![capture d ecran 2018-08-28 a 14 42 18](https://user-images.githubusercontent.com/3830050/44723721-1448c400-aad1-11e8-993b-1e95e7b909f5.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @matks,

I did not manage to reproduce the issue with the last version 1.7.4.2.
I attached a video record: https://drive.google.com/file/d/1AAfdbWluABBV4Q6oqyw9V2m_WJvHNCjh/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with the branch develop.
In the last version 1.7.4.2. => Ok
We will see how to fix it.

Best regards, Khouloud

**Comment by matks** [comment]
According to its [routing](
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/products.yml#L49) this page expects URL to be formatted as `/{offset}/{limit}/{orderBy}/{sortOrder}`

However the listing URL does not follow this at all: `/sell/catalog/products?_token=xxxxx&orderBy=reference&sortOrder=asc`: the sort parameters are not passed in the path but as GET parameters. So `offset`, `orderBy`, `sortOrder` ... are always being given default values no matter what the user inputs.

@eternoendless Wdyt ? I can either fallback on the $_GET (using Symfony `$request` object) values  or I can modify the routing.

**Comment by PierreRambaud** [comment]
@matks Le Fu.. Was already fixed. https://github.com/PrestaShop/PrestaShop/pull/9074 and validated by @eternoendless

**Comment by mickaelandrieu** [comment]
As it's fixed and merged this issue should be closed.

Good job everyone

**Comment by mickaelandrieu** [comment]
Not fixed on 1.7.5 => https://github.com/PrestaShop/PrestaShop/pull/10365

**Comment by marionf** [comment]
It's fixed on 1.7.5.x
