### ISSUE TITLE
Frequently disconnected from Prestashop Back office

### ISSUE THREAD

**Issue by CArlvJ1N0N8** [PrestaShop/PrestaShop#10244]
**Describe the bug**
When connecting to the Backoffice of Prestashop you have to enter a username and a password. 
It happens very often that i am being ejected from the back-Office and need to reconnect to continue my session. 

**To Reproduce**
By working frequently on the Back-Office it reproduces regularly. 

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0.27-0+deb9u1

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Could you please try to delete all cookies, it could be a cookie related problem. In Chrome, for example, to delete all cookies you right-click->Inspect element->Application->Cookies->Delete all cookies.
Also, check the developer console in your browser, see if you have some errors there. 
Another approach, try to log in in the admin using the browser Incognito mode (Ctrl+Shift+P in Google Chrome). This way you will start without any cookies set. See if it works.

Best regards, Khouloud

**Comment by LedCloud** [comment]
First of all check that your IP is not changing offen. If it it is changing, it might be a reason.
For security purpose strore will ask you to log in again if your IP has been changed. You can switch it off.
Advanced Parametrs->Administration->Check the cookie's IP address

**Comment by CArlvJ1N0N8** [comment]
Hello, 

I have done the cookies clean up numerous times. 
Nothing changes. 

For the IP change, i will try this setting but i am on my own wireless so IP should not change so often...

As an example, i login to the BO, i go to the International - translations - i select Translations installed modules then i select "Supercheckout" in the modules and choose a language, reviewing the translations for 5-7 minutes, typing in the different boxes, etc. .... without saving... 
After the 5-7 minutes if i save i need to login again and all translations done are lost...

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

In the login in page BO, did you checked the stay_logged_in option?

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
Yes I always check it.

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

The default settings are 15 minutes, so the login is automatically terminated after 15 minutes of inactivity in the PrestaShop.
This time can be easily adjusted in the following folder: 
classes / controller / AdminController.php
Look for line 2732, where the following code is to be found: 
if ($this->context->cookie->last_activity + 900 < time()) {
Changing 900 to 3600 increases the log-in period from 15 to 60 minutes.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
Hllo, 

Looking at this as i will change this setting, but the file AdminController.php does not exist. 
I thought it would be AdminAccessController but there is not line 2732. 

Can you please provide full name? 

Thanks, 

Carl

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8 ,

It is into the path /PROJECT_FOLDER/classes/controller/AdminController.php
![image](https://user-images.githubusercontent.com/16067358/44995624-28defd80-afa4-11e8-869c-32db0fc8cb10.png)

Best regards, Khouloud

**Comment by CArlvJ1N0N8** [comment]
OK it seems to be working fine now. 
I will continue to test and let you know !

**Comment by khouloudbelguith** [comment]
Hi @CArlvJ1N0N8,

Since it is fixed, I close the issue.
Feel free to open a new one when needed.

Best regards, Khouloud

**Comment by MarouaniALA** [comment]
Hi,
Have same problem i modified that line and the problem persist . get this PHP Notice in apache error log 

[php7:notice] [pid 9747] [client ] PHP Notice:  Undefined index: name in /var/www/html/classes/controller/AdminController.php on line 633, referer: https://URL

**Comment by khouloudbelguith** [comment]
Hi @MarouaniALA,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by MarouaniALA** [comment]
Hi @khouloudbelguith,
Ok sorry 

Thanks
