### ISSUE TITLE
Combination selector generates 403 forbidden error!

### ISSUE THREAD

**Issue by fruitfreak** [PrestaShop/PrestaShop#10331]
If a product has two sizes, but each size has different flavors - it generates an error if I first select one flavor that do not exist in the other size. And then selects the other size...

Example:
Go to:
http://test.plante-protein.dk/protein-pulver/20-67-vega-protein-greens-proteinpulver.html#/
1. Select Berry flavor
2. Select 760 Gram size.

Logically selecting the 760 gram size should reset the flavor options - but Instead it throws the not-so-pretty 403 error. 
Notice both the popup and the red "An error occurred while processing your request".

Thanks! :-)
Kind regards
Ivan

**Comment by khouloudbelguith** [comment]
Hi @fruitfreak,

The issue is fixed in the next version 1.7.5.0.
Here's the PR: #9390 to solve the issue.
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #9390

**Comment by fruitfreak** [comment]
This one is still an issue unfortunately - running 1.7.6.0
http://prntscr.com/onlsmb

example:

https://plante-protein.dk/protein-pulver/39-258-pulsin-supershake-vegansk-proteinpulver.html

When selecting between flavors that have different sizes it generates 403 pop-up.

What to do?
Thanks :-)
Ivan

**Comment by khouloudbelguith** [comment]
@fruitfreak, this issue occurs with the `productextratabs` module.
Thanks!
