### ISSUE TITLE
Filter by Size - Files Page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11054]
**Describe the bug**
In the files page, when we try to filter by size, the filter is NOK.
=> No records found 
 

**To Reproduce**
1. Go to BO => Catalog => Files
2. In files page, add at least two files 
3. Try to filter by size=> No records found

**Screenshots**
https://drive.google.com/file/d/1aFPudNh5W0ZqMUJy5h_1oBvnIkUlkRzH/view

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

**Comment by marionf** [comment]
@khouloudbelguith 

It works for me

![capture d ecran_459](https://user-images.githubusercontent.com/13449658/47099202-16a7de80-d235-11e8-9f3d-8e5f76681ce8.png)

![capture d ecran_460](https://user-images.githubusercontent.com/13449658/47099207-19a2cf00-d235-11e8-817b-8ae3be57c97a.png)

**Comment by khouloudbelguith** [comment]
Hi @marion, it is not the sort action, it is the filter action.
![image](https://user-images.githubusercontent.com/16067358/47099367-6dadb380-d235-11e8-945c-d9121ab30706.png)
Thanks!

**Comment by marionf** [comment]
It works if you enter an integer but not a decimal number or the exact value with the "k"

![capture d ecran_461](https://user-images.githubusercontent.com/13449658/47099612-f4629080-d235-11e8-82de-2757585902bb.png)

**Comment by ghost** [comment]
I don't reproduce this issue,I think it has been fixed when the page migration

Thomas

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

No ,it's not fixed yet cause I reproduce it on PS1783 and develop, check the attached screen record below:

https://user-images.githubusercontent.com/23308427/154231031-2ef823d7-d969-465f-aaa1-9731c3643e24.mp4

Thanks!

**Comment by Poulinhoo** [comment]
Hello!

I investigated this issue and I found the problem. In this case, when we save a file, we store the file size in Bytes in the database. To be clear to the merchant and have a human-readable value, we convert it to the best suitable unit (kB, MB, etc.) depending on the size. 

eg: 
- 105870 Bytes (in the database) will be converted to 105.87kB
- 2508700 Bytes will be converted to 2.50MB


So, given those examples, if the merchant wants to search by size, he will enter, for example, 2.50 in the filter. 2.50 in the database corresponds to nothing because the value stored in the database, as explained earlier, is 2508700. So there are no results for the given search. It can be confusing for the user 🤔 

Multiple solutions can be done, such as adding a selector in the filter to choose the units in which the merchant is performing the search. However, it requires some (too big?) changes.
A potentially quick fix, we can only change the placeholder wording from

![Screenshot 2024-07-31 at 11 05 27](https://github.com/user-attachments/assets/c8362820-3c4b-4982-be2d-94fb4940640f)

to something like "search file size (by bytes)" to give more context for the merchant on how to perform the search.

**Comment by boo-code** [comment]
Still reproduces on 9.2.x. Draft PR: #42476.

The Size column and its filter do not use the same value. `AttachmentGridDataFactoryDecorator:78` converts the stored byte count for display through `FileSizeConverter::convert()`, while `AttachmentQueryBuilder::applyFilters()` matches that byte count with `a.file_size LIKE '%<input>%'`. Measured:

    bytes=512      shown=512B     types 512    -> LIKE '%512%'    matches: YES
    bytes=1234     shown=1.21kB   types 1.21   -> LIKE '%1.21%'   matches: NO
    bytes=45678    shown=44.61kB  types 44.61  -> LIKE '%44.61%'  matches: NO
    bytes=3145728  shown=3.00MB   types 3.00   -> LIKE '%3.00%'   matches: NO

So the filter answers only for files under a kilobyte, which print as their own byte count. Every larger file is unreachable by anything the column shows - which is the "No records found" in the report, and why two files were enough to see it.

The PR makes the filter a range over the stored byte count, with the unit named in the inputs, which is how `ProductGridDefinitionFactory` filters its numeric columns. Parsing the displayed `44.61kB` back into bytes was the other candidate and is rejected in the PR: it means inverting a lossy conversion whose separator is localised.
