### ISSUE TITLE
PS1.7.4.4 BO language in Traditional Chinese, Cannot click the Calendar icon to show the Calendar Window

### ISSUE THREAD

**Issue by bmwjoeytsang** [PrestaShop/PrestaShop#11330]
**Describe the bug**
If we change the employee language to Traditional Chinese (TW) in BO, there have some error and the calendar windows cannot show up.

**To Reproduce**
1. When we goto Products / Category in BO, it will show "Uncaught ReferenceError: file_not_found is not defined". And I checked in the server /js/tiny_mce/langs/tw.js, there is no tw.js file in there. 

2. When we Edit the products in BO, it will show "Uncaught ReferenceError: file_not_found is not defined" and "Uncaught TypeError: locale() locale tw-tw is not loaded from moment locales!", then if we click the calendar icon to select the date (eg: add a specific price -> available from), the calendar cannot show up.

But If we change the employee profile to English again, all is working properly without any error. it seem there have some files is missing for TW-TW.

I tried PS1.7.3.2 and 1.7.4.4 also got the same problem.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.3.2 and 1.7.4.4
PHP version: 7.0.3
![ps1744error](https://user-images.githubusercontent.com/38032785/48236572-d4218e00-e3fd-11e8-8feb-322963724fae.JPG)

**Comment by bmwjoeytsang** [comment]
I changed the ISO code from tw-tw to zh-tw and the problem has been solved. thanks!

**Comment by madsoliver** [comment]
Same for a lot of languages.
Clean install and same error.
Please open this issue again.
Issue is still here on 1.7.5.1
