### ISSUE TITLE
Orders with relay carrier module but no relay selected

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/PrestaShop#11750]
**Describe the bug**
We have orders with relay carrier module but no relay selected.
This bug concerns relay point modules, it has been reproduced with Mondial Relay (mondialrelay) and SoColissimo (soflexibilite).

Thanks for your help.

**To Reproduce**
1. Make a cart
2. Go to the checkout
3. Go to step 3: carrier
4. Select home delivery
5. Go to step 4: payment
6. Return to step 3 and choose the relay point module (Mondial Relay or So Flexibility)
7. Close popup of selection of relay point WITHOUT choosing relay point
8. Return to step 2: address
9. Validate step 2 => BUG: we go directly to step 4 while we still have the relay point carrier selected but we did not choose a relay point

In contrast, the TNT module, meanwhile, has added a control that corrects much of the problem by blocking access to the payment step.

**Additionnal information**
PrestaShop version: 1.7.2.0, 1.7.4.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Thanks for your report.
What is the exact version of the mondial-relay module did you use?
Thanks!

**Comment by bm-services** [comment]
Hi,
With Mondial Relay 2.3.2 on PrestaShop 1.7.4.0
With So Flexibilité 3.1.15 on PrestaShop 1.7.2.0, we have exactly the same problem.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.
We need to install Soap & cURL to use this module.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

I manage to reproduce this issue with Mondial Relay v2.3.3 - by PrestaShop.
I attached a video record.
https://drive.google.com/file/d/1BWxf1LLnHLA_Nw6oEnJYXskH1sQ5r-_c/view
We will see how to fix it.
Thanks!

**Comment by bm-services** [comment]
Hello,
Have you been able to advance on this bug?

**Comment by khouloudbelguith** [comment]
ping @colinegin

**Comment by colinegin** [comment]
@PrestaShop/prestashop-core-developers what do you think of this issue ? Should it be fixed in the core or in the module itself ?

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Sorry, it not fixed yet.
This is is not a regression or security issue, so it will not be fixed before 1.7.6.0 as described here: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#target-branch
Thanks for your understanding!

**Comment by colinegin** [comment]
Hello @eternoendless and @PrestaShop/prestashop-core-developers what do you think of this issue ? Should it be fixed in the core or in the module itself ?

Thanks

**Comment by colinegin** [comment]
Kind reminder @eternoendless and @PrestaShop/prestashop-core-developers , any idea ?

**Comment by khouloudbelguith** [comment]
Hi @bm-services, @colinegin,

I did not manage to reproduce the issue with PS1.7.6.0beta1.
I attached a screen record
https://drive.google.com/file/d/1rVYrouktypMV0JzbGoA9ccaaoP1ZiT1a/view
This issue should be fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/13106

Since it is fixed, I close the issue, feel free to open a new one when needed.

Thank you!
