### ISSUE TITLE
Product url / id_product_attribute*

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11773]
Hi,
In term of SEO it is not a good idea to have the id_product_attribute in the url. The rule is simple : if you can avoid the use of the canonical ... then avoid ! Do you plan to fix that ?
The problem with the canonical is that you won't check it "every day" ... if one day there is a bug (for any reason) and the canonical is wrong >> you will kill your seo effort.

Thanks for your answer.

Best Regards,
Guillaume

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Thanks for your report.
Recently we have made some modifications related to the SEO OPTIMIZATION in the product page.
Thanks to follow those links & feedback: #9463, #9456
About the bad URL when the product has combinations, we have also this issue #9784, it is added to our bug roadmap.
Thanks to check & feedback.

**Comment by grabelle** [comment]
Hi,
Sorry but I have to say that it is always strange to see some major error in term of SEO in a new project and a big project like prestashop (1.4 , 1.5 , 1.6 ... 1.7). 
Do you have any idea of the release with the fix ? 1.7.5 ?

Thanks for your great support

Guillaume

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

we have just published the Release Candidate of PrestaShop 1.7.5.0.
So, take a minute and read all about this release here: http://build.prestashop.com/news/prestashop-1.7.5-rc-release/
So the stable version will be released in a short time.
Thanks!

**Comment by grabelle** [comment]
Hi,
Sorry but the problem is still there on 1.7.5.0 ... do you plan to fix this or should we go back to 1.6 version ?
Thx for your support

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

In the PS1.7.5 we have made some SEO improvement.
About the bad URL when the product has combinations, we have this issue #9784, it is added to our bug roadmap.
Thanks!

**Comment by grabelle** [comment]
Hi,
Will this very important problem for a ecommerce website be fixed in the 1.7.5.1 ? (I mean removing the {-:id_product_attribute} of the product url) ?

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Unfortunately, for PS1.7.5.1, we only accept security fixes or regression from 1.7.5.0.
Thanks!

**Comment by Maofree** [comment]
Hi @khouloudbelguith 
I've seen that on the 1.7.5.0 there is the same problem
all combinations redirect to the canonical url (that without id_product_attribute) but this page if not exists and there is another redirect to the default combination but it has also the canonical url
so all these product pages will not be indexed

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Is it the same issue reported here #9784?
Thanks!

**Comment by Maofree** [comment]
yes
the problem is the same, there is reported the rss problem but it is for combination problem
I thought in the 1.7.5 it was fixed instead it is still present

**Comment by khouloudbelguith** [comment]
@maofree, the issue #9784 is still open, it is added to our bug roadmap.
Thanks!

**Comment by Maofree** [comment]
this problem is present from a long time

**Comment by HeineFr** [comment]
Hello,

I'm new in prestashop still september, i'm preparing to migrate my eshop and i saw the problem on 1.7.4.2.
After searches i saw that the issue was in the bug road map.
I saw only today and upgrade to the release of 1.7.5 that i was waiting for to produce finaly my website on prestashop without the canonical problem.

I paid some module to optimize SEO but i'm affraid to see that a real problem like this wasn't yet solve.

Incredible !

**Comment by grabelle** [comment]
Hi,
I fully agree and especially since this basic SEO problem did not exist in version 1.6. Version 1.7 is not ready for a production site that cares about the SEO. Very disappointing.

**Comment by grabelle** [comment]
Hi, any chance to get this solved ? I can't believe that no one care about that ! ?

Please fix this asap.

**Comment by RzaHuseyin** [comment]
you just need to modify $default_routes array in /classes/Dispatcher.php

'product_rule' => array( 
    'rule' => '{category:/}{id}-{rewrite}{-:ean13}.html',

http://prntscr.com/o1agta

after that you can can save your modifying in backoffice

**Comment by grabelle** [comment]
Hi,
Thanks, seems to work ! Hope I won't get side effect.

**Comment by grabelle** [comment]
> you just need to modify $default_routes array in /classes/Dispatcher.php
> 
> 'product_rule' => array(
> 'rule' => '{category:/}{id}-{rewrite}{-:ean13}.html',
> 
> http://prntscr.com/o1agta
> 
> after that you can can save your modifying in backoffice

Hi, it works but there is a side effect ... on the product page, the image is not displayed anymore (until I select the thumbnails)

![Capture du 2019-06-19 09-05-10](https://user-images.githubusercontent.com/5048627/59743997-d8eed000-9271-11e9-8e8c-d11dd41894d8.png)

**Comment by monak83** [comment]
Hi to all this problem persists even in the version 8.2.1 is possible?
