### ISSUE TITLE
Expected argument of type "object, array or empty", "string" given

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#11909]
**Describe the bug**
Error 500 when I click on the invoice item in the backend menu.

**To Reproduce**
1. in backend
2. Click on invoice item menu: /index.php/sell/orders/invoices/

**Screenshots**
```
Stack Trace:
Symfony\Component\Form\Exception\UnexpectedTypeException:
Expected argument of type "object, array or empty", "string" given

  at vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:41
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms('', object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData('')
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('Fattura n. ec/', '#IN'), 'add_current_year' => false, 'reset_number_annually' => true, 'year_position' => 1, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('www.domain.com', ''), 'invoice_model' => 'invoice', 'use_disk_cache' => false), object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData(array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('Fattura n. ec/', '#IN'), 'add_current_year' => false, 'reset_number_annually' => true, 'year_position' => 1, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('www.domain.com', ''), 'invoice_model' => 'invoice', 'use_disk_cache' => false))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(array('invoice_options' => array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('Fattura n. ec/', '#IN'), 'add_current_year' => false, 'reset_number_annually' => true, 'year_position' => 1, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('www.domain.com', ''), 'invoice_model' => 'invoice', 'use_disk_cache' => false)), object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:379)
  at Symfony\Component\Form\Form->setData(array('invoice_options' => array('enable_invoices' => false, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => array('Fattura n. ec/', '#IN'), 'add_current_year' => false, 'reset_number_annually' => true, 'year_position' => 1, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => array('www.domain.com', ''), 'invoice_model' => 'invoice', 'use_disk_cache' => false)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:483)
  at Symfony\Component\Form\Form->initialize()
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:226)
  at Symfony\Component\Form\FormBuilder->getForm()
     (src/Core/Form/FormHandler.php:114)
  at PrestaShop\PrestaShop\Core\Form\FormHandler->getForm()
     (src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php:57)
  at PrestaShopBundle\Controller\Admin\Sell\Order\InvoicesController->indexAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin/index.php:88)
```

![logs](https://user-images.githubusercontent.com/2458824/50377654-61711880-0621-11e9-85f0-846132510561.png)

![exception 01](https://user-images.githubusercontent.com/2458824/50377656-68982680-0621-11e9-83d3-71fb20c4e6a3.png)

![exception 02](https://user-images.githubusercontent.com/2458824/50377657-6d5cda80-0621-11e9-9c18-a8be14f2d98f.png)

**Additionnal information**
Prestashop 1.7.5
![server](https://user-images.githubusercontent.com/2458824/50377667-abf29500-0621-11e9-9504-5106e06c5a1e.png)

**Comment by khouloudbelguith** [comment]
Hi @dritancami,

Could you please try to replace the `ps_configuration_lang` table in the Database with the one from clean PS1.7.5.0 installation.
Thanks to check & feedback.

**Comment by ghost** [comment]
I can try, in the meantime I tried to redo what is indicated here http://forge.prestashop.com/browse/BOOM-5982?focusedCommentId=171708&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-171708 but did not solve the problem.

**Comment by khouloudbelguith** [comment]
@dritancami, yes because the exception is a different page.
That's why you need to replace all the ps_configuration_lang table.
Thanks!

**Comment by ghost** [comment]
No sorry, the problem has not been solved. On the same server (with the same features) I installed a clean version ps 1.7.5.0 and I tested with only one active language and then with two active languages, as is currently on the ps in production.
![schermata 2018-12-24 alle 11 38 36](https://user-images.githubusercontent.com/2458824/50397395-7b6d4100-0770-11e9-9db3-cbd6c443a763.png)

**Comment by khouloudbelguith** [comment]
@dritancami, Could you please follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by ghost** [comment]
Here it is:

![schermata 2018-12-24 alle 11 50 19](https://user-images.githubusercontent.com/2458824/50397640-364a0e80-0772-11e9-9c54-13dc451167d5.png)
![schermata 2018-12-24 alle 11 50 38](https://user-images.githubusercontent.com/2458824/50397642-3c3fef80-0772-11e9-8449-1620ab0fa90a.png)
![schermata 2018-12-24 alle 11 50 48](https://user-images.githubusercontent.com/2458824/50397645-3fd37680-0772-11e9-8ea6-5676e916e129.png)

**Comment by khouloudbelguith** [comment]
@dritancami, thanks for your feedback.
In my case, I did not manage to reproduce the issue with PS1.7.5.0, English country / French language.
What is the exact Language/country di you used during the install?
Thanks!

**Comment by nuevoenesto** [comment]
Hi
I have the UnexpectedTypeException  when I click on the invoice item in the backend menú.
I replace the ps_configuration_lang table with one from a clean 1.7.5.0 new instalaltion, but the error continues.
Any help?
Thanks Enrique

**Comment by ghost** [comment]
In Italian. Now I did the reverse test, I imported the "ps_configuration_lang" table from the ps in production to the one just installed 1.7.5 and the problem does not exist.

**Comment by nuevoenesto** [comment]
I received this from my page:
UnexpectedTypeException
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 41)
PropertyPathMapper->mapDataToForms('#IN', object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData('#IN')
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false), object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false))
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false)), object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => '', 'footer_text' => '', 'invoice_model' => 'invoice', 'use_disk_cache' => false)))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 483)
Form->initialize()
in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php (line 226)
FormBuilder->getForm()
in src/Core/Form/FormHandler.php (line 114)
            [                'form_builder' => &$this->formBuilder,            ]        );        return $this->formBuilder->getForm();    }    /**     * {@inheritdoc}     *
FormHandler->getForm()
in src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController.php (line 57)
InvoicesController->indexAction(object(Request))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
HttpKernel->handleRaw(object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
HttpKernel->handle(object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
Kernel->handle(object(Request), 1, false)
in adminlabs/index.php (line 88)

**Comment by khouloudbelguith** [comment]
@dritancami, so your issue is fixed?
@nuevoenesto, could you please try to replace the ps_configuration_lang table in the Database with the one from clean PS1.7.5.0 installation.
Thanks!

**Comment by nuevoenesto** [comment]
Hi, 
Just I replace the table ps_configuration_lang  from a nwe database, but the error continues.

**Comment by ghost** [comment]
> @dritancami, so your issue is fixed?
> @nuevoenesto, could you please try to replace the ps_configuration_lang table in the Database with the one from clean PS1.7.5.0 installation.
> Thanks!

No, it has not been solved. Summary, if I import the table of the clean installation in the db of the ps in production - the problem continues. If i import the table of ps in production in the db of the clean installation, the problem does not occur.

**Comment by khouloudbelguith** [comment]
@dritancami, could you please provide me the table ps_configuration_lang of your fresh installation (where the error occurs)
& provide me the ps_configuration_lang of your shop production (where there is no error).
Thanks!

**Comment by ghost** [comment]
It's the opposite, new installation = without problems, production = problems.
[production.sql.zip](https://github.com/PrestaShop/PrestaShop/files/2707522/production.sql.zip)
[new installation.sql.zip](https://github.com/PrestaShop/PrestaShop/files/2707523/new.installation.sql.zip)

**Comment by nuevoenesto** [comment]
Hi
I attach table in the original Pd 1.7.5.0 format
 I import this to the new proyect and not work, previous original Tablet in final propyect was not save.

**Comment by nuevoenesto** [comment]
I attach the file
[ps_configuration_lang_new.zip](https://github.com/PrestaShop/PrestaShop/files/2707599/ps_configuration_lang_new.zip)

**Comment by khouloudbelguith** [comment]
@dritancami, @nuevoenesto Did you made an upgrade from a previous version PrestaShop?
If yes, during the upgrade are there any errors displayed?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

**Comment by ghost** [comment]
Here it is:
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2707620/log.txt)

**Comment by nuevoenesto** [comment]
Yes this a upgrade form PD 1.6 to  1.7 without error in the process
Attach log file
Thanks!

**Comment by nuevoenesto** [comment]
The file
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2707629/log.txt)

**Comment by khouloudbelguith** [comment]
Hi @dritancami, @nuevoenesto,

Despite our several trials, I could not reproduce your issue with the provided information.
We are the Holidays season, our developers are not here right now.
I will assign your issue to our developer to reproduce the issue.
Thanks for your patience & your understanding!
@Quetzacoalt91 what do you think?
Thanks!

**Comment by rdy4ever** [comment]
Same error for me: 

> Expected argument of type "object, array or empty", "string" given
![image](https://user-images.githubusercontent.com/12268701/50425878-00974980-0888-11e9-9e50-32593b8514d6.png)

I didn't have this error in 1.7.4.2, so this is introduced in 1.7.5.0. I have tested it both on local (WAMP) and in production with the same error.

_PS 1.7.5.0
Linux #1 SMP Sun Feb 18 08:20:42 EST 2018 x86_64
LiteSpeed
PHP: 7.2.4
MySQL: 10.2.19-MariaDB-cll-lve_

**Comment by nuevoenesto** [comment]
Hello
In the label LOGS I have it

![error](https://user-images.githubusercontent.com/46094992/50425986-ac3d9b00-0882-11e9-9c5d-a42584ff3c12.JPG)

**Comment by khouloudbelguith** [comment]
Hi all,

During the upgrade, we have three warnings during the upgrade, here's the PR: #11814 to solve those warnings.
It could be related to your issue.
Thanks to check this PR: #11814  & apply changes to your Database & feedback.

**Comment by nuevoenesto** [comment]
Hello khouloudbelguith
Many thanks for your help.
My problem is in the INVOICE option.
this is the last error.
Can you help me, please?

![captura](https://user-images.githubusercontent.com/46094992/50443067-e9953d80-0901-11e9-8e03-24c7ed31a075.JPG)

**Comment by khouloudbelguith** [comment]
@dritancami, did you made an upgrade to PS1.7.5.0?
after the upgrade did you made the changes on your Database that I suggested in my [comment](https://github.com/PrestaShop/PrestaShop/issues/11909#issuecomment-449939147)?
Thanks!

**Comment by nuevoenesto** [comment]
Yes, I upgrade from PS 1.6.1.23 to PS.1.7.5.0
All running well, with some litte problems, like permissions of the Administror user, that solved with a new adminsitrator user, or traductions, but the menu  OREDERS->INVOICE show the error posted and not work.
Enrique

**Comment by khouloudbelguith** [comment]
@nuevoenesto, thanks for your feedback.
In my case, I did not manage to reproduce the issue with PS1.7.5.0 after upgrade from PS1.6.1.23.
Could you please try to make changes in your Database these changes:

ALTER TABLE `PREFIX_supply_order_receipt_history` CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '';


ALTER TABLE `PREFIX_product_lang` CHANGE `meta_description` `meta_description` varchar(512) DEFAULT NULL, CHANGE `meta_keywords` `meta_keywords` varchar(255) DEFAULT NULL;

ALTER TABLE `PREFIX_product` CHANGE `reference` `reference` varchar(64) DEFAULT NULL;

ALTER TABLE `PREFIX_order_detail` HANGE `product_supplier_reference` `product_supplier_reference` varchar(64) DEFAULT NULL;

As described in this PR: https://github.com/PrestaShop/PrestaShop/pull/11814/files

PS: PREFIX is the prefix of your tables, t could be for example ps.
Thanks to check & feedback.

**Comment by ghost** [comment]
> @dritancami, did you made an upgrade to PS1.7.5.0?
> after the upgrade did you made the changes on your Database that I suggested in my [comment](https://github.com/PrestaShop/PrestaShop/issues/11909#issuecomment-449939147)?
> Thanks!

Hi, I update ps from 1.7.4.4 version. Excluding the modification of the first file (https://github.com/PrestaShop/PrestaShop/pull/11814/files#diff-c23da96dc8986a4cee89980f3aad30e0) the other changes i can't test them because the folder 'install' no longer exists.

**Comment by khouloudbelguith** [comment]
@dritancami, you need to check your database & make those request SQL
![image](https://user-images.githubusercontent.com/16067358/50450217-c2079a80-092c-11e9-90e3-d26965f45e00.png)

Thanks!

**Comment by ghost** [comment]
Before applying the fix to the db, is it normal that I don't have the table indicated: 'PREFIX_supply_order_receipt_history'? The other tables instead there are.

**Comment by khouloudbelguith** [comment]
@dritancami, with fresh installation 1.7.4.4, this table exists  https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/install-dev/data/db_structure.sql#L2434

Thanks!

**Comment by ghost** [comment]
I do not question it, but I (in fact) don't have this table. Just for completeness of information, initially I had installed ps 1.7.3 .. I do so:
- I export this table from a clean installation (1.7.5.0)
- subsequently, i will test as indicated here https://github.com/PrestaShop/PrestaShop/pull/11814/files

**Comment by khouloudbelguith** [comment]
@dritancami, thanks for your feedback.
After those fixes, do you still have the same issue in the invoices page?
Thanks!

**Comment by nuevoenesto** [comment]
Hello khouloudbelguith
I made the the changes, and the problem persist at click in the INVOICE menu.

UnexpectedTypeException
HTTP 500 Internal Server Error
Expected argument of type "object, array or empty", "string" given

    Exception Logs 2 Stack Trace 

Symfony\Component\Form\Exception\ UnexpectedTypeException
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 41)
PropertyPathMapper->mapDataToForms('#IN', object(RecursiveIteratorIterator)) in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)

**Comment by ghost** [comment]
Go finished right now, the problem has not been solved.
![schermata 2018-12-26 alle 17 44 54](https://user-images.githubusercontent.com/2458824/50451717-fd5a9700-0935-11e9-9068-1ac57ba001f4.png)

**Comment by khouloudbelguith** [comment]
@dritancami, @nuevoenesto thanks for your feedback.
@marionf what do you think?
Thanks!

**Comment by rdy4ever** [comment]
Same for me. Executed SQL commands, problem remains the same.

**Comment by khouloudbelguith** [comment]
Hi all,

It could be like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.

Can you please check if you have missing columns on your database schema.
https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/upgrade/sql/1.7.5.0.sql

You can find the full schema for 1.7.5.0 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/data/db_structure.sql

Thanks!

**Comment by ghost** [comment]
I could give the commands to be 100% sure, then I'll update you.

**Comment by khouloudbelguith** [comment]
@dritancami, thanks!
Waiting for your feedback.

**Comment by ghost** [comment]
I run all the query sql (https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/install-dev/upgrade/sql/1.7.5.0.sql ), but the error continues..
<img width="1087" alt="schermata 2018-12-27 alle 12 26 34" src="https://user-images.githubusercontent.com/2458824/50478670-c6868e80-09d2-11e9-984b-376d6cc56bea.png">

**Comment by khouloudbelguith** [comment]
@dritancami, I assigned the issue to our developers to reproduce the issue.
Thanks!

**Comment by rdy4ever** [comment]
Yeap. Same for me. Checked all, I have all new colums, but still - the same error on the Invoices screen.

**Comment by rdy4ever** [comment]
These are the only errors I got during db upgrade, but I fixed them later:

> [WARNING] SQL 1.7.5.0
            1060 in ALTER TABLE `ps_supply_order_receipt_history`
  CHANGE `employee_firstname` `employee_firstname` VARCHAR(255) DEFAULT '',
  CHANGE `employee_lastname` `employee_firstname` VARCHAR(255) DEFAULT '': Duplicate column name 'employee_firstname'

> [WARNING] SQL 1.7.5.0
>             1060 in ALTER TABLE `ps_product`
>   CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL,
>   CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL: Duplicate column name 'supplier_reference'

> [WARNING] SQL 1.7.5.0
>             1060 in ALTER TABLE `ps_stock_available`
>   ADD `location` VARCHAR(255) NOT NULL DEFAULT '' AFTER `out_of_stock`: Duplicate column name 'location'

**Comment by khouloudbelguith** [comment]
@rdy4ever, those warnings are fixed with this  PRs: https://github.com/PrestaShop/PrestaShop/pull/11814
Thanks!

**Comment by rdy4ever** [comment]
Hi, yes, I know. However, the error persists.

Pe 27 dec. 2018, la 15:23, khouloudbelguith <notifications@github.com> a scris:

**Comment by kris4net** [comment]
same for me 
PHP: 7.2.13 
1.7.4.4 -->1.7.5 ; 1-click up 4.5.1

**Comment by nuevoenesto** [comment]
Hi
I continue with this error after the sql update.
Thanks
Enrique

![image](https://user-images.githubusercontent.com/46094992/50488526-43c9f780-0a03-11e9-94a9-301c12806fe3.png)

**Comment by nuevoenesto** [comment]
The Logs are the same from dritancami user
![image](https://user-images.githubusercontent.com/46094992/50491879-e474e300-0a14-11e9-81f5-55950a637bd3.png)

**Comment by Quetzacoalt91** [comment]
Hello there,

I can't reproduce your issue by upgrading shops to 1.7.5.0, even with previous versions of the autoupgrade module.

But as far as I can tell, there is data missing in your database, especially regarding `PS_INVOICE_PREFIX`.

This SQL request could help you to get the access to the invoice page:

```sql
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_PREFIX"), 1, null, NOW());
```

Note you may have to replace the lang ID and the prefix used on your server.

Regards

**Comment by rdy4ever** [comment]
But still, I had no issue with the invoices page before upgrading to 1.7.5. I indeed used the ps_cleaner module to clear all orders, carts, clients and invoice test data before going live with my shop. Could this be the problem?

**Comment by ghost** [comment]
The query returns me the error:
`#1062 - Duplicate entry '39-1' for key 'PRIMARY'
`

**Comment by rdy4ever** [comment]
Hi @Quetzacoalt91 
I checked my database and I already have the correct enteries for both enabled langauges in `ps_configuration_lang` table, regarding `PS_INVOICE_PREFIX` :
![image](https://user-images.githubusercontent.com/12268701/50517964-bdbdb780-0abb-11e9-9a96-714606b47dff.png)

**Comment by kris4net** [comment]
same for me, ps_configuration_lang is correct.

**Comment by Quetzacoalt91** [comment]
Hmm, what about the legal free text? Here are the data from my shop after a quick test:

```
mysql> select * from ps_configuration where name = "PS_INVOICE_LEGAL_FREE_TEXT";
+------------------+---------------+---------+----------------------------+-------+---------------------+---------------------+
| id_configuration | id_shop_group | id_shop | name                       | value | date_add            | date_upd            |
+------------------+---------------+---------+----------------------------+-------+---------------------+---------------------+
|              360 |          NULL |    NULL | PS_INVOICE_LEGAL_FREE_TEXT | NULL  | 2018-12-28 15:38:40 | 2018-12-28 15:38:40 |
+------------------+---------------+---------+----------------------------+-------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from ps_configuration_lang where id_configuration = 360;
+------------------+---------+----------+---------------------+
| id_configuration | id_lang | value    | date_upd            |
+------------------+---------+----------+---------------------+
|              360 |       1 | fefefefe | 2018-12-28 15:38:40 |
|              360 |       3 |          | 2018-12-28 15:38:40 |
+------------------+---------+----------+---------------------+
2 rows in set (0.00 sec)

```

**Comment by ghost** [comment]
I get errors of execution:
`#1064 - Errore di sintassi nella query SQL vicino a 'mysql> select * from ps_configuration where name = "PS_INVOICE_LEGAL_FREE_TEXT"' linea 1`
`#1064 - Errore di sintassi nella query SQL vicino a 'mysql> select * from ps_configuration_lang where id_configuration = 360' linea 1`

**Comment by kris4net** [comment]
@ Quetzacoalt91 it's the same on my presta, except language which is 1051

**Comment by Quetzacoalt91** [comment]
Sorry, I copied the whole screen from my terminal. Do not copy the `mysql>` part when running the SQL requests. :)

**Comment by ghost** [comment]
Here's what I get. 1° query:
![schermata 2018-12-28 alle 17 31 43](https://user-images.githubusercontent.com/2458824/50521609-c798e800-0ac6-11e9-98c6-6e90a07422b1.png)
2° query:
![schermata 2018-12-28 alle 17 32 51](https://user-images.githubusercontent.com/2458824/50521610-ca93d880-0ac6-11e9-90db-c2a488e8fcbf.png)

**Comment by rdy4ever** [comment]
@dritancami 
in your case, for the 2nd query put in `id_configuration = 471`
In my case there is no entery in `ps_configuration_lang` for this. I'll create one and see if it helps.

**Comment by ghost** [comment]
Here it is 2° query:
![schermata 2018-12-28 alle 17 43 07](https://user-images.githubusercontent.com/2458824/50521873-2f036780-0ac8-11e9-90ac-bed0714b49cc.png)
![schermata 2018-12-28 alle 17 43 38](https://user-images.githubusercontent.com/2458824/50521875-31fe5800-0ac8-11e9-8664-313fa5c16606.png)

**Comment by rdy4ever** [comment]
Nope. Didn't help. Even though I was indeed missing these rows in `ps_configuration_lang`, adding them didn't fix the error.
`INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`, `date_upd`) VALUES ('390', '2', 'TEXT', '2018-12-28 00:00:00');`

**Comment by rdy4ever** [comment]
**SOLVED IT:**

- Run:

`SELECT * FROM ps_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT";`
`SELECT * FROM ps_configuration WHERE name = "PS_INVOICE_FREE_TEXT";`

Take note of `id_configuration` for both; THEN:
- Run:
`SELECT * FROM ps_configuration_lang WHERE id_configuration = ID`

replace `ID` with each ID returned before. 

If you get an empty response, like this:
![image](https://user-images.githubusercontent.com/12268701/50524233-3b45ef80-0add-11e9-9ab0-a0ed90bfcf99.png)
, it means that you have to add the row to the database, so:

- Run this query for each `id_configuration` missing form `ps_configuration_lang` and each language id:

`INSERT INTO `ps_configuration_lang` (`id_configuration`, `id_lang`, `value`, `date_upd`) VALUES ('ID', 'IDLANG', 'TEXT 1', NOW());`

For VALUES:
replace `ID`  with the `id_configuration` you returned from each querry.
replace `IDLANG` with the id of each enabled langauge.
`TEXT 1` -> whatever text, you will be able to replace it later.

**Comment by nuevoenesto** [comment]
Hi rdy4ever
How can view the IDLANG code?

Many thanks!.

**Comment by rdy4ever** [comment]
@nuevoenesto 
`SELECT * FROM ps_configuration_lang`
And see other rows for `id_lang`. If you only have one language enabled, you shoud have 1. If two, you shoud have 1 and 2, etc.

**Comment by nuevoenesto** [comment]
Thanks @rdy4ever 
I, made it but the error continues

Symfony\Component\Form\Exception\
UnexpectedTypeException
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 41)
PropertyPathMapper->mapDataToForms('#IN', object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData('#IN')
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => array('B13544762', 'B13544762'), 'footer_text' => array('B13544762', 'B13544762'), 'invoice_model' => 'invoice', 'use_disk_cache' => false), object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => array('B13544762', 'B13544762'), 'footer_text' => array('B13544762', 'B13544762'), 'invoice_model' => 'invoice', 'use_disk_cache' => false))
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (line 49)
PropertyPathMapper->mapDataToForms(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => array('B13544762', 'B13544762'), 'footer_text' => array('B13544762', 'B13544762'), 'invoice_model' => 'invoice', 'use_disk_cache' => false)), object(RecursiveIteratorIterator))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 379)
Form->setData(array('invoice_options' => array('enable_invoices' => true, 'enable_tax_breakdown' => false, 'enable_product_images' => false, 'invoice_prefix' => '#IN', 'add_current_year' => false, 'reset_number_annually' => false, 'year_position' => 0, 'invoice_number' => 0, 'legal_free_text' => array('B13544762', 'B13544762'), 'footer_text' => array('B13544762', 'B13544762'), 'invoice_model' => 'invoice', 'use_disk_cache' => false)))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 483)
Form->initialize()
in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php (line 226)
FormBuilder->getForm()
in src/Core/Form/FormHandler.php (line 114)

**Comment by rdy4ever** [comment]
This is strange, form me the error was fixed both on my staging and my production shops like this.

**Comment by rdy4ever** [comment]
@nuevoenesto could you send me a database dump to take a look? (Export as sql )

**Comment by rdy4ever** [comment]
@nuevoenesto 
Could you export the two tables and attach them here to take a look
form Export->Export method ->Custom ->deselect all tables and select just the two.

**Comment by rdy4ever** [comment]
@nuevoenesto 
Try this and screenshot the result:

> SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_PREFIX");
> SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_LEGAL_FREE_TEXT");
> SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_FREE_TEXT");

**Comment by nuevoenesto** [comment]
Hi @rdy4ever 
I attach the two tables exported

**Comment by nuevoenesto** [comment]
I try with this
Error

consulta SQL: Documentación

SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHEREname= "PS_INVOICE_LEGAL_FREE_TEXT") LIMIT 0, 25

MySQL ha dicho: Documentación
#1064 - Algo está equivocado en su sintax cerca '= "PS_INVOICE_LEGAL_FREE_TEXT") LIMIT 0, 25' en la linea 1

**Comment by nuevoenesto** [comment]
ok I corrected the sentence and show this
![image](https://user-images.githubusercontent.com/46094992/50525630-edc98280-0adc-11e9-9c0e-22f90bd1736a.png)

**Comment by rdy4ever** [comment]
@nuevoenesto 
You're missing rows for `PS_INVOICE_PREFIX`
Run this query and it should fix it:

INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_PREFIX"), 1, "#IN", NOW());

INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_PREFIX"), 5, "#IN", NOW());

**Comment by nuevoenesto** [comment]
@rdy4ever 
I receive this
 MySQL ha dicho: Documentación
#1062 - Entrada duplicada '42-1' para la clave 'PRIMARY'

**Comment by rdy4ever** [comment]
Tri this again:

SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_PREFIX");
SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT");
SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_FREE_TEXT");

and screenshot the whole page

**Comment by nuevoenesto** [comment]
ok, this is the result

![image](https://user-images.githubusercontent.com/46094992/50525894-ad6b0400-0ade-11e9-8fa3-b968213c7d5e.png)

**Comment by nuevoenesto** [comment]
![image](https://user-images.githubusercontent.com/46094992/50525906-c7a4e200-0ade-11e9-9e9d-50cd991fb7e4.png)

**Comment by nuevoenesto** [comment]
![image](https://user-images.githubusercontent.com/46094992/50525912-d390a400-0ade-11e9-8ffa-a7b1536ee48c.png)

**Comment by rdy4ever** [comment]
Ok, you're still missing one in `PS_INVOICE_PREFIX`. Run this, and then retry the Invoices page:

INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_PREFIX"), 5, "#IN", NOW());

**Comment by rdy4ever** [comment]
By the way, I can see that you actually have 5 enabled langauges, so maybe you need to run the SQL's for all missing languages

**Comment by rdy4ever** [comment]
@nuevoenesto, Run this to also fix if for langauages 2 and 3:

INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_PREFIX"), 2, "#IN", NOW());
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_PREFIX"), 3, "#IN", NOW());
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 2, "...", NOW());
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 3, "...", NOW());
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_FREE_TEXT"), 2, "...", NOW());
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_FREE_TEXT"), 3, "...", NOW());

**Comment by nuevoenesto** [comment]
YES!!!!!!!
MANY MANY THANKS!
THIS Run!

@rdy4ever  have a good 2019 year!

**Comment by rdy4ever** [comment]
@nuevoenesto Great! HNY!

**Comment by rdy4ever** [comment]
**SIMPLE SOLUTION TO TEST AND FIX THIS ERROR**
1. Take a look into `ps_configuration_lang` to check how many languages you have enabled and their corresponding id's:
`SELECT * FROM ps_configuration_lang`

2. Run this SQL on the database:
SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_PREFIX");
SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_LEGAL_FREE_TEXT");
SELECT * FROM ps_configuration_lang WHERE id_configuration = (select id_configuration FROM ps_configuration WHERE `name` = "PS_INVOICE_FREE_TEXT");

You should have an equal number of rows with the number of each enabled language for each of the three queries. [This is how the result looks like for a shop with 5 enabled languages.](https://imgur.com/5A0Y3Rx)
If any of the query returns empty or misses rows for some languages, then you will need to add the missing rows:

3. FIXING
**To fix missing `PS_INVOICE_PREFIX`:**
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_PREFIX"), 1, "#IN", NOW());

(replace 1 with each of your language ids (id_lang)

**To fix missing `PS_INVOICE_LEGAL_FREE_TEXT`:**
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 1, "TEXT", NOW());

(replace 1 with each of your language ids (id_lang)

**To fix missing `PS_INVOICE_FREE_TEXT`:**
INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM ps_configuration WHERE name = "PS_INVOICE_FREE_TEXT"), 1, "TEXT", NOW());

(replace 1 with each of your language ids (id_lang)

Also, if your table prefix isn't `ps`, use own prefix for all queries.

**Comment by rdy4ever** [comment]
@dritancami 
Run this SQL:

INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 1, "TEXT", NOW());
INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 2, "TEXT", NOW());

I put 1 and 2 as I assume that you have two enabled languages (with id's 1 and 2), but adjust the SQL if otherwise. I think it should fix it for you.
Edit: your prefix is chy, so I updated the sql.

**Comment by kris4net** [comment]
> SIMPLE SOLUTION TO TEST AND FIX THIS ERROR

@rdy4ever  big thanks, this works!!
Happy new year !!!

**Comment by ghost** [comment]
> INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 2, "TEXT", NOW());

Hi @rdy4ever , I run the query, but the problem is not solved:
![schermata 2018-12-29 alle 01 42 28](https://user-images.githubusercontent.com/2458824/50531508-5f202a00-0b0b-11e9-983a-a37959868f8d.png)
![schermata 2018-12-29 alle 01 44 22](https://user-images.githubusercontent.com/2458824/50531511-634c4780-0b0b-11e9-87d7-7f88a34323bf.png)

**Comment by rdy4ever** [comment]
Could you export just the two tables (chy_configuration and chy_configuration_lang) as sql and attach them here? I’ll take a look and tell you exactly what sql’s you should run to fix the error.

Trimis de pe iPhone‑ul meu

Pe 29 dec. 2018, la 02:46, Dritan Cami <notifications@github.com> a scris:

**Comment by ghost** [comment]
Here:
[config.sql.zip](https://github.com/PrestaShop/PrestaShop/files/2716279/config.sql.zip)
[config-lang.sql.zip](https://github.com/PrestaShop/PrestaShop/files/2716280/config-lang.sql.zip)

**Comment by rdy4ever** [comment]
@dritancami 
Run this SQL and I think your problem will be solved:

INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_FREE_TEXT"), 1, "TEXT", NOW());
INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_FREE_TEXT"), 2, "TEXT", NOW());

**Comment by ghost** [comment]
Hi, I run the query, but the problem is not solved..

**Comment by rdy4ever** [comment]
Could you screenshot the stack trace after this sql?

**Comment by ghost** [comment]
Sure:
![schermata 2018-12-29 alle 12 31 29](https://user-images.githubusercontent.com/2458824/50537834-b357f800-0b65-11e9-9220-02be0fcbb487.png)

**Comment by rdy4ever** [comment]
@dritancami 
No, I meant a screenshot of the errror (Exception and stack trace tabs)

**Comment by rdy4ever** [comment]
@dritancami Please run this SQL one more time and screenshot the whole response page (I need to see the result for each of the 3 queries):

SELECT * FROM chy_configuration_lang WHERE id_configuration = (select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_PREFIX");
SELECT * FROM chy_configuration_lang WHERE id_configuration = (select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT");
SELECT * FROM chy_configuration_lang WHERE id_configuration = (select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_FREE_TEXT");

It should look like this, with two rows for each query:
![image](https://user-images.githubusercontent.com/12268701/50537936-a0e2bc00-0b6f-11e9-8b70-9e2e353801d0.png)

**Comment by ghost** [comment]
> @dritancami
> No, I meant a screenshot of the errror (Exception and stack trace tabs)

![schermata 2018-12-29 alle 13 56 41](https://user-images.githubusercontent.com/2458824/50538587-e902de00-0b71-11e9-9e7a-5260ec12ed1c.png)
![schermata 2018-12-29 alle 13 56 57](https://user-images.githubusercontent.com/2458824/50538588-ed2efb80-0b71-11e9-811f-e1690f8f52f5.png)
![schermata 2018-12-29 alle 13 58 57](https://user-images.githubusercontent.com/2458824/50538592-f029ec00-0b71-11e9-85ed-55962725dd5e.png)

**Comment by ghost** [comment]
> Please run this SQL one more time and screenshot the whole response page (I need to see the result for each of the 3 queries):

![schermata 2018-12-29 alle 14 01 15](https://user-images.githubusercontent.com/2458824/50538623-5f9fdb80-0b72-11e9-95af-c59816f8ff48.png)
![schermata 2018-12-29 alle 14 01 49](https://user-images.githubusercontent.com/2458824/50538625-629acc00-0b72-11e9-9ac5-8f3601e3f224.png)
![schermata 2018-12-29 alle 14 02 13](https://user-images.githubusercontent.com/2458824/50538626-6595bc80-0b72-11e9-9fce-723e021a5da6.png)

**Comment by rdy4ever** [comment]
@dritancami I see you still don't have "legal_free_text". Please run both of these SQLs:

INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 1, "TEXT", NOW());
INSERT INTO chy_configuration_lang (id_configuration, id_lang, value, date_upd) values ((select id_configuration FROM chy_configuration WHERE name = "PS_INVOICE_LEGAL_FREE_TEXT"), 2, "TEXT", NOW());

**Comment by rdy4ever** [comment]
@dritancami if it still doesn't work, you could just DROP `chy_configuration_lang` and reimport it from the attached SQL
[chy_configuration_lang.zip](https://github.com/PrestaShop/PrestaShop/files/2716388/chy_configuration_lang.zip)

**Comment by ghost** [comment]
Hurray, the problem is now solved! Thanks a lot @rdy4ever! Thanks - Thanks - Thanks!!!

**Comment by rdy4ever** [comment]
@dritancami Great!

**Comment by mavayit333** [comment]
[Watch Ruby reid Onlyfans s – Lesbian Sex Tape With Splatxo](https://porncheck.live/archives/4151)

[Watch Anna Malygon/Maligoshik Play Dildo On Bed ](https://porncheck.live/archives/3502)
 
Watch [Alexisshv – Riding With Dildo ](https://porncheck.live/archives/7674)

[Watch Jellybeanbrains Onlyfans Blowjob Skill Pro ](https://porncheck.live/archives/4131)

[Watch Kawaiisofey / Aishah Sofey Nude – Fuck BackSide ](https://porncheck.live/archives/6577)

[Watch Kelsey Lawrence s – Doggy Style ](https://porncheck.live/archives/5644)

[Watch Hannah Becker Onlyfans – Fuck With dildo]( https://porncheck.live/archives/6859)

[Watch Marie Temara Onlyfans – POV Dildo Ride Porn ](https://porncheck.live/archives/3142)
 
[Watch Mellooow – Nude Play Body  ](https://porncheck.live/archives/4152)

[Watch Itscarlyjane Onlyfans – Play With Dildo](https://porncheck.live/archives/4832)

[Watch Camilla Araujo Onlyfans s – Nude Shower Tease Boobs](https://porncheck.live/archives/3945)
