### ISSUE TITLE
faceted search 2.2.1 doesn't show results with color/ patterns of Attributes 0 Stock. PS 1.7.5

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#12143]
When you filter color/pattern attributes, the module doesn't show results of combinations out of stock.

Reproduce
- PS 1.7.5 clean or old installation
- faceted search update from 2.2.0 to 2.2.1
- sample products change a combination to stock 0

**Comment by khouloudbelguith** [comment]
Hi @pdkey,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & ps_facetedsearch v2.2.1.
Before the upgrade with Color "Yellow" => it is displayed ( ps_facetedsearch v2.2.0)
![image](https://user-images.githubusercontent.com/16067358/51176801-27143780-18be-11e9-8e7c-0c4078b0af60.png)
After the upgrade, the "Attribute filter "Yellow" is displayed with a wrong result ( ps_facetedsearch v2.2.1)
![image](https://user-images.githubusercontent.com/16067358/51176892-6b073c80-18be-11e9-99ef-70754d9b1c5f.png)
This issue is related to this ticket: https://github.com/PrestaShop/PrestaShop/issues/10018
It is caused by this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/43
We will see how to fix it.
Thanks!

**Comment by dineshbadrukhiya** [comment]
I think we can edit the code for this issue:
ps_facetedsearch/ps_facetedsearch.php (approx line 1423)

`ON (sa.`id_product_attribute` = pac.`id_product_attribute` AND sa.`quantity` > 0)`

Replace it with:
`ON (sa.`id_product_attribute` = pac.`id_product_attribute` AND sa.`quantity` >= 0)`

**Comment by khouloudbelguith** [comment]
Hi @dineshbadrukhiya,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/ps_facetedsearch
Thank you!

**Comment by dineshbadrukhiya** [comment]
@khouloudbelguith I will open PR for this fix.

**Comment by sarahdib** [comment]
This issue is fixed with the 3.0.0 version of the module Faceted search.

**Comment by antoniocici** [comment]
The issue is still present in the version 3.6.0 of the Faceted search module. 

I've managed to solve the issue by modifying the file:

modules/ps_facetedsearch/src/Product/Search.php

at line 147, modifying the source code from this:
 
```
                case 'id_attribute_group':
                    $operationsFilter = [];
                    foreach ($filterValues as $attributeId => $filterValue) {
                        $this->getSearchAdapter()->addOperationsFilter(
                            'with_attributes_' . $attributeId,
                            [[['id_attribute', $filterValue]]]
                        );
                    }
                    break;
```

to this:

```
                case 'id_attribute_group':
                    $operationsFilter = [];
                    foreach ($filterValues as $attributeId => $filterValue) {
                        $this->getSearchAdapter()->addOperationsFilter(
                            'with_attributes_' . $attributeId,
                            [[['id_attribute', $filterValue]]]
                        );
                    }
                    //modded by Antonio to hide Out of Stock combinations
                    $operationsFilter = [];
                    $operationsFilter[] = [
                        ['quantity', [0], '>'],
                    ];
                    $this->getSearchAdapter()->addOperationsFilter(
                        self::STOCK_MANAGEMENT_FILTER,
                        $operationsFilter
                        );
                    break;
```

and now it works!

**Comment by marionf** [comment]
@hibatallahAouadni Could you try to reproduce this issue with the last version of ps_facetedsearch and reopen it if you can reproduce it ?

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

The only issue that I managed to reproduce is this #10018 see the attached screen record below:

https://drive.google.com/file/d/1SZ5ETLmoTONcwlX6KP66iiedeCg7gs7p/view

https://drive.google.com/file/d/1yS17yBxSG7lfVLeS0lDnNuLCRxY9E1EN/view

Please check and feedback.
Thanks!

**Comment by marionf** [comment]
Thank you @hibatallahAouadni

**Comment by qumuq-til** [comment]
@antoniocici Could you also extend your patch to fix the number of products displayed in the filter (when "Show the number of matching products" is enabled)?
Also, some options should disappear from the filter when out of stock - otherwise selecting those options leads to an empty page.
