### ISSUE TITLE
If customer has no postcode a 500 error is thrown in the checkout

### ISSUE THREAD

**Issue by wtbi** [PrestaShop/PrestaShop#12273]
500 error thrown when customer has no postcode
As a customer, if I have an address that doesn't need a postcode (for example: Ireland) and I go to the checkout I get a 500 error.

**To Reproduce**
1. Add a customer to Prestashop with their country as Ireland
2. In the Location, set Ireland to not require a postcode
2. Set the postcode field as none mandatory
3. Go to the frontend and sign in as the customer
4. Put a product into the basket
5. Go to the checkout
6. See the error

**Screenshots**
<img width="1393" alt="screenshot 2019-01-23 at 12 28 46" src="https://user-images.githubusercontent.com/14834860/51606688-83a0d380-1f0a-11e9-92ae-e98544679d18.png">
<img width="958" alt="screenshot 2019-01-23 at 12 29 02" src="https://user-images.githubusercontent.com/14834860/51606697-87ccf100-1f0a-11e9-8f36-194b98d06af2.png">

**Additional information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @wtbi,

What is the exact PrestaShop version did you use?
I did not manage to reproduce the issue with fresh install PS1.7.5.0
https://drive.google.com/file/d/1UpAW9cp_H9XlgMrv8Ut2pJl-sZU2qZ35/view
This issue is fixed previously with this PR: https://github.com/PrestaShop/PrestaShop/pull/8435
Thanks to check & feedback.

**Comment by wtbi** [comment]
Hi @khouloudbelguith 

I had the issue with PS 1.7.3.2 but the issue remained after I updated to 1.7.5.0

Thanks,

**Comment by khouloudbelguith** [comment]
@wtbi, I tried also with fresh installation PS1.7.3.2 & it is fixed.
https://drive.google.com/file/d/1bxgOKVSlyUnuXMLgQyFaZL1-1ObuU2mZ/view
This issue is fixed in the PrestaShop 1.7.3.0.
THanks!

**Comment by wtbi** [comment]
@khouloudbelguith - I solved this issue by moving my theme to a fresh installation of 1.7.5.0.

Thanks,
D.

**Comment by khouloudbelguith** [comment]
@wtbi, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
