### ISSUE TITLE
Export component

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#12524]
For upcoming 1.7.6 version we cannot leave exporting data like that:

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController.php#L338

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php#L795

We need some data export component or at least add some hooks. @matks wdyt?

**Comment by matks** [comment]
@sarjon I think there's already quite a lot of things for 1.7.6 😞 it's a good idea but will probably be handled later

**Comment by PierreRambaud** [comment]
@matks Could you explain to us a little bit more? :sweat_smile:

**Comment by matks** [comment]
@PierreRambaud I think when this issue was written, the URLs were showing something else 😄 

My guess is that in our current architecture, on listing pages, the "export data" action are done in a very simplistic and limited way:
```
    // CategoryController.php
    public function exportAction(CategoryFilters $filters)
    {
        $filters = new CategoryFilters(['limit' => null] + $filters->all());
        $categoriesGridFactory = $this->get('prestashop.core.grid.factory.category');
        $categoriesGrid = $categoriesGridFactory->getGrid($filters);

        $headers = [
            'id_category' => $this->trans('ID', 'Admin.Global'),
            'name' => $this->trans('Name', 'Admin.Global'),
            'description' => $this->trans('Description', 'Admin.Global'),
            'position' => $this->trans('Position', 'Admin.Global'),
            'active' => $this->trans('Displayed', 'Admin.Global'),
        ];

        $data = [];

        foreach ($categoriesGrid->getData()->getRecords()->all() as $record) {
            $data[] = [
                'id_category' => $record['id_category'],
                'name' => $record['name'],
                'description' => $record['description'],
                'position' => $record['position'],
                'active' => $record['active'],
            ];
        }

        return (new CsvResponse())
            ->setData($data)
            ->setHeadersData($headers)
            ->setFileName('category_' . date('Y-m-d_His') . '.csv');
    }
```

- the choice of data to be exported is defined by used filters (not intuitive*)
- available columns are hardcoded (hence the suggestion for hooks)

*For example if you open the 1st page, you'll see the 50 first records (because it's paginated). You hit the "export" button and it only exports the 50 1st records although you expected the full listing to be exported.

So the suggestion was to build an Export component to be used in all Listing pages, which would address the current limitations in a smart and friendly way.

**Comment by PierreRambaud** [comment]
This is something we already fixed: #16328  :thinking:

**Comment by matks** [comment]
> This is something we already fixed: #16328 🤔

Only the "limited number of data exportable" issue. The main issue remains: we use the Grid, which is not built for Export, as a DataFetcher service then we create a CSV file using hardcoded values and it is not extensible (no hooks).

**Comment by PierreRambaud** [comment]
We should be able to add hooks for the job, it should be enough, what do you think?
