### ISSUE TITLE
Customer group tax setting ignored in product volume discounts on PS 1.7.5.0

### ISSUE THREAD

**Issue by raphaelboos** [PrestaShop/PrestaShop#12538]
In Prestashop 1.7.5.0, Classic template, the customer group settings for price display excluding tax are ignored on product pages with volume discounts.

There are 2 similiar reports but they do not address volume discounts
1. #9856 (Discount problems for customers without VAT) or 
2. #12199 (Wrong prices for groups without tax ) 

**To Reproduce**
1. Create a user account X in the frontend
2. Create a new user group Y in the backend, go to group configuration and set price display option to "tax excluded. 
3. Assign the user account X to the new user group Y and remove all other groups.
4. Create a product Z with volume discounts in the backend for the user group Y.
5. Login to your shop frontend with your user account X and open the product page.
6. While the main product price is displayed net, volume prices are displayed gross including VAT.

**Additionnal information**
PrestaShop version: 1.7.5.0
Template/Theme: Classic
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @raphaelboos,

Your issue is it fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/11103?
It is fixed in the PS1.7.6.
It fixes this ticket: #9696 which is similar to your issue.
Thanks to check & feedback.

**Comment by raphaelboos** [comment]
Hi @khouloudbelguith,

I applied the patch #11103 to 1.7.5. but this did not solve the problem with volume (quantitity) discounts. 
Price output in Classic Theme though https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-discounts.tpl still gross.

**Comment by khouloudbelguith** [comment]
@raphaelboos, thanks for your feedback.
So, your issue is that the quantity discount has a wrong calculation when price display method is tax excluded as described in this ticket: #9929?
Thanks!

**Comment by raphaelboos** [comment]
Hi @khouloudbelguith,
yes, i can comfirm, that this is the same problem as described in #9929.

**Comment by khouloudbelguith** [comment]
@raphaelboos, this issue is added to our bug roadmap.
Your ticket is a duplicate of #[9929](https://github.com/PrestaShop/PrestaShop/issues/9929).
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9929
