### ISSUE TITLE
Problem Quantities with combination 1.7.5

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#13118]
Hello, I use PS 1.7.5
I notice that when I go on my products that has combination and I change adding 0 quantities 
everything is ok but on the homepage of products it displays wrong quantities. Why?

Here some picture:
<img width="1178" alt="Schermata 2019-03-30 alle 14 44 43" src="https://user-images.githubusercontent.com/47249256/55276940-9e246e00-52fa-11e9-9a0f-93fee7eae747.png">
<img width="902" alt="Schermata 2019-03-30 alle 14 44 27" src="https://user-images.githubusercontent.com/47249256/55276941-9e246e00-52fa-11e9-81bb-ce20212de3fa.png">

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

I did not manage to reproduce the issue with PS:1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1UVTEeP0mWwgVKYl0DSBRQmAuDT5xoWx3/view 
What is the exact version of Prestashop did you used?

Thanks!

**Comment by morghy1992** [comment]
@khouloudbelguith 

thank you for the replay. 
I use 1.7.5

I went into : Catalog - Stocks and I need to change from there the quantities because if I'll go to the product - combination and add 0 quantities give me for example still 30 quantities available so I have to go in stock and change with -15 and - 15 to have 0. 

I also notice when I went into phpmyADM that I do not have the file ps_stock_available.
Is it normal?

**Comment by khouloudbelguith** [comment]
@morghy1992, it is not normal.

**Comment by morghy1992** [comment]
@khouloudbelguith do you know why? :(

**Comment by khouloudbelguith** [comment]
@morghy1992, did you do an upgrade?

**Comment by morghy1992** [comment]
@khouloudbelguith last months I did from 1.7 to 1.7.5

**Comment by khouloudbelguith** [comment]
@morghy1992, did you make a backup of the database?

**Comment by morghy1992** [comment]
@khouloudbelguith  yes I did it from Sql

**Comment by khouloudbelguith** [comment]
@morghy1992, is the table exists?

**Comment by morghy1992** [comment]
@khouloudbelguith yes I have it

**Comment by khouloudbelguith** [comment]
@morghy1992, does your problem is solved?

**Comment by morghy1992** [comment]
@khouloudbelguith still have the problem. I went into Catalog - stock and modified the quantities then 
If I go on products give me wrong quantities. This is very strange

**Comment by khouloudbelguith** [comment]
@morghy1992, could you please clear cache, check your shop with another browser and feedback.

**Comment by ghost** [comment]
I can say that also have similar problem with quantities... Store twice updated 1.7.3.4 1.7.4.5 to 1.7.5.1. Everything looks good at every upgrade process but suddenly i noticed weird things going with product quantities :(...

**Comment by khouloudbelguith** [comment]
Hi @marionf,

What do you think? In my case, I did not manage to reproduce the issue.

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.

Best regards.

**Comment by neich78** [comment]
Hi, I have the same problem with version 1.7.6.4. In some products, the total quantity in Product_Catalog summary is not the same as sum of combinations stock. There's no way to change it or update it. 
For example, product id=3 has 335 items in summary and the real stock in combinations is 103. 
![Captura de pantalla 2020-04-30 a las 9 40 55](https://user-images.githubusercontent.com/11721870/80685008-d6cae400-8ac6-11ea-922a-e4cc799a006b.png)
![Captura de pantalla 2020-04-30 a las 9 40 44](https://user-images.githubusercontent.com/11721870/80685019-db8f9800-8ac6-11ea-8d6a-3b87470cd22d.png)
