### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#13913]
Prestashop 1.7.5.2 on php 7.2.18
often I've this error:
Fatal error: require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/dev/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php on line 86

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Thanks!

**Comment by centoasa** [comment]
already done many times, but issue happens again
Also tried to not use prestashop cache, but issue still remain.
Issue happens also when I try to update traffic/seo/setting url

**Comment by centoasa** [comment]
Maybe related to this apache issue?
`AH01071: Got error 'PHP message: PHP Fatal error: require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/dev/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php on line 86\n', referer: https://www.100asa.it/Back100asa/index.php/sell/catalog/products/89?_token=zz5300G_3YKdCaoCENWDX5Gkhhhhm8tZPyFI-wfxj8Q
`

**Comment by khouloudbelguith** [comment]
@centoasa, the fatal error related to file in the cache
Thanks!
This is afresh installation PS1.7.5.2?

**Comment by centoasa** [comment]
No, is not a fresh installation. Is a 1.7 first release updated from time to time

**Comment by khouloudbelguith** [comment]
@centoasa, Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
Thanks to check and feedback.

**Comment by centoasa** [comment]
Now seems it working well

**Comment by khouloudbelguith** [comment]
@centoasa, it is a cache issue.
I close the ticket, feel free to open a new one when needed.
Thanks!

**Comment by centoasa** [comment]
I'd really like to re-enable the cache, so if you could pass on this error to the developers it would be great.

**Comment by khouloudbelguith** [comment]
@centoasa, if you enable smarty cache, the issue remains again?
Thanks!

**Comment by centoasa** [comment]
Just enable smarty cache, and I've:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
But website not crashed and relogin seems all works well.
I'm continuing to works and let you know

**Comment by khouloudbelguith** [comment]
@centoasa, could you please try to enable the debug mode et provide me the exact exception displayed.
Thanks!

**Comment by centoasa** [comment]
again-->
`Fatal error: require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/dev/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php on line 86`

79.7.101.x is my public ip address--> https://nimb.ws/B5nNxY

to make my webste working, I've to delete manually /var/cache/*

**Comment by khouloudbelguith** [comment]
@centoasa, if you set the option "Template compilation" to Force compilation / "Recompile templates if the files have been updated" and clear cache, the cache is enabled in this case => you have the same error?
Thanks!

**Comment by centoasa** [comment]
always-->
`Fatal error: require_once(): Failed opening required '/var/www/vhosts/100asa.it/httpdocs/var/cache/dev/appParameters.php' (include_path='/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear_exception:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/console_getopt:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/pear-core-minimal/src:/var/www/vhosts/100asa.it/httpdocs/vendor/pear/archive_tar:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/100asa.it/httpdocs/config/bootstrap.php on line 86`

**Comment by khouloudbelguith** [comment]
@centoasa, in my case, I did not manage to reproduce the issue with PS1.7.5.2.
After removal of cache `rm -fR var/cache/*` thanks to run those commands

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

THanks!

**Comment by centoasa** [comment]
for me --> Could not open input file: ./bin/console

**Comment by centoasa** [comment]
[OK] Cache for the "dev" environment (debug=true) was successfully cleared.
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
re-activate smarty cache, we hope all continue to works! I keep you updated

**Comment by centoasa** [comment]
just try to rebuild products/home-default images, server crashed, clear again cache directly by server, and prestashop goes up!

**Comment by khouloudbelguith** [comment]
Hi @centoasa, when smarty cache is disabled & you try to regenerate images => same issue occurs or not?

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith yes it's right! 
but not only this: I'm trying to update a "ps_facetedsearch v2.2.1 to v3.0.1" prestashop module and all prestashop crashes and crashes the server
https://nimb.ws/buaRit

**Comment by centoasa** [comment]
I've just installed and upgrading other modules without any issue or problems; so I think there's something borken in this module upgrade ps_facetedsearch v2.2.1 to v3.0.1

**Comment by khouloudbelguith** [comment]
@centoasa, We released a 3.0.2 which this the upgrade problem is there are many products/categories.

Thanks!

**Comment by centoasa** [comment]
@khouloudbelguith thank you so much, but in my backoffice still see v2.2.1 --> v3.0.1
 https://nimb.ws/vREd6X

**Comment by khouloudbelguith** [comment]
@centoasa, you can download zip here: https://github.com/PrestaShop/ps_facetedsearch/releases
Can I close this issue? your ps_facetedsearch issue is similar to this ticket: #13938
THanks!

**Comment by centoasa** [comment]
Thanks a lot @khouloudbelguith Now all works charme!
Please close this issue!

**Comment by khouloudbelguith** [comment]
@centoasa, great!
Feel free to open a new one when needed.

Thanks!

**Comment by centoasa** [comment]
And now the smarty clear cache button works well!

**Comment by fmipsylone** [comment]
@khouloudbelguith 
Hi,
I had the same problem on a 1.7.5.1. The main problem came from the generation of `var/cache/prod|dev/appParameters.php` without any permissions set.

AND I followed the @centoasa workaround here.
SO Disabling the Zend Opcache solved the problem. 

This issue is very closed and linked to issue #13050.

I think that **it would be wiser to re-open the issue** while it is not cleared solved with OPcache enabled. And it would be wiser to not consider it as solved with some cache workaround manipulations that we are not sure of the real effects...

Because the problem appears whereas I followed the PHP-FPM optimizations we can expect from the official PrestaShop documentation: [See devdocs](https://devdocs.prestashop.com/1.7/scale/optimizations/)
So disabling the Zend Opcache does not respect PrestaShop setup optimizations expectations as they are indicated in devdocs, I quote the doc below: 

> Also, your favorite ecommerce project made sure it’s fully compatible with OPCache.

**Comment by khouloudbelguith** [comment]
Hi @fmipsylone,

Your issue seems to be similar to this: https://github.com/PrestaShop/PrestaShop/issues/10998
& it is fixed by following these steps: https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-476361695
Fixed with this PR: https://github.com/PrestaShop/docker/pull/193
Thanks!

**Comment by fmipsylone** [comment]
Thank you @khouloudbelguith,

This seems to work for me !
Just to notice that `opcache.fast_shutdown` has been deleted start from [PHP 7.2](https://www.php.net/manual/fr/opcache.configuration.php#ini.opcache.fast-shutdown), so the remaining settings I use are:
```
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
```
May be It would be interesting to mention that in [PrestaShop devdoc page](https://devdocs.prestashop.com/1.7/scale/optimizations/)

Thanks.

**Comment by khouloudbelguith** [comment]
@fmipsylone, thanks to open a new issue in the [docs repository](https://github.com/PrestaShop/docs).

Thanks!

**Comment by fabiodc95** [comment]
> @centoasa, Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.
> Thanks to check and feedback.

Hello @khouloudbelguith  I've the same problem here, but I cannot access to PS Backoffice to force the cache compilation. How can I get the same result using only files and db access?

I've already checked if the PS_SMARTY_CACHE, PS_JS_THEME_CACHE, PS_CSS_THEME_CACHE params were set to 0 in the PS_CONFIGURATION table and they were; then I set also _PS_SMARTY_FORCE_COMPILE_ to 1. None of these changes helped me.

Thanks
