### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Gftec** [PrestaShop/PrestaShop#14013]
**Describe the bug**
When I log in or try to reconnect to manage my shop, add a product, edit or create a category, I always get this error message : Invalid Token: Accessing this link may result in a possible security issue.

I have contacted my hosting provider, this is his report :
Another option could be the error we see in the error_log of your https://www.vente-ordi.store/psadmin/error_log:

[27-May-2019 16:45:05 Europe/Paris] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/venteord/public_html/controllers/admin/AdminFeaturesController.php:624) in /home/venteord/public_html/classes/controller/AdminController.php on line 1877

**To Reproduce**
1. Go to 'https://www.vente-ordi.store/psadmin/index.php/security/compromised?uri=https%253A%252F%252Fwww.vente-ordi.store%252Fpsadmin%252Findex.php%252Fimprove%252Fmodules%252Fmanage%253F&_token=gRNqIhicJLxm77Rjjdb88vrjSR8IQWJXt5EmMFSZxfA'
![Jeton non valide](https://user-images.githubusercontent.com/51158048/58549570-1c729300-820c-11e9-9efd-22e43db82da2.png)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.1.29

**Comment by khouloudbelguith** [comment]
Hi @Gftec,

This Lifetime of back office cookies can be easily adjusted in the following folder:
`classes / controller / AdminController.php`
Look for the following code is to be found:
`if ($this->context->cookie->last_activity + 900 < time()) {`
Changing 900 to 3600 increases the log-in period from 15 to 60 minutes.
![image](https://user-images.githubusercontent.com/16067358/50767768-60c1be80-127e-11e9-9710-56a11163f55e.png)
Thanks to check and feedback.

**Comment by Gftec** [comment]
Hi khouloudbelguith
Thanks for your reply and help.
I Have applied the change here, screenshot enclosed. 
Do I need to make any other change?
![AdminController php   cPanel File Manager v3](https://user-images.githubusercontent.com/51158048/58552423-a7ef2280-8212-11e9-8c62-1c2d85056983.png)

I really hope this going to resolve the issue definitely.

Thank a lot,

Best regards,
Gftec

**Comment by khouloudbelguith** [comment]
@Gftec, no just increase the lifetime of cookies.
So, now, your issue is solved?

Thanks!

**Comment by Gftec** [comment]
No, I'm still experiencing an issue when I start a new session.

**Comment by khouloudbelguith** [comment]
@Gftec, when you navigate to your BO like this URL: `http://your shop/admin-folder ` you have the same issue.
In your case, your BO link: https://www.vente-ordi.store/psadmin

after signing in => you are redirected to the token page?

Thanks!

**Comment by Gftec** [comment]
When my session expires and that I refresh the browser, I'm redirected to the token page.

**Comment by khouloudbelguith** [comment]
@Gftec, this is normal behavior, because your session is ended.
the lifetime of cookies is exceeded.

Thanks!

**Comment by Gftec** [comment]
Thank you .

**Comment by khouloudbelguith** [comment]
@Gftec, you are welcome!
Can I close the issue?

Thanks!

**Comment by Gftec** [comment]
Yes, thank you.

**Comment by khouloudbelguith** [comment]
@Gftec, feel free to open a new one when needed.
Thanks!

**Comment by Gftec** [comment]
Thanks
Regards,

Gilbert Fautré
GF-TECHNOLOGIES.COM
33 LE BREUIL
17150 SAINT MARTIAL DE MIRAMBEAU
0546709466 / 0650684714
Vente de matériel informatique : https://www.vente-ordi.store/
Marketing numérique : https://www.gf-technologies.co/


Le mer. 29 mai 2019 à 15:45, khouloudbelguith <notifications@github.com> a
écrit :
