### ISSUE TITLE
Hello I have big problem with the subject email 

### ISSUE THREAD

**Issue by yassine1812** [PrestaShop/PrestaShop#14891]
Hello 

I upgraded to 1.7.6 and since when the customers receive the email of confirmation, in the subject, I don't have the name of my shop but I have [PrestaShop] (please check the picture) 
<img width="1440" alt="Capture d’écran 2019-07-28 à 22 38 59" src="https://user-images.githubusercontent.com/53042056/62012739-6b946000-b18a-11e9-9812-1c61bdbc885a.png">

I don't know how can I do 

thanks 

Version de PrestaShop : 1.7.6.0
Version de PHP : 7.2.19

**Comment by khouloudbelguith** [comment]
Hi @yassine1812,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screenshot
![image](https://user-images.githubusercontent.com/16067358/62034203-78926d00-b1e5-11e9-99c1-8c20ffc304a2.png)
Could you please navigate to the BO => Shop Parameters => Contact => Stores Tab & edit your shop name.
![image](https://user-images.githubusercontent.com/16067358/62034387-d7f07d00-b1e5-11e9-9b17-69513584b5fe.png)

Thanks to check & feedback.

**Comment by yassine1812** [comment]
Hello friend

thanks for your reply :) 

The name shop is right, it's my name shop

**Comment by khouloudbelguith** [comment]
@yassine1812, could you please try to navigate to the BO => Shop Parameters => General => Enable "Multistore".
Then go to the BO => Advanced Parameters => Multistore => Edit your shop => & edit the shop name & save => after that try to disable multistore.
![image](https://user-images.githubusercontent.com/16067358/62037610-02453900-b1ec-11e9-96a7-1764ab2dabcb.png)

Thanks to check & feedback

**Comment by yassine1812** [comment]
Hello 

yes perfect it's working now :) but I don't know why I lost all my small category, isn't a problem I can create again, do you know why ?

**Comment by khouloudbelguith** [comment]
@yassine1812, when trying to save your shop; you didn't select all your categories.
You just selected your subcategories.
![image](https://user-images.githubusercontent.com/16067358/62040762-18ee8e80-b1f2-11e9-88f0-3c26c94b564b.png)
 
Thanks!

**Comment by yassine1812** [comment]
Ok no problem thanks for your help :)

**Comment by khouloudbelguith** [comment]
@yassine1812, you are welcome.
Since it is fixed.
 close the issue, feel free to open a new one when needed.

Thanks!

**Comment by FaustoBoscaro** [comment]
This is NOT SOLVED, all my subcategories are desappered and there's no way to show them back!!!!

**Comment by FaustoBoscaro** [comment]
> @yassine1812, when trying to save your shop; you didn't select all your categories.
> You just selected your subcategories.
> ![image](https://user-images.githubusercontent.com/16067358/62040762-18ee8e80-b1f2-11e9-88f0-3c26c94b564b.png)
> 
> Thanks!

This solution cause to my shop worst problems!!!!

**Comment by khouloudbelguith** [comment]
Hi @FaustoBoscaro,

In the Multistore page, The sub-categories issue is reported here: https://github.com/PrestaShop/PrestaShop/issues/9701
It is added to our bug roadmap.

Thanks!
