### ISSUE TITLE
Faceted navigation - Multiple filter problems

### ISSUE THREAD

**Issue by itnomic** [PrestaShop/PrestaShop#14999]
**Bug**
After module upgrade from 2.x.x to 3.x.x I'm not able to filter articles correctly. I have the issue on different shops. I tried also do make a clean install of the module and use the original classic-template without any changes but it doesn't help. After downgrading to 2.x.x I don't have the bug anymore.

**Video**
https://streamable.com/l24ea

**Forum**
https://www.prestashop.com/forums/topic/992476-faceted-navigation-filterig-product-with-multiple-features/?tab=comments#comment-3141380

**Versions**
PrestaShop version: 1.7.5.2 and 1.7.6.0
Module-Version: 3.2.0
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @itnomic,

I did not manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.0.6 & v3.2.0.
I attached a screen record
https://drive.google.com/file/d/1ijnUVPviyCYwdeseFbHAUW5oxeNYS-WS/view
This issue is fixed with this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/72 (fixes this issue: https://github.com/PrestaShop/PrestaShop/issues/13985#issuecomment-496228818)

Thanks to check & feedback.

**Comment by itnomic** [comment]
Hi, 
no, the problem still exists on many shops, see prestashop community. What php-version do you use? I made a longer video, i was upgrading the module from 2.x.x to 3.x.x.. Maybe it is a problem after upgrading to the new major version?

Video 2:
https://streamable.com/fw81e

**Comment by khouloudbelguith** [comment]
@itnomic, Could you please provide me the access to your shop to test it.
This is a public space.
You can provide me the credentials by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

Thanks!

**Comment by itnomic** [comment]
sure, you got an e-mail! Thank you!

**Comment by khouloudbelguith** [comment]
@itnomic, yes!
I will check & feedback

**Comment by khouloudbelguith** [comment]
@itnomic, I tried with a shop installed with Deutch language/ Germany country => but I did not manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.2.0.
In your case, it is different.
After installing your module ps_facetedsearch v3.2.0.
Could you please check in your module folder if those files are uploaded in your module
https://github.com/PrestaShop/ps_facetedsearch/pull/72/files
Thanks!

**Comment by itnomic** [comment]
I also tried a new clean Prestashop 1.7.6.0 version on the same server with the module ps_facetedsearch 3.2.0 and everything works fine.

But if I upgrade an old shop from ps_facetedsearch 2.x.x to 3.2.0. I have the errors again. I don't know why? I also looked in the folder, all files are the same like on github. If I downgrade the module to 2.x.x again, all filteroptions works correctly again.

Maybe some other people have the same problem after upgrading?

**Comment by khouloudbelguith** [comment]
@itnomic, no, in my case, I tried with PS1.7.5.2, I make an upgrade of the module ps_facetedsearch from 2.x.x to 3.2.0 & it is OK.
https://drive.google.com/file/d/1PHJpyFfr-H5GebW9UqNQYWDIxxOeB14s/view
Thanks!

**Comment by zelduxs** [comment]
Hi i also have the same problem :(

**Comment by ghost** [comment]
Please change PHP version to 7.2 and check again...

**Comment by zelduxs** [comment]
Hi my PHP version: 7.2.14

2019-08-09, pn 16:55, Prestashark.eu <notifications@github.com> rašė:

**Comment by khouloudbelguith** [comment]
Hi @zelduxs, could you please try to click on these buttons from the page configuration of the ps_facetedsearch module
- Rebuild entire price index
- Build attributes and features indexes
- Clear cache
![image](https://user-images.githubusercontent.com/16067358/62792604-8ee2d780-bac7-11e9-83f5-95ab78abb27b.png)

Check & feedback.

**Comment by zelduxs** [comment]
I know, but it doesn't help, I've tried many times

**Comment by khouloudbelguith** [comment]
Hi all,

Your ticket is a duplicate of #15103
It is added to our bug roadmap.
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15103
