### ISSUE TITLE
Error in module "ps_categoryproducts"

### ISSUE THREAD

**Issue by manel-roman** [PrestaShop/PrestaShop#15310]
**Describe the bug**
After a product page in section "products in the same category" there is an error. 
Title and price only appears on the first item. The following products are shown without title, stars(reviews), price, etc.

The point is that it works perfectly if you deactivate Cache.

**To Reproduce**
1. Activate ps_categoryproducts module
2. Activate cache
3. Scroll down to 'products in the same category'

**Screenshots**

![Sin-título-1](https://user-images.githubusercontent.com/54669473/63937389-96f8bc00-ca62-11e9-9968-7f686f48c7d0.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.19

**Comment by khouloudbelguith** [comment]
Hi @manel-roman,

I did not manage to reproduce the issue with PS1.7.6.1 & the ps_categoryproducts module v1.0.4.
https://drive.google.com/file/d/1wPc5v94_Djpme7f1yLiQjStFCo0txlou/view
This issue is fixed with this PR: https://github.com/PrestaShop/ps_categoryproducts/pull/6
Your ticket is a duplicate of #9652
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9652

**Comment by zell9999** [comment]
> 
> 
> **Describe the bug**
> After a product page in section "products in the same category" there is an error.
> Title and price only appears on the first item. The following products are shown without title, stars(reviews), price, etc.
> 
> The point is that it works perfectly if you deactivate Cache.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Activate ps_categoryproducts module
> 
>     2. Activate cache
> 
>     3. Scroll down to 'products in the same category'
> 
>     4. See error
> 
> 
> **Screenshots**
> 
> ![Sin-título-1](https://user-images.githubusercontent.com/54669473/63937389-96f8bc00-ca62-11e9-9968-7f686f48c7d0.jpg)
> 
> **Additional information**
> PrestaShop version: 1.7.6.1
> PHP version: 7.2.19

I have the same problem. Many people have this problem, especially those who have prestashop in Spanish.
This error is still not fixed but @khouloudbelguith can not reproduce it....
I opened the same issue few months ago and it was closed too...
https://github.com/PrestaShop/PrestaShop/issues/14967

@khouloudbelguith, did you try using only the Spanish language (remove English) and only EURO in the currency

**Comment by HartLarsson** [comment]
I think is related to a non Classic default theme.
With Warehouse theme (also the latest 4.3.4 and latest modules ps_categoryproducts v 1.0.4 & ps_viewedproduct v1.2.1) the problem is the same if the Cache is enabled
