### ISSUE TITLE
CPU maximum - site slow - 1.7.6 prestashop performance

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15527]
Ever since I migrated from PS 1.6 to 1.7 I'm experiencing that the site time to time is extremely slow. Front office, but also Back office. For customers its impossible to order, and for us its impossible to work. 

We already upgraded the server for one with more RAM - ROM and more CPU. ( 8GB ram - 200 rom and 4 CPU ) Although this helpt the overal speed. 
Upgraded PS to the latest version and still CPU 100% used and back office very slow to a point unreachable. .

Under good circumstance BO will work good, but the order page always loads very slow. Extremely slow. Maybe this is because of the multistore feature. Indication loading time 30 sec to 1 minute. CPU high this can take up to 3-4 minutes

I don't know if its relevant, but I think that the CPU usage ( high ) is caused by crawlers. This is only  a guess. Is it possible that because of multistore, multiple domains are being crawled at the same time. In dashboard?

In dash board I see sometimes that over 1800 customers are online, but this I doubt. Thats why im thinking, maybe its a crawler ( but what do I know ) 

Also BO freezes when I re-build full search index and want to generate new thumbnails. 

PS: 1.7.6.1
PHP 7.2
Theme classic.

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks to follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

Thanks!

**Comment by 01park** [comment]
Hi @khouloudbelguith 

All these basic tweaks I already done. 

Nearly all stats I have disabled in modules. Just have best products, sales, data mining active.

**Comment by khouloudbelguith** [comment]
@01park, Could you please try to enable profiling mode
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks!

**Comment by 01park** [comment]
HI,

I will try this, but the problem is, is that the whole BO is not responding when the CPU is using 100%. 

And then after and X amount of hours ( probably a few hours from now ) everything will run smooth again and the CPU will go down.

For example why does the BO freeze when regenerate Thumbnails or reindex search. 

I checked error file, getting this

Stack trace:
#0 /home/xxxx/public_html/www.xxxxxxx.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'xxxe...', '}6%WqtF]j^^F', Array)
#1 /home/xxxxx/public_html/www.xxxxx.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(44): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'pxxx...', '}6%WqtF]j^^F', Array)
#2 /home/xxxxx/public_html/www.xxxx.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, '_fullflee...', '}6%WqtF]j^^F', Array)
#3 /home/xxxxx/public_html/www.xxxxxxxp.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect()
#4 /home/xxxxx/public_html/www.xxxxxx in /home/xxxxx1/public_html/wwwxxxxxxm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
[13-Sep-2019 11:40:15 Europe/Dublin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1040] Too many connections in public_html/www.----.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43


Screenshot from loading the order page


<img width="1669" alt="Screenshot 2019-09-13 at 16 20 16" src="https://user-images.githubusercontent.com/46492443/64874308-aa9b4980-d642-11e9-950f-48e203bb7758.png">

**Comment by khouloudbelguith** [comment]
@01park,
>[13-Sep-2019 11:40:15 Europe/Dublin] PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1040] Too many connections in public_html/www.

T﻿his is an issue that occurs on shared hosting. MySQL has a limit on how many concurrent connections it serves (151 by default, though usually set higher for shared db servers). If this number is reached, new c﻿onnection attempts return with the error you quoted. If you're on shared hosting, check with your hoster if other users are eating up connections.

Or Check your my.cnf file for "max_connections". If none exist try:

```
[mysqld]
set-variable=max_connections=250
```

Thanks!

**Comment by 01park** [comment]
Hi @khouloudbelguith 

Whe do I find this : [mysqld]
set-variable=max_connections=250

**Comment by khouloudbelguith** [comment]
@01park, in your file `my.cnf`.

Thanks!

**Comment by 01park** [comment]
and where is this located

**Comment by khouloudbelguith** [comment]
@01park, you can follow this link
https://stackoverflow.com/questions/2482234/how-do-i-find-the-mysql-my-cnf-location#targetText=There%20my.cnf%20file%20is,%2Flampp%2Fetc%2F%20folder.

It is on your server

Thanks!

**Comment by 01park** [comment]
@khouloudbelguith 

Thanks for your help. 

I can say that the BO loading time issue now is solved. I checked my database and discoverd that the the stats and ps_quest table had over 500.000.000 rows of data. I deciced to empty this together wit a few other data mining tables. After this, Back office is fast as lightning now. 

Problem 2. High CPU, I discovered after cleaning the stats. The amount of visits was increasing from 0 to 1000. within minutes. That couldnt be right. 
After some research I discovered the server was been heavily attacked by bad bots and ip-adresses.  After blocker over 200 of them. CPU is now back to 25% - 40%

**Comment by khouloudbelguith** [comment]
@01park, great!
Since it is fixed.
I close the issue.
Feel free to open a new one when needed.

Thanks!

**Comment by 01park** [comment]
Hi @khouloudbelguith 

This is a different topic, but I still have problems with the automatic index of products. 

- After saving a product, the index does not get updated
- After rebuilding entire index back office freezes until I get a 404 page.
- After using a cron job to rebuild entire index nothing happens

Also, when generating new thumbnails BO freezes until I get a 404 page.


The same happens with generating new thumbnails

**Comment by khouloudbelguith** [comment]
This issue is currently closed & it is different, can you open a new one with more information about your configuration.

Thanks!
