### ISSUE TITLE
[PHP Notice #8] Undefined index: id_image (classes/Product.php, line 6003)

### ISSUE THREAD

**Issue by ChMat** [PrestaShop/PrestaShop#15701]
**Describe the bug**
After updating a product and its combinations through the API (PUT requests all get http 200 success responses), a GET request on that same product returns a http 500 error response.

The error is a notice from Prestashop:

`[PHP Notice #8] Undefined index: id_image ([prestashop root]/classes/Product.php, line 6003)`

Debug mode is off on the Prestashop instance so I should not get those PHP notices.

The line that raises this notice is in the function below. None of the products and such have images so I don't get why an `id_image` array index is expected here. Why does this happen?

```php
    /**
     * Webservice getter : get virtual field id_default_image in category.
     *
     * @return int
     */
    public function getCoverWs()
    {
        $result = $this->getCover($this->id);

        return $result['id_image']; // this is line 6003
    }
```

**Additional information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.32

**Comment by khouloudbelguith** [comment]
Hi @ChMat,

I did not manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
I used this script
```
<html><head><title>Update Product</title></head><body>

<?php
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'http://prestashop.com/shop');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$url = 'http://prestashop.com/shop';

$ws = new PrestaShopWebservice(
                           $url,
                            'Key',
                            false);

$id =  1; //ID product Here

$timestamp_debut = microtime(true);
$xml = $ws->get(array('resource' => 'products', 'id' => $id));

//Unset readonly fields or buggy fields
unset($xml->product->position_in_category);
unset($xml->product->manufacturer_name);
unset($xml->product->associations->product_features); 
unset($xml->product->quantity);
unset($xml->product->associations->categories);
unset($xml->product->type);

$product = $xml->children()->children();
$product->price = 20;

$product->description->language[0][0] = "Description produit webservice";
$product->description_short->language[0][0] = "Short Description produit webservice";

$product->unit_price_ratio = 12;
	
$opt['putXml'] = $xml->asXML();                  
$opt['id'] = $id;
$opt['resource'] = 'products';
$xml = $ws->edit($opt);
echo "DONE";
```

Thanks to check & feedback.

**Comment by ChMat** [comment]
Hi @khouloudbelguith 

Thanks for the support.

My bad. In order to get more verbose error messages while developing, I just realise I had changed error reporting level to `E_ALL`.

However, there is an issue nonetheless with how `Product::getCoverWs()` works.

- the products I work with have 2 categories, none of which have images at the moment.
- Prestashop `Product::getCoverWs()` function expects the return value from `$this->getCover()` to be an array (see phpdoc) and the `id_image` key to exist in the array. But when the categories don't have an image, the return value from `$this->getCover()` is in fact a boolean false.

Line 6003 in `Classes/Product.php` should be changed:

```php
// From
return $result['id_image'];
// To this
return (false !== $result && array_key_exists('id_image', $result)) ? $result['id_image'] : null;
```
I did not delve in how to contribute to this project, so I'll just leave this here if you need it.

Thanks anyway, this helped me solve my problem.

**Comment by khouloudbelguith** [comment]
@ChMat, thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by Perfecticus** [comment]
Hi, why was this marked as "No change required"?, @ChMat stated that a change was needed to eradicate the warning that occurs when the cover image result does not have a 'id_image' index.

I experienced this bug using 1.7.1.6 webservice in production with default error reporting.
In my case:
`<message><![CDATA[[PHP Notice #8] Undefined index: id_image (/var/www/html/XXXXXX/classes/Product.php, line 6081)]]></message>`

**Comment by Gronghon** [comment]
Version 1.7.7.5, the notice is still present... 2021...
Debug mode : off

We can't proceed to make a GET request if it doesn't have any image.

/api/products/593

`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[5]]>
            </code>
            `<message>`
                <![CDATA[[PHP Notice #8] Undefined index: id_image (/xxx/classes/Product.php, line 6262)]]>
            </message>
        </error>
    </errors>
</prestashop>`
