### ISSUE TITLE
Call to private method when trying to update shop language or e-mails themes

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#16017]
**Describe the bug**

I tried to update a language setting (French) from BO: International > translations > Add / Update a language and click button. It returned me:

```
Call to private Pelago\Emogrifier\HtmlProcessor\AbstractHtmlProcessor::__construct() from context 'PrestaShop\PrestaShop\Core\MailTemplate\Transformation\CSSInlineTransformation'

Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to private Pelago\Emogrifier\HtmlProcessor\AbstractHtmlProcessor::__construct() from context 'PrestaShop\PrestaShop\Core\MailTemplate\Transformation\CSSInlineTransformation'" at /var/www/c-piscine/html/src/Core/MailTemplate/Transformation/CSSInlineTransformation.php line 70
```

**Screenshots**
![bug-language-update](https://user-images.githubusercontent.com/7419525/67084750-df4c7480-f19d-11e9-8a86-9b5b808ecbab.png)

![bug-language-update2](https://user-images.githubusercontent.com/7419525/67085133-8fba7880-f19e-11e9-9397-823f8b28f9b9.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.1.
What is the exact version of the ps_emailsubscription module did you use?

Thanks!

**Comment by Klemart3D** [comment]
Hi @khouloudbelguith,

Thanks for tour answer.

Module ps_emailsubscription:

**Inscription à la newsletter**
**v2.5.1** - par PrestaShop 

And when I'm trying to Configure this module I have the following:
```
Notice à la ligne 74 du fichier /var/www/prestashop/html/src/Adapter/Routing/LegacyHelperLinkBuilder.php
[8] Undefined index: id_merged
```

![Capture d’écran de 2019-10-18 12-12-18](https://user-images.githubusercontent.com/7419525/67086274-ac57b000-f1a0-11e9-915e-ef52a17b11f0.png)

**Comment by khouloudbelguith** [comment]
@Klemart3D, this is adifferent issue.
It is fixed in the new patch PS1.7.6.2 with this PR: https://github.com/PrestaShop/PrestaShop/pull/15382 as reported here: https://github.com/PrestaShop/PrestaShop/issues/15318
In your exception, you have an error with the module ps_emailsubscription
![image](https://user-images.githubusercontent.com/16067358/67086560-53d4e280-f1a1-11e9-8c22-eb4fa2a2a10f.png)

Could you please try to reset it & try to re-upload the Pack France from the BO => International => Localization Page.

Thanks!

**Comment by Klemart3D** [comment]
Still the same by resetting module:
![bug-traduction](https://user-images.githubusercontent.com/7419525/67093018-f779bf00-f1b0-11e9-89df-72b4a3371c2f.gif)

Error is on "newsletter_conf" email template so I tried to change mailing template from "modern" to "classic" but error is the same.

I reproduced the same error from screen ("Call to private...") by generating emails, from "Email theme" tab:
modern + French + Core + Erase to Yes : KO
modern + French + Core + Erase to No : KO

modern + English + Core + Erase to No : OK!
modern + English + Core + Erase to Yes : KO

classic + French + Core + Erase to No : KO
classic + English + Core + Erase to No : OK!

**Comment by khouloudbelguith** [comment]
@Klemart3D, could you please try to re-upload the Pack France from the BO => International => Localization Page.
![image](https://user-images.githubusercontent.com/16067358/67094244-b505b180-f1b3-11e9-9a3e-e60dd89e23ee.png)

Thanks!

**Comment by Klemart3D** [comment]
Done. But not better :/

![bug2](https://user-images.githubusercontent.com/7419525/67094669-8e944600-f1b4-11e9-90da-5b2b86d91efb.gif)

**Comment by khouloudbelguith** [comment]
@Klemart3D, this is a fresh install PS1.7.6.1 pr an upgrade from a previous version?
What is the exact language/country did you used during the install?

Thanks!

**Comment by Klemart3D** [comment]
@khouloudbelguith 
It was a fresh install of PS 1.7.5.2 with French + English + Deutsch + Russian languages.
And I upgraded from PS 1.7.5.2 to 1.7.6.1 past week with 1-Click Upgrade (you can find log in [ticket 15910](https://github.com/PrestaShop/PrestaShop/issues/15910#issuecomment-541060842)).
And I removed Russian language yesterday.

**Comment by khouloudbelguith** [comment]
@Klemart3D, Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by Klemart3D** [comment]
![Screenshot_2019-10-18 PHP PrestaShop Info](https://user-images.githubusercontent.com/7419525/67097327-29435380-f1ba-11e9-90a6-0b78477dccaf.png)

**Comment by khouloudbelguith** [comment]
@Klemart3D, could you please check if the `pelago/emogrifier` in your composer.lock file
https://github.com/PrestaShop/PrestaShop/blob/1.7.6.1/composer.lock#L2967

Thanks!

**Comment by Klemart3D** [comment]
Nice shot @khouloudbelguith!!

I was with `pelago/emogrifier` v2.2.0:
![emogrifer](https://user-images.githubusercontent.com/7419525/67100589-3e22e580-f1c0-11e9-9324-d38705502a72.png)

So I re-upload the official `composer.lock` of PS 1.7.6.1, launch a `composer install` and see:
```
- Downgrading pelago/emogrifier (v2.2.0 => v2.1.1): Loading from cache
```
Now everything (updating shop language or regenerating email templates) is working!

Thank you very much ;)

You can close this ticket.

**Comment by khouloudbelguith** [comment]
@Klemart3D, you are welcome!
Since it is fixed, I close the issue, feel free to open a new one when needed.

Thanks!
