### ISSUE TITLE
Faceted Search Module 3.4.0 Lose Order of Categories

### ISSUE THREAD

**Issue by agalussio** [PrestaShop/PrestaShop#16130]
**Describe the bug**
When I activate the ps_facetedsearch module the order of the products within the categories fails. If I disable it, it is sorted correctly.

**To Reproduce**
1. When I activate the ps_facetedsearch Module
2. I lose the order of the categories you had

I've got it set up:
Product Setting - Default Order by = "Position Inside Category"

https://www.tiendahippie.es/catalogo/order-faceted.mp4

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: 7.2
ps_facetedsearch 3.4.1

**Comment by khouloudbelguith** [comment]
Hi @agalussio,

This issue is fixed in the develop branch.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14879 to fix the issue.
I attached a screen record
https://drive.google.com/file/d/1jmR8364Ew4uiPs6v_lTpkCNV2NyKadyM/view
It is fixed in the next version PS1.7.7.0.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/14616

**Comment by agalussio** [comment]
@khouloudbelguith  no, it's not similar to the: #17400 
As you see in the video I sent, the problem is when the facet search module is active.

**Comment by khouloudbelguith** [comment]
@agalussio, I just re-opened the issue.
Waiting for your feedback.

**Comment by agalussio** [comment]
Thanks @khouloudbelguith 
I don't know why the mistake would occur. I read a lot of topics on category positions and faceted search but I couldn't figure it out.
The order in the BO works fine and if I change the position of the products it works too.
The problem is if I activate the faceted search and it is solved when I deactivate it.

I hope someone can help me

**Comment by khouloudbelguith** [comment]
@agalussio, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.3 and the ps_facetedsearch module v3.4.1.
I attached a screen record
https://drive.google.com/file/d/1cQjMHMS7gb1E1JOLQDBJb_3i68kAEOCk/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- javascript console log

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by agalussio** [comment]
PHP configuration: https://mayorista-ropa.es/info.php

I checked and there are no mistakes. But I also asked my hosting provider to analyze it for me and he sees no errors either.

No errors in the logs apache,Php, debug mode either.
Also not in javascript console log

I have a development server that has the same problem. If there's a private way I can give you access to see it.

**Comment by khouloudbelguith** [comment]
@agalussio, sorry, but we must first try to reproduce your issue.
Did you use a custom theme? your module is it overriten by your theme?

tHANKS!

**Comment by agalussio** [comment]
It happens in the classic theme, panda and alysum

**Comment by agalussio** [comment]
No override on modules

**Comment by khouloudbelguith** [comment]
@agalussio, could you please try to re-install the `ps_facetedsearch` module with removing the folder, clear cache, check and feedback.

Thanks!

**Comment by agalussio** [comment]
I just uninstalled the module, deleted the ps_facetedsearch folder and reinstalled the module (removing cache - although not in development)
And the same problem remains.

**Comment by khouloudbelguith** [comment]
@agalussio, thanks to check the sorting when `ps_facetedsearch` is enabled:
1. The products are sorted in another order or they are just displayed randomly
2. If they are sorted in another order, which this order (Product name, Product price, ..)
3. What is the exact order method used "Ascending" or "Descending"

For example, your products are sorted "Position inside category" but the default order method is "Ascending"?

Thanks!

**Comment by agalussio** [comment]
@khouloudbelguith 

1. They are shown at random
2. Just sort it out alphabetically. A to Z - and Z to A.
By price he also orders it wrong. 
3. Order products by: Position within the category 
Default sort method: Ascending

For example, your products are sorted "Position inside category" but the default order method is "Ascending"?
YES

**Comment by khouloudbelguith** [comment]
@agalussio, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Also, you can check manually if this class: https://github.com/PrestaShop/ps_facetedsearch/blob/master/src/Product/SearchProvider.php is not overridden.

Thanks!

**Comment by agalussio** [comment]
@khouloudbelguith 
In debug mode there are no errors. And in the php log there are no errors either. Attached is the log
https://dev.tiendahippie.es/catalogo/dev.log
https://dev.tiendahippie.es/catalogo/error_log.txt

check the overridde classes and there are none from SearchProvider.php

**Comment by khouloudbelguith** [comment]
>[12-Feb-2020 09:25:19 UTC] PHP Fatal error:  require(): Failed opening required '/home/mayoristaropa/public_html/dev/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='/home/mayoristaropa/public_html/dev/vendor/pear/pear_exception:/home/mayoristaropa/public_html/dev/vendor/pear/console_getopt:/home/mayoristaropa/public_html/dev/vendor/pear/pear-core-minimal/src:/home/mayoristaropa/public_html/dev/vendor/pear/archive_tar:.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/mayoristaropa/public_html/dev/vendor/composer/autoload_real.php on line 61

It is a cache issue, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).

>[21-Feb-2020 07:21:26 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/mayoristaropa/public_html/dev/classes/controller/Controller.php:772
Stack trace:
#0 /home/mayoristaropa/public_html/dev/classes/controller/FrontController.php(533): ControllerCore->get('prestashop.core...')
#1 /home/mayoristaropa/public_html/dev/classes/controller/FrontController.php(517): FrontControllerCore->buildFrontEndObject(Array)
#2 /home/mayoristaropa/public_html/dev/classes/controller/FrontController.php(548): FrontControllerCore->assignGeneralPurposeVariables()
#3 /home/mayoristaropa/public_html/dev/override/classes/controller/FrontController.php(23): FrontControllerCore->initContent()
#4 /home/mayoristaropa/public_html/dev/classes/controller/ModuleFrontController.php(77): FrontController->initContent()

You have an override of the `FrontController.php` class, it could be the problem.

Thanks to check & feedback.

**Comment by agalussio** [comment]
@khouloudbelguith

Thank you for your answer. I saw the override but it doesn't affect it. I still removed (/home/mayoristaropa/public_html/dev/classes/controller/FrontController.php) it and deleted the cache (also the /var folder)

But it's still the same mistake.

**Comment by khouloudbelguith** [comment]
@agalussio, could you please provide me the new dev log after deleting the cache and removing the override.

Thanks!

**Comment by agalussio** [comment]
@khouloudbelguith 
I already updated the files with the ones on the server now

https://dev.tiendahippie.es/catalogo/dev.log
https://dev.tiendahippie.es/catalogo/error_log.txt

**Comment by khouloudbelguith** [comment]
@agalussio,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by marlon8511** [comment]
> @khouloudbelguith
> I already updated the files with the ones on the server now
> 
> https://dev.tiendahippie.es/catalogo/dev.log
> https://dev.tiendahippie.es/catalogo/error_log.txt

Hello I have the same issue, could you fix it??

**Comment by marlon8511** [comment]
Hello @agalussio, I have the same issue. Could you fix it?

**Comment by agalussio** [comment]
Hi, I haven't been able to fix it and they've already tried 3 developers.
Prestashop is very disappointing.

**Comment by marlon8511** [comment]
@agalussio 
Hello I fixed the problem using this:

 "/modules/ps_facetedsearch/src/Adapter/MySQL.php" 

in "getFieldMapping" method:
...
'position' => [
                'tableName' => 'category_product',
                'tableAlias' => 'cp',
                **'fieldName' => 'position',  // <- ADD THIS**
                'joinCondition' => '(p.id_product = cp.id_product)',
                'joinType' => self::INNER_JOIN,
            ],
I found this solution here #15062 by @Mindfield-Studio

**Comment by agalussio** [comment]
@marlon8511  Thank you for the input, but I don't think I can fix it. I still have the mistake...

**Comment by tardinim** [comment]
@marlon8511 your solution work fine for me on my local machine but no on the webserver.
I think I've find the problem, for example this is the query string:

```
SELECT p.id_product 
FROM   (SELECT p.id_product, 
               p.id_manufacturer, 
               Sum(sa.quantity) AS quantity, 
               p.CONDITION, 
               p.weight, 
               p.price, 
               cp.position 
        FROM   ptt_product p 
               LEFT JOIN ptt_product_attribute pa 
                      ON ( p.id_product = pa.id_product ) 
               LEFT JOIN ptt_product_attribute_combination pac 
                      ON ( pa.id_product_attribute = pac.id_product_attribute ) 
               LEFT JOIN ptt_stock_available sa 
                      ON ( p.id_product = sa.id_product 
                           AND Ifnull(pac.id_product_attribute, 0) = 
                               sa.id_product_attribute 
                           AND sa.id_shop = 1 
                           AND sa.id_shop_group = 0 ) 
               INNER JOIN ptt_category_product cp 
                       ON ( p.id_product = cp.id_product ) 
               INNER JOIN ptt_category c 
                       ON ( cp.id_category = c.id_category 
                            AND c.active = 1 ) 
               INNER JOIN ptt_product_shop ps 
                       ON ( p.id_product = ps.id_product 
                            AND ps.id_shop = 1 
                            AND ps.active = true ) 
        WHERE  p.visibility IN ( 'both', 'catalog' ) 
               AND c.nleft >= 4 
               AND c.nright <= 17 
               AND ps.id_shop = '1' 
        GROUP  BY p.id_product) p 
       INNER JOIN ptt_category_product cp 
               ON ( p.id_product = cp.id_product ) 
GROUP  BY p.id_product 
ORDER  BY cp.position ASC 
LIMIT  0, 20 

```
The subquery work well but the last group by
`GROUP BY p.id_product ORDER BY cp.position ASC`
is interpred in different ways on my local machine and my webserver

**Comment by arirangz** [comment]
Hello,

I still have the issue with laster Prestashop and search Module. I had to disable the module to get the right order.

Is there any progress on this issue?

Thanks

**Comment by ghost** [comment]
Thank you @marlon8511 this fixes the issue !
Is there a way to override in a clean way the `/modules/ps_facetedsearch/src/Adapter/MySQL.php` file or can we only fix it in the core module file ?

**Comment by arirangz** [comment]
Hello @khouloudbelguith 

As I mentioned in my previous comment, the issue is not fixed.

Could you please have a look?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by piotrmerton** [comment]
I just encountered this exact issue on PrestaShop 8.1.5 and ps_facetedsearch 3.5.11. Uninstalling ps_facetedsearch (or disabling "Show products from podcategories" in module settings) fixes sort order but obivously it's not the optimal solution. 

It also works perfectly fine on localhost (MySQL), but not on webserver (MariaDB). So maybe it is down to MariaDB differently interpreting ORDER BY?
