### ISSUE TITLE
Improve feature creation in product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16306]
#### Describe the bug

> Edited by @HanaRebaiQA 

There are two cases in product page : 

**Product V1 page** : There is no possibility to delete a feature when we put `Choose a value` and `Choose a feature`. The features are duplicated after save and when we put a customized value for it.

Here is a screen-record : 8.0.x with product V1 page

https://user-images.githubusercontent.com/92912932/177517930-35644b44-8d22-43f1-8c9e-83ed0550d8cc.mp4

**Product V2 page** : An exception is thrown when we put `choose a value` and `choose a feature ` 

Here is a screen-record : 8.0.x with product V2 page

https://user-images.githubusercontent.com/92912932/177517938-e58de612-24d2-4aeb-8da9-f3ba98340fee.mp4

>  //*************************The original Description************************//

If you create a feature in a product page "Add a new feature" and give it a custom value, **but without selecting an existing feature** then it is impossible to delete it after

In addition to no being able to delete it, it seems to impact existing and fine features by applying the custom value of the created feature to all the features' values.

#### Expected behavior
When you add a feature, you have a drop-down with all features. 

If you have not yet selected a feature, the “pre-defined value” drop-down is disabled and the “customized value” field should be also disabled (currently it’s not).

![capture d'écran_2129](https://user-images.githubusercontent.com/13449658/68379424-17682700-014e-11ea-90cc-620af369b4a2.png)

If you select a pre-defined value, the customized value should be disabled because a feature can’t have both.

![capture d'écran_2130](https://user-images.githubusercontent.com/13449658/68379520-4b434c80-014e-11ea-883a-a26d398b9713.png)

If you start enter a customized value, the pre-defined value drop-down should be disabled because a feature can’t have both.

![capture d'écran_2131](https://user-images.githubusercontent.com/13449658/68379592-7463dd00-014e-11ea-9f58-b11ea7f65124.png)

#### Steps to Reproduce

1. Go to 'Catalog > products > select any product'
2. In the product page, on the first tab, click on 'Add a feature'
3. For "Feature" and "Pre-defined value", select "Choose a feature" and add a custom value
4. Save
5. go to another page and come back to the product page
6. See the feature you created, delete it and save
7. Go to another page and come back, the feature still exist.

**Screenshots**

See the video:
https://drive.google.com/file/d/1nZPWLhODwa9FQlvmK2aHRDWNPVEy8O1W/view

#### Additional informations
PrestaShop version: 1.7.7.0
PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

Well, the 3 use cases that you asked for as an improvement, they are not yet fixed/applied with PS1.7.7.0.
And for the bug, following your steps to reproduce the issue, I managed to reproduce it with PS1.7.7.0.

Thanks!

**Comment by hattia** [comment]
Hello,

is this bug is resolved please ? cause in last PS version 1.7.7.7 , this bug still exist.

Thanks

**Comment by alfonsolr09** [comment]
No solution yet??

**Comment by nauumb** [comment]
Hello! I would like to work on this problem @hattia  @hibatallahAouadni . It's my first time so I'll follow https://github.com/PrestaShop/PrestaShop/blob/5d61aa8679978d9c3e767e0d7864358a6c896f08/CONTRIBUTING.md to collaborate, but any smells of where we can start from?  

I would like to be able to talk to you before I start coding. 

Thanks you,

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone please help @nauumb to create his first PR :rocket:

**Comment by mcosta-dada** [comment]
It is unfortunate that this error has not yet been resolved, I found a first report from November 2018.

At least they could give a js solution at least to be able to move forward and not have to delete the product and create another one again.

Thank you

**Comment by alfonsolr09** [comment]
> It is unfortunate that this error has not yet been resolved, I found a first report from November 2018.
> 
> At least they could give a js solution at least to be able to move forward and not have to delete the product and create another one again.
> 
> Thank you

my solution was to go into the database and remove all the features
This I did is not a solution.
I understand that it is an open source project, but does PrestaShop have hired employees?

**Comment by matks** [comment]
> I understand that it is an open source project, but does PrestaShop have hired employees?

The PrestaShop company have employees that work on this project but they are not 'in charge'. They contribute to topics they consider interesting for their usage.

This is how an open source project works: the community of users use the project for their own benefits, and submit contributions that match their needs and can be useful for other people as well.

In other words, this bug will remain unsolved until someone considers that it has a ROI high enough to invest resources to explore this bug and fix it. It can be a merchant, it can be a web agency, it can be PrestaShop company or even Microsoft. Someone will consider this bug is important for him/her and invest to fix it.

If PrestaShop company considers this bug is important, that this bug is very frustrating for its users, it is likely that PrestaShop company will assign a developer of the company to work on it. If it has not happened yet, this is because PrestaShop company - and other companies - did not consider this bug is important enough.

>  did not consider this bug is important enough.
Which does not mean this bug is not important, it means _there are other topics more important_ 😉  that is a big difference. If topic B is more important than topic C, it does not mean topic C is a trivial topic. It means topic B has a highest ROI than topic C.

**Comment by AlloryDante** [comment]
This happens to me everytime, what can I do?

**Comment by alfonsolr09** [comment]
The PrestaShop team does not care about this serious error, it seems that you cannot do anything. 
"If you want a solution you can find it on your own since it is an open source project"
I am in the same case as you, friend ... I find it regrettable

**Comment by alfonsolr09** [comment]
@marionf thats not a improvement, thats a bug!!

**Comment by hattia** [comment]
Agree with @alfonsolr09 this is a bug and a really annoying bug

**Comment by matks** [comment]
If you find that this issue is critical for you, and it's important to have it fixed quick, then you can _invest_ into having it done.

You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. I'm sure there is great developers you can hire for a bugfix mission ;) .

The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by alfonsolr09** [comment]
What do you think about disabling the custom value box while you haven't selected a feature?
I could create the PR

**Comment by nauumb** [comment]
It seems like I not should be persisted in the database before data verification. @alfonsolr09 Wouldn't a robust model be a better solution in this case?

There is some SQL querys that you can run gainst your database.

`DELETE FROM ps_feature_value_lang WHERE id_feature_value IN (SELECT id_feature_value FROM ps_feature_value WHERE id_feature=0);`
`DELETE FROM ps_feature_product WHERE id_feature=0;`
`DELETE FROM ps_feature_value WHERE id_feature=0;`

These queries will fix data inconsistency. ¡Warning! ⚠️  Test these changes first in a development environment before making them in production.

**Comment by alfonsolr09** [comment]
> It seems like I not should be persisted in the database before data verification. @alfonsolr09 Wouldn't a robust model be a better solution in this case?
> 
> There is some SQL querys that you can run gainst your database.
> 
> `DELETE FROM ps_feature_value_lang WHERE id_feature_value IN (SELECT id_feature_value FROM ps_feature_value WHERE id_feature=0);`
> `DELETE FROM ps_feature_product WHERE id_feature=0;`
> `DELETE FROM ps_feature_value WHERE id_feature=0;`
> 
> These queries will fix data inconsistency. ¡Warning! ⚠️  Test these changes first in a development environment before making them in production.
> 
> 

what's your proposal?  I don't really understand what you want to say to me :(

**Comment by alfonsolr09** [comment]
can we merge this into 1.7.8.x?

**Comment by hibatallahAouadni** [comment]
> can we merge this into 1.7.8.x?

Ping @PrestaShop/product-team wdyt?

**Comment by marionf** [comment]
@alfonsolr09 No, only regressions are fixed in patch versions

**Comment by Bilalk56** [comment]
Hi, this problem still persists in 1.7.8.3 or reappears, with the same procedure to reproduce it as described in this ticket.

**Comment by Bilalk56** [comment]
Hi, this problem still persists in 1.7.8.3 with the same procedure to reproduce it as described in this ticket.

**Comment by mcosta-dada** [comment]
> 

Looks like someone is fixing it.

https://github.com/PrestaShop/PrestaShop/pull/27097

If someone in the thread is able to help here is the repository:
https://github.com/atomiix/PrestaShop/commit/ff3adb374f6f7129802849d4f993ac981e930f6c

**Comment by Bilalk56** [comment]
My bad. issue #9680 was matches has duplicate by this one. But although that concerns the same location, but not the same problem, which is "Duplication of feature line in product page". I'm reviving the topic from the original ticket...

**Comment by MatShir** [comment]
It seems to be fixed in the new product page @hibatallahAouadni. Could you double-check ? ;)

**Comment by hibatallahAouadni** [comment]
Ping @MatShir indeed it's fixed on the new experimental product page on `develop` :tada: 

https://user-images.githubusercontent.com/23308427/154951530-daae4364-27aa-444f-ac21-04fcb5fc899c.mp4

Closing the issue!

**Comment by alfonsolr09** [comment]
> Parece estar arreglado en la página del nuevo producto @hibatallahAouadni . ¿Podrías verificar dos veces? ;)

when will the old product page be removed? maybe we should fix the problem on the current page until the new one is launched?

**Comment by hibatallahAouadni** [comment]
> when will the old product page be removed? maybe we should fix the problem on the current page until the new one is launched?

@alfonsolr09 It will be removed on the next major patch 8.0.0 :wink:

**Comment by alfonsolr09** [comment]
that is, in less than 1 year probably right?

**Comment by alfonsolr09** [comment]
that is, in less than 1 year probably right?

**Comment by MatShir** [comment]
Hopefully this summer, you can follow the updates of the v 8.0.0 in this issue https://github.com/PrestaShop/PrestaShop/issues/26427 :)

**Comment by serracol** [comment]
> It seems like I not should be persisted in the database before data verification. @alfonsolr09 Wouldn't a robust model be a better solution in this case?
> 
> There is some SQL querys that you can run gainst your database.
> 
> `DELETE FROM ps_feature_value_lang WHERE id_feature_value IN (SELECT id_feature_value FROM ps_feature_value WHERE id_feature=0);` `DELETE FROM ps_feature_product WHERE id_feature=0;` `DELETE FROM ps_feature_value WHERE id_feature=0;`
> 
> These queries will fix data inconsistency. ¡Warning! ⚠️ Test these changes first in a development environment before making them in production.

Thanks a lot to @nauumb for sharing this fix. This will remove all those duplicated entries...

**Comment by HanaRebaiQA** [comment]
Hello,

I was able to reproduce the issue in product page on 8.0.x.

There are two cases in product page : 

**Product V1 page** : There is no possibility to delete a feature when we put `Choose a value` and `Choose a feature`. The features are duplicated after save and when we put a customized value for it.

Here is a screen-record : 8.0.x with product V1 page

https://user-images.githubusercontent.com/92912932/177517930-35644b44-8d22-43f1-8c9e-83ed0550d8cc.mp4


**Product V2 page** : An exception is thrown when we put `choose a value` and `choose a feature ` 

Here is a screen-record : 8.0.x with product V2 page

https://user-images.githubusercontent.com/92912932/177517938-e58de612-24d2-4aeb-8da9-f3ba98340fee.mp4


@MatShir : I updated the description of the issue and have removed the `Fixed` label. 
I think it should be updated to a `Bug` label and not `Feature`. What do yout tink ?
Also, i put the two different cases of product V1 and product V2 here in the same issue. It's Ok or i should create a dedicated issue for product V2 ? What do you think ?


Thank you!

**Comment by alfonsolr09** [comment]
From what I understand, the "old" product creation page will not be deleted in version 8.0, so could someone implement this bug fix?

https://github.com/PrestaShop/PrestaShop/pull/26782

**Comment by FabienPapet** [comment]
Hello @alfonsolr09, I could not have a look on your PR because it is empty. Can you please update it ?

Thank you

**Comment by alfonsolr09** [comment]
I created it, but @atomiix moved it from site or something similar. I do not understand very well how to solve it since I am not an expert in GitHub

**Comment by alfonsolr09** [comment]
I created it, but @atomiix moved it from site or something similar. I do not understand very well how to solve it since I am not an expert in GitHub

**Comment by MatShir** [comment]
Seems to be fixed on 8.1 :)
We won't be able to back port this fix to anterior versions, the changes are too major

**Comment by djoelleuch** [comment]
Hello @MatShir , 
The issue is fixed on 8.1 as you can see below : 

[issue16306.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/ee5bc99e-3fe2-4e7c-9f40-9fd268b38df4)

I will close the issue , Thank you .
