### ISSUE TITLE
[Bug][Performance] Guest checkout validates all the guest addresses (thousands)

### ISSUE THREAD

**Issue by dkarlovi** [PrestaShop/PrestaShop#16584]
**Describe the bug**
If you have a lot of guest checkouts, you'll have a lot of guest addresses (`ps_address.id_customer = 0`).

This causes a problem since, currently, the [checkout process validates all the customer's addresses](https://github.com/PrestaShop/PrestaShop/blob/a51084f29cb87627ad57fde9d7932057c225b4e1/controllers/front/OrderController.php#L230-L233). In the case you're a guest, that means **all guest addresses** are validated.

If you have a lot (thousands or tens of thousands) of guest checkouts, all the addresses are being validated at any guest checkout, making it ever more slower.

**To Reproduce**
1. Create 10k guest fake customer addresses, `ps_address.id_customer = 0`
2. Try to do a new guest checkout
4. Observe seconds of delay in the `POST /order` request

**Additional information**
PrestaShop version: latest, linked
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @dkarlovi,

The issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/8904
As reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9690
Thanks to check & feedback.

**Comment by dkarlovi** [comment]
Don't think it's fixed currently since we're seeing the described behavior, is it s regression?

**Comment by khouloudbelguith** [comment]
@dkarlovi, Could you please try to enable profiling mode
In your Projetc_Folder/config/defines.inc.php, you need to replace this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', flase);
}
```

by this

```
if (!defined('_PS_DEBUG_PROFILING_')) {
    define('_PS_DEBUG_PROFILING_', true);
}
```
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks to provide me a screenshot.
In your BO => Adnaced Parameters => Information page=> thanks to provide me all informations.

**Comment by matks** [comment]
It might be an unexpected side-effects of wanting to valide all customer addresses at checkout, but it has unwanted behavior for guests.

I guess a simple solution would be not to perform the validation for guests ?

**Comment by dkarlovi** [comment]
@khouloudbelguith this is not easy to screenshot since it's a redirect request (done as `GET /order`) when you click Checkout on the cart.

I'll attach the screenshot of my Blackfire.io profile:
![Prestashop checkout profile - Blackfire](https://user-images.githubusercontent.com/209225/69808141-30ad4200-11e7-11ea-92d9-8f0b76858020.png)

Note the number of addresses validated.

If I run 
```sql
SELECT count(*) FROM ps_address where id_customer = 0;
```

I get the same number, hinting the massive slowdown we're seeing is caused by the linked code. Removing this code fixes the issue and speeds up the execution time of this request by 97% in our case: https://twitter.com/dkarlovi/status/1199704905583333376

**Comment by dkarlovi** [comment]
@matks 

> I guess a simple solution would be not to perform the validation for guests ?

Agreed, that's exactly what we did.

**Comment by slri** [comment]
Just want to chime in on the issue since I've been working with @dkarlovi on it.
Our solution is exactly what @matks and @dkarlovi suggested, and I was forced to do it like this (in an OrderController override):
```php
        if($customer->id) {
            $allInvalidAddressIds = $addressValidator->validateCustomerAddresses($customer, $this->context->language);
            $this->checkoutWarning['invalid_addresses'] = $allInvalidAddressIds;
        }
```

Reasoning for this is that `$customer->isGuest()` is in our case rendered useless due to our `$customer` having `id_guest` set to `false`. Reasoning for this is, to me, unknown and the functionality hasn't been altered.
Version the isGuest issue is tested on is 1.7.4.4.

**Comment by khouloudbelguith** [comment]
@dkarlovi, @slri, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2.
I used this script to create a lot of addresses
```
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 28/11/19
 * Time: 14:44
 */
ini_set('display_errors','on');

define('DEBUG', true); // Debug mode
define('PS_SHOP_PATH', 'http://shop.com'); // Root path of your PrestaShop store
define('PS_WS_AUTH_KEY', 'Key'); // Auth key (Get it in your Back Office)
require_once('./PSWebServiceLibrary.php');
$psXML = <<<XML
<prestashop>
<address>
  <id/>
  <id_customer>0</id_customer>
  <lastname>lastname</lastname>
  <firstname>firstname</firstname>
  <address1>address</address1>
  <id_manufacturer>0</id_manufacturer>
  <alias>boom</alias>
  <postcode>33133</postcode>
  <price>100</price>
  <city>Paris</city>
  <id_country>8</id_country>
</address>
</prestashop>
XML;
$webService = new PrestaShopWebservice(PS_SHOP_PATH, PS_WS_AUTH_KEY, DEBUG);
$xml = new SimpleXMLElement($psXML);
var_dump($xml->asXML());
$opt = array( 'resource' => 'addresses' );
$opt['postXml'] = $xml->asXML();
//$opt['id_shop'] = 'all';
for ($i = 1; $i <= 10000; $i++) {
    $xml = $webService->add( $opt );
}
$xml = $webService->add( $opt );
```
When profiling mode is enabled, In the checkout page, I have 37479 queries
![image](https://user-images.githubusercontent.com/16067358/69815869-8853a980-11f7-11ea-9619-ca49f3da0c7f.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by lutek** [comment]
my quick patch #14881
