### ISSUE TITLE
Shop Context in Admin Panel is wrong on Multistore shop

### ISSUE THREAD

**Issue by IvoRabush** [PrestaShop/PrestaShop#16702]
**Describe the bug**
When the multistore is active, the Shop Context in the admin panel is wrong. It always returns the shop from the main domain.

**To Reproduce**
1. Activate the multistore future
2. Set the 1st store domain to example.com
3. Set the 2nd (and every next store) the domain example.com and Virtual URL 'VU/'
**example:** 2nd store is for Bulgaria, so I set the Virtual URL to 'bg/'
![image](https://user-images.githubusercontent.com/32366618/70230170-71b1d300-1760-11ea-8232-f5395a901c7d.png)

In the admin panel, doesn't matter on which context your are (all shops, shop 1, shop 2, ...) the **Context Object** (Context::getContext->shop->id or $this->context->shop->id) or the **Shop object** (Shop::getContextShopID(true)) will always return the shop ID from the main domain, the domain **without the Vistual URL**

**Consequences**
1. This has many bad consequences on **all the SQL queries with shop restriction** that are called from the admin panel.
2. My other worry is the time zones, it allways takes the same timezone and the create/update dates are always from 1 timezone, but when  customer makes an order, the context is correct from the frontend and the timezones and also corret.
In my case the order is made in the BG store and takes the time zone Europe/Sofia, but when modifiying the order, it takes the time zone from the shop of the main domain. It appears that the order history changes are made before the order itself is created!!
![image](https://user-images.githubusercontent.com/32366618/70233190-b93b5d80-1766-11ea-9c28-cbbada304d1a.png)

**Comment by khouloudbelguith** [comment]
Hi @IvoRabush,

The "Admin URL issue" is fixed with this PR: #9450 as described in this [ticket](http://forge.prestashop.com/browse/BOOM-3607.
Thanks to check & feedback.

**Comment by IvoRabush** [comment]
Prestashop Version 1.7.5
I'm not calling the method getAdminBaseLink.

I'm changing the shop context and when I call the methods Context::GetContext()->shop->id in order to get the currect shop context. Doesn't matter on which Shop context I am, it gives the shop from the current URL  - this is wrong !

![image](https://user-images.githubusercontent.com/32366618/70303734-04a64800-1809-11ea-893c-ee8f16c84970.png)

The problem is here: /classes/shop/Shop.php
Method: initialize()
![image](https://user-images.githubusercontent.com/32366618/70301610-87c49f80-1803-11ea-9a0f-0e7a03ffddca.png)

from this **preg_match** it give always the shop from the base URL.
1. If the link to the admin panel is example.com/adminXXXXXXX it will always return the shop where there is not setting for virtual URL
2. if the link to the admin panel is example.com/**bg**/adminXXXXXXX it will always return the shop where the virtual URL is **bg**

Now the issue is, when I switch the shop contexts in the admin panel, it doesn't redirect to example.com/**SHOP-VIRTUAL-URL**/adminXXXXXXX

**Comment by khouloudbelguith** [comment]
@IvoRabush, as described in this PR: https://github.com/PrestaShop/PrestaShop/pull/9450
The current behavior in PrestaShop is:

_The URLs in the left column keep the one in your address bar, even when you select a specific shop, and even if you have a subfolder installation instead of a domain one Perform the same check on the domain/address of another shop_

So, when you select another shop, it doesn't redirect to `exemple.com/virtual_URL/admin-dev/`
It could be confusing for some people to be redirected to another URL
The very purpose of this issue was to prevent using different URLs from one shop to another

It would cause problems with the authentication as the cookie is stored by domain.
With the actual fix, you can administrate all your stores from a single, unchanging URL (whether the main one or a secondary shop url), which prevents domain switching and unlocking. 

Thanks!

**Comment by IvoRabush** [comment]
@khouloudbelguith 
I saw the commit, I compared the classes/link.php class I had and it's the same. no difference.
Still the issue is there.

Can you please test this print on your setup and see if the shop context will change when you change the shop context in the admin panel ?

![image](https://user-images.githubusercontent.com/32366618/70319838-edc51d00-182b-11ea-9aa2-5a86e9a07000.png)

echo "TIME ZONE : " . date_default_timezone_get() . " | " .
     "DATE: " . date("H:i:s") .  " | " .
     "CONTEXT SHOP ID: " . $context->shop->id . " | " .
     "SHOP CONTEXT SHOP ID: " . Shop::getContextShopID(true);

**Comment by khouloudbelguith** [comment]
@IvoRabush, I have this exception when changing the shop context.
![image](https://user-images.githubusercontent.com/16067358/70321620-0e8b7380-1828-11ea-8bb3-05f6f570d314.png)

Thanks!

**Comment by IvoRabush** [comment]
@khouloudbelguith  instead of the **echo** can you then try the looger again in the same file just after the **@date_default_timezone_set(Configuration::get('PS_TIMEZONE'));**

$logger = new FileLogger();
$logger->setFilename(_PS_ROOT_DIR_ . '/var/logs/' . date('Ymd') . '_shop_context_check.log');
$logger->logInfo('START ...');
$logger->logInfo("TIME ZONE : " . date_default_timezone_get());
$logger->logInfo("DATE : " . date("H:i:s"));
$logger->logInfo("CONTEXT SHOP ID : " . $context->shop->id );
$logger->logInfo("SHOP CONTEXT SHOP ID : " . Shop::getContextShopID(true));
$logger->logInfo('END ...');
$logger->logInfo('');

This should creates a file in /var/logs/20191206__shop_context_check.log
Can you please upload it after changing the shop context to different shops ?

**Comment by IvoRabush** [comment]
After you change the shop context few times, check the **SHOP ID** value in the log, you will see that it's the same doesn't matter which shop context you are.

After that, change the log filename to '_shop_context_check_url_change.log' and on your browser change the URL from domain.com/adminXXXXXX to domain.com/**VIRTUAL-URL**/adminXXXXXX and see the difference in the log, the **SHOP ID** will be correct.

I would like see both logs if possible

**Comment by khouloudbelguith** [comment]
@IvoRabush, new exception
![image](https://user-images.githubusercontent.com/16067358/70327489-30d8bd80-1837-11ea-8fdf-65e23ca68b1f.png)
![image](https://user-images.githubusercontent.com/16067358/70327533-48b04180-1837-11ea-999e-0dc0e66a38b6.png)

Thanks!

**Comment by IvoRabush** [comment]
Remove the PS_ROOT_DIR and the point, let it be like this $logger->setFilename('/var/logs/' . date('Ymd') . '_shop_context_check.log');

**Comment by khouloudbelguith** [comment]
@IvoRabush, I have this error
`Directory /var/logs is not writable`
All permissions are good
![image](https://user-images.githubusercontent.com/16067358/70330661-4998a180-183e-11ea-9af9-d6128014c7f0.png)

Thanks!

**Comment by IvoRabush** [comment]
Hello @khouloudbelguith ,

The defines.inc.php is loaded after config.inc.php on your PS version, that's why the _PS_ROOT_DIR is not defined.
``
Here you are the code for the logger, it should work now:
$logCurrentDirectory = `dirname(__FILE__);`
$logPSRootDirectory = realpath($logCurrentDirectory.'/..');

$logger = new FileLogger();
$logger->setFilename($logPSRootDirectory . '/var/logs/' . date('Ymd') . '_shop_context.log');
$logger->logInfo('START ...');
$logger->logInfo("TIME ZONE : " . date_default_timezone_get());
$logger->logInfo("DATE : " . date("H:i:s"));
$logger->logInfo("CONTEXT SHOP ID : " . $context->shop->id );
$logger->logInfo("SHOP CONTEXT SHOP ID : " . Shop::getContextShopID(true));
$logger->logInfo('END ...');
$logger->logInfo('');

After making the test with switching the shop context from the upper right corner. Can you please make the second test as following:
1. Change the looger script to the following
$logCurrentDirectory = `dirname(__FILE__);`
$logPSRootDirectory = realpath($logCurrentDirectory.'/..');

$logger = new FileLogger();
$logger->setFilename($logPSRootDirectory . '/var/logs/' . date('Ymd') . '_shop_context_url_prefix.log');
$logger->logInfo('START ...');
$logger->logInfo("TIME ZONE : " . date_default_timezone_get());
$logger->logInfo("DATE : " . date("H:i:s"));
$logger->logInfo("CONTEXT SHOP ID : " . $context->shop->id );
$logger->logInfo("SHOP CONTEXT SHOP ID : " . Shop::getContextShopID(true));
$logger->logInfo('END ...');
$logger->logInfo('');

2. change the url to example.com/**VIRTUAL-URL**/adminXXXXXXX

This should generate 2 log files that you can find in the project root directory under var/logs 
1st filename: datetime_shop_context.log
2nd filename: datetime_shop_context_url_prefix.log

**Comment by khouloudbelguith** [comment]
@IvoRabush, thanks for your feedback.
The first test, I changed between shops & I have this log file
[20191209_shop_context.log](https://github.com/PrestaShop/PrestaShop/files/3940071/20191209_shop_context.log)
The second test, I added this virtual URL to the link, I have this log file
[20191209_shop_context_url_prefix.log](https://github.com/PrestaShop/PrestaShop/files/3940092/20191209_shop_context_url_prefix.log)

Thanks to check & feedback.

**Comment by IvoRabush** [comment]
@khouloudbelguith I was coorect, if you check the first log, you will only see Shop ID 1 which is the shop without virtual URL. In short you changed the shop context but it always return Shop ID 1.

In the second test you changed the admin URL and then in the log you can see Shop ID 1 and Shop ID 2.

**Comment by khouloudbelguith** [comment]
Hi @IvoRabush,

Thanks for these clarifications. 
Ping @jolelievre what do you think? 

The "Admin URL issue" is fixed with this PR: #9450 as described in this [ticket](http://forge.prestashop.com/browse/BOOM-3607).
Thanks!

**Comment by IvoRabush** [comment]
Hello,
almost 2 months later and still not raction ...
Any updates ?

**Comment by khouloudbelguith** [comment]
Ping @jolelievre friendly reminder :) 

Thanks!

**Comment by PierreRambaud** [comment]
Hi and really sorry for the delay, we are really busy with many other issues.

If I correctly understand what you are trying to do, is using the correct shop in the admin depending on the URL?
I manage to reproduce if I'm right :sweat_smile: 
![image](https://user-images.githubusercontent.com/1462701/99822453-86df6780-2b53-11eb-89a6-60e1b68b790a.png)

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

If you reproduce it, I believe we need to add the **`To Do`** label, is that so?

Thanks!

**Comment by PierreRambaud** [comment]
I don't know if it's the desired behaviour or not. It always depend on the @PrestaShop/product-team :)

**Comment by boo-code** [comment]
Measured both halves of this report on 9.2. They have separate answers, so it is worth splitting them.

## The shop context itself follows the selector

The reported symptom does not reproduce. Replaying a back office request on the main domain and then
applying the shop selector exactly as `AdminController::initShopContext()` does for a cookie value of
`s-2`:

```
                                        Context::getContext()->shop->id    Shop::getContextShopID(true)
  after bootstrap (URL = shop 1)                     1                                1
  after switching BO context to shop 2               2                                2
```

The reason the original log said otherwise is placement, and it is worth stating because it is what
kept this thread stuck. The probe was inserted right after
`@date_default_timezone_set(Configuration::get('PS_TIMEZONE'))` in `config/config.inc.php`. At that
point only `Shop::initialize()` has run, which resolves the shop from the URL
(`classes/shop/Shop.php:331`, `if (!($id_shop = Tools::getValue('id_shop')) || defined('_PS_ADMIN_DIR_'))`).
The selector is applied later, by `AdminController::initShopContext()` for legacy pages and by
`ShopContextSubscriber` for migrated ones. So a probe in `config.inc.php` reads the URL shop by
construction, whichever shop is selected - it was measuring bootstrap, not the shop context.

@PierreRambaud's screenshot is a different observation and it still holds: the address bar can say
`/b/` while the selector says `a`. That is the open design question, not this.

## The timezone does not follow the selector

This half is real and still live on 9.2. Same replay, multistore, shop 1 on `Europe/Paris` and shop 2
on `Europe/Sofia`:

```
                                        PS_TIMEZONE     PHP timezone    MySQL session offset
  after bootstrap (URL = shop 1)        Europe/Paris    Europe/Paris    +02:00
  after switching BO context to shop 2  Europe/Sofia    Europe/Paris    +02:00

  PHP date()          2026-09-06 19:29:43
  MySQL NOW()         2026-09-06 19:29:43
  shop 2 wall clock   2026-09-06 20:29:43
```

`Configuration::get('PS_TIMEZONE')` is shop-aware and returns the selected shop's value, but PHP's
timezone was bound once at `config/config.inc.php:139` and there is no other
`date_default_timezone_set()` call anywhere in the tree. So every date written while working on shop 2
is stamped in shop 1's timezone - `ObjectModel::add()` stores `date('Y-m-d H:i:s')`
(`classes/ObjectModel.php:529`), and raw SQL resolves `NOW()` against the session offset, which is
aligned to the same stale value.

That is the mechanism behind the second half of the report, the one about order history rows appearing
to predate the order they belong to.

Two things worth noting for whoever specs this. A per-shop `PS_TIMEZONE` is reachable through the
standard back office: `Adapter\Configuration::set()` with no `ShopConstraint` builds one from the
current shop context (`src/Adapter/Configuration.php:146-153`), so saving Localization while a shop is
selected writes a row scoped to that shop - even though `LocalizationConfiguration` itself is not
declared multistore-aware. And the same shape reaches outside the back office, because
`classes/pdf/HTMLTemplate.php:230`, `classes/order/OrderHistory.php:239` and
`classes/webservice/WebserviceRequest.php:876` all switch shop context without the timezone following.

I have a fix for this half and will open it as its own issue and PR rather than attach it here, since
this ticket's headline claim is the design question above and closing it on a timezone fix would settle
something nobody has answered.
