### ISSUE TITLE
Module Theme template (override) translations not working properly

### ISSUE THREAD

**Issue by Perfecticus** [PrestaShop/PrestaShop#16862]
**Describe the bug**
When overriding a template of a module in your theme modules directory, adding a new translation, the texts appear in BO and is translatable (write to ps_translations works).

*I encountered this bug for the old translation tag*

The changed translation is not being used in FO however.
Tried clearing cache and deleting cache directory.

**To Reproduce**
1. Pick a module which has no overrides in your theme.
2. Create an override template with an **added/extra** translation and place it in themes/mytheme/modules/module/../template.tpl
3. Translate the module string for the theme in Back office
4. Check view in front office

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

![Template](https://puu.sh/ER5oT/430b7899f8.png)
![Back-office](https://puu.sh/ER5oj/f487ffbad0.png)
![DB](https://puu.sh/ER5S5/74f3f4901b.png)
![Front-office](https://puu.sh/ER5TF/d3f2c1b327.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

**Comment by rdy4ever** [comment]
Hi @Perfecticus 
To mitigate this issue, use theme domain instead of module when overriting module templates in your custom theme. For example instead of `mod='faqs'` use `d='Mods.Faqs'` . And you will find the translation in the BO under the Mods domain, Faqs subdomain.

**Comment by khouloudbelguith** [comment]
Hi @Perfecticus,

You can follow those links: https://build.prestashop.com/news/new-translation-system-prestashop-17/#calling-symfonys-translator
https://build.prestashop.com/howtos/translation/how-to-translate-your-theme/

Thanks!

**Comment by Perfecticus** [comment]
> Hi @Perfecticus
> To mitigate this issue, use theme domain instead of module when overriting module templates in your custom theme. For example instead of `mod='faqs'` use `d='ModsFaqs'` (cammel case). And you will find the translation in the BO under the Mods domain, Faqs subdomain.

Hi @rdy4ever, thanks for that hint.

@khouloudbelguith, I have read through all of the documentation concerning translations and never figured out to do what rdy4ever said. I was under the impression that new translations would only be used when implementing a certain method in 1.7.6.1.

I saw this in https://devdocs.prestashop.com/1.7/modules/creation/module-translation/new-system/

![Opt-in for new translations](https://puu.sh/ER6Ze/8e43558fd5.png)

Perhaps it should be clarified that when overriding a module using legacy translation, the override needs to be adjusted to use new translation domains; i.e. 'Modules.Faqs.Search_block'

For me, this issue is resolved but I assume other people will and have jerked their hair over this.

**Comment by rdy4ever** [comment]
> Perhaps it should be clarified that when overriding a module using legacy translation, the override needs to be adjusted to use new translation domains; i.e. 'Modules.Faqs.Search_block'

I would only use one domain and one subdomain, like `Modules.Faqs`. Using more subdomains in custom transaltions may cause some issuses.
PS: Sorry about the CammelCase. Correct is to use `.` as you did. Use CammelCase in the subdomain just for visual aid, like `Modules.FaqsSearchblock`

**Comment by rdy4ever** [comment]
> I was under the impression that new translations would only be used when implementing a certain method in 1.7.6.1.

Modules, yes, must opt-in. But once you override a module template in your theme, you can use the new translation system just by using `d` instead of `mod` and the string will be interpreted as belonging to the theme and not to the module. That's how it's done in Classic theme for the default modules. See [this](https://github.com/PrestaShop/PrestaShop/blob/275d56c78c9d146eee5ae602d0b481e3e2485536/themes/classic/modules/ps_sharebuttons/views/templates/hook/ps_sharebuttons.tpl#L29) file, for reference.

**Comment by khouloudbelguith** [comment]
@Perfecticus, thanks for your feedback.
>For me, this issue is resolved

Since it is resolved, I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by micka-fdz** [comment]
Following a discussion with @ttoine, this issue isn't yet resolved.

When we need to add new module translations on an override file (in `themes/modules/modulename` folder), these translations appear on BO but don't work on FO. We need to replace `mod='modulename'` domains with new `d='Themes.Modules.Modulename'` domains.

@khouloudbelguith can you reopen this issue please? Thanks.

**Comment by Perfecticus** [comment]
If it's of any help; what worked for me was a domain tag following this pattern:

{l s='Looking for answers? Our FAQ is the quickest way of finding it.' d='**Modules.Faqs.Search_block**'}

**Comment by micka-fdz** [comment]
Yes @Perfecticus, I do that on all my projects but it's just a workaround.
I think it's a core bug that needs to be fixed, please reopen this issue.

**Comment by ttoine** [comment]
@eternoendless knows a lot about the translation problems, maybe we could have his opinion?
also, @micka-fdz is there a link with #17844, and if yes, can you please explain why?

**Comment by micka-fdz** [comment]
No @ttoine, I think it's two separate issues.
