### ISSUE TITLE
Facing 500 error on the Admin

### ISSUE THREAD

**Issue by 06463771** [PrestaShop/PrestaShop#17368]
I am facing 500 error on the prestashop admin login page. The site  is working fine. below are the cpanel error logs :-

[Mon Jan 27 02:01:19.526239 2020] [lsapi:error] [pid 1292460:tid 139663316444928] [client 157.36.174.52:59055] [host www.picfair.in] Backend fatal error: PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove directory "/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr": rmdir(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr): Directory not empty. in /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180\nStack trace:\n#0 /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /home/nkh94n2gnruv/public_html/classes/Tools.php(3295): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 [internal function]: ToolsCore::{closure}()\n#3 {main}\n  thrown in /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:01:16.345629 2020] [lsapi:error] [pid 1336577:tid 139663253505792] [client 157.36.174.52:59054] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:01:16.340224 2020] [lsapi:notice] [pid 1336577:tid 139663253505792] [client 157.36.174.52:59054] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.509360 2020] [lsapi:error] [pid 1292457:tid 139663190566656] [client 157.36.174.52:59034] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.509316 2020] [lsapi:notice] [pid 1292457:tid 139663190566656] [client 157.36.174.52:59034] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.469635 2020] [lsapi:error] [pid 1292162:tid 139663222036224] [client 157.36.174.52:59029] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.469542 2020] [lsapi:notice] [pid 1292162:tid 139663222036224] [client 157.36.174.52:59029] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.420626 2020] [lsapi:error] [pid 1292163:tid 139663358404352] [client 157.36.174.52:59033] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.420572 2020] [lsapi:notice] [pid 1292163:tid 139663358404352] [client 157.36.174.52:59033] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.377600 2020] [lsapi:error] [pid 1027888:tid 139663274485504] [client 157.36.174.52:59354] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.377495 2020] [lsapi:notice] [pid 1027888:tid 139663274485504] [client 157.36.174.52:59354] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:19.873404 2020] [lsapi:error] [pid 1292468:tid 139663410853632] [client 157.36.174.52:59030] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:19.873346 2020] [lsapi:notice] [pid 1292468:tid 139663410853632] [client 157.36.174.52:59030] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY

Please tell me how to resolve this.

**Comment by khouloudbelguith** [comment]
Hi @06463771,

Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

Thanks!

**Comment by 06463771** [comment]
Ok Mam 

Let me try. As I am not a developer.

**Comment by 06463771** [comment]
Mam can you do this for me. because there are too many files under addons_service. I am confused.
I can provide you details

**Comment by khouloudbelguith** [comment]
@06463771,

>Mam can you do this for me

Sorry, no!
But, I can help you.
>Let me try. As I am not a developer.

please, make a backup of your database and your files before any deletion.

You need to connect to your hosting space using your FTP client, by using the connection details provided by your web host (if not, contact your host).
Once connected, it is time to navigate this directory: [/Project_Folder/var/cache/](https://github.com/PrestaShop/PrestaShop/tree/1.7.6.0/var/cache)
You have `dev/` or `prod/` folder, you need to delete them manually.

Thanks to check & feedback.

**Comment by 06463771** [comment]
I have deleted dev/ and prod/ folder, but still facing the same issue

**Comment by 06463771** [comment]
Now on the admin link, the main website is showing.

**Comment by 06463771** [comment]
Now facing 404 error on the admin

**Comment by khouloudbelguith** [comment]
@06463771, 
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

PS: If you can’t access your dashboard, you can still enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`

… and change it to:

`define('_PS_MODE_DEV_', true);`

Thanks!

**Comment by 06463771** [comment]
Let me try. As I am not a developer.

**Comment by 06463771** [comment]
I have enabled the debug mode as you told and below is the link of my Admin 

www.picfair.in/01qezb1glssvthci/

And these are the error logs :-


[Mon Jan 27 02:41:03.397100 2020] [authz_core:error] [pid 1719982:tid 139663263995648] [client 45.55.58.166:54534] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/contact_form.txt
[Mon Jan 27 02:41:03.396195 2020] [authz_core:error] [pid 1721139:tid 139663211546368] [client 45.55.58.166:54532] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/productoutofstock.txt
[Mon Jan 27 02:41:03.394471 2020] [authz_core:error] [pid 1722184:tid 139663211546368] [client 45.55.58.166:54536] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/password_query.txt
[Mon Jan 27 02:41:03.384549 2020] [authz_core:error] [pid 1719983:tid 139663253505792] [client 45.55.58.166:54538] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/guest_to_customer.txt
[Mon Jan 27 02:41:03.374504 2020] [authz_core:error] [pid 1719980:tid 139663201056512] [client 45.55.58.166:54542] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/voucher.txt
[Mon Jan 27 02:41:00.538106 2020] [authz_core:error] [pid 1722184:tid 139663180076800] [client 45.55.58.166:54512] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/employee_password.txt
[Mon Jan 27 02:41:00.534388 2020] [authz_core:error] [pid 1719983:tid 139663400363776] [client 45.55.58.166:54510] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/contact.txt
[Mon Jan 27 02:41:00.526837 2020] [authz_core:error] [pid 1719980:tid 139663284975360] [client 45.55.58.166:54516] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/log_alert.txt
[Mon Jan 27 02:41:00.526442 2020] [authz_core:error] [pid 1720534:tid 139663253505792] [client 45.55.58.166:54508] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/voucher_new.txt
[Mon Jan 27 02:41:00.519964 2020] [authz_core:error] [pid 1719984:tid 139663389873920] [client 45.55.58.166:54518] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/reply_msg.txt
[Mon Jan 27 02:41:00.516821 2020] [authz_core:error] [pid 1719982:tid 139663190566656] [client 45.55.58.166:54514] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/order_customer_comment.txt
[Mon Jan 27 02:40:57.772575 2020] [authz_core:error] [pid 1722184:tid 139663326934784] [client 45.55.58.166:54506] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/order_merchant_comment.txt
[Mon Jan 27 02:40:57.765095 2020] [authz_core:error] [pid 1719983:tid 139663295465216] [client 45.55.58.166:54502] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/backoffice_order.txt
[Mon Jan 27 02:40:57.764032 2020] [authz_core:error] [pid 1720981:tid 139663337424640] [client 45.55.58.166:54498] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/import.txt
[Mon Jan 27 02:40:57.760631 2020] [authz_core:error] [pid 1720534:tid 139663263995648] [client 45.55.58.166:54504] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/forward_msg.txt
[Mon Jan 27 02:40:57.755920 2020] [authz_core:error] [pid 1719981:tid 139663337424640] [client 45.55.58.166:54500] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/test.txt
[Mon Jan 27 02:40:57.755790 2020] [authz_core:error] [pid 1720772:tid 139663190566656] [client 45.55.58.166:54496] AH01630: client denied by server configuration: /home/nkh94n2gnruv/public_html/mails/en/newsletter.txt
[Mon Jan 27 02:01:19.526239 2020] [lsapi:error] [pid 1292460:tid 139663316444928] [client 157.36.174.52:59055] [host www.picfair.in] Backend fatal error: PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove directory "/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr": rmdir(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr): Directory not empty. in /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180\nStack trace:\n#0 /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(177): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /home/nkh94n2gnruv/public_html/classes/Tools.php(3295): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 [internal function]: ToolsCore::{closure}()\n#3 {main}\n  thrown in /home/nkh94n2gnruv/public_html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:01:16.345629 2020] [lsapi:error] [pid 1336577:tid 139663253505792] [client 157.36.174.52:59054] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:01:16.340224 2020] [lsapi:notice] [pid 1336577:tid 139663253505792] [client 157.36.174.52:59054] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.509360 2020] [lsapi:error] [pid 1292457:tid 139663190566656] [client 157.36.174.52:59034] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.509316 2020] [lsapi:notice] [pid 1292457:tid 139663190566656] [client 157.36.174.52:59034] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.469635 2020] [lsapi:error] [pid 1292162:tid 139663222036224] [client 157.36.174.52:59029] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.469542 2020] [lsapi:notice] [pid 1292162:tid 139663222036224] [client 157.36.174.52:59029] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.420626 2020] [lsapi:error] [pid 1292163:tid 139663358404352] [client 157.36.174.52:59033] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.420572 2020] [lsapi:notice] [pid 1292163:tid 139663358404352] [client 157.36.174.52:59033] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.377600 2020] [lsapi:error] [pid 1027888:tid 139663274485504] [client 157.36.174.52:59354] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:20.377495 2020] [lsapi:notice] [pid 1027888:tid 139663274485504] [client 157.36.174.52:59354] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:19.873404 2020] [lsapi:error] [pid 1292468:tid 139663410853632] [client 157.36.174.52:59030] [host www.picfair.in] Backend fatal error: PHP Fatal error:  require(): Failed opening required '/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php' (include_path='/home/nkh94n2gnruv/public_html/vendor/pear/pear_exception:/home/nkh94n2gnruv/public_html/vendor/pear/console_getopt:/home/nkh94n2gnruv/public_html/vendor/pear/pear-core-minimal/src:/home/nkh94n2gnruv/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear') in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY
[Mon Jan 27 02:00:19.873346 2020] [lsapi:notice] [pid 1292468:tid 139663410853632] [client 157.36.174.52:59030] [host www.picfair.in] Backend log: PHP Warning:  require(/home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/getPrestashop_AccessDenied_ListenerService.php): failed to open stream: No such file or directory in /home/nkh94n2gnruv/public_html/var/cache/prod/ContainerKzusowr/appProdProjectContainer.php on line 1133\n, referer: http://www.picfair.in/01qezb1glssvthci/index.php/improve/modules/updates?_token=WzAcUStjMNBoqJLqjGUiknE3FskfHlLv85dnZsOWpfY

**Comment by khouloudbelguith** [comment]
@06463771, you have cache issues as always
Could you please try to clear the cache manually by deleting all the folder into var/cache (prod & dev).
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache. (Navigate to your BO => Advanced Parameters => Performance page).

>client denied by server configuration
You have also a permission issue on your server

Please contact your host about this issue.

Thanks to check with them & feedback.

**Comment by 06463771** [comment]
I am not able to login to my BO, so how can I follow the second instruction which you are saying to do ?

**Comment by 06463771** [comment]
I have deleted both the folders just know, still it showing the 404 error (The page you are looking for was not found. ). Its not showing me the admin login page

**Comment by 06463771** [comment]
I have contacted to my Hosting provider and this issue was of there hand and they sorted out. 
Thanks for your support.

**Comment by khouloudbelguith** [comment]
@06463771, thanks for your feedback.
Since it is fixed, I will close the issue, feel free to open a new one when needed.

Thanks!

**Comment by Perfecticus** [comment]
@khouloudbelguith 

I have been trying to find other people having the issues I'm having and this appears to match my case. I have had problems on 1.7.6.1 and still have issues after migrating to 1.7.6.3.

The cache appear to end up in an unrecoverable state quite often after being cleaned.
Some routines in prestashop clears cache files automatically, I havnt investigated exacly which,
but I assume saving seo/url-options does so, as I have encountered the non-recoverable 500 when saving that.

More frequently I encounter this when manually clearing the var/cache/prod when working with mail themes and templates. Apparently you need to clear the entire cache in order to generate new mail templates from mail theme, so that is what I have been doing.

Most of the time I encounter this bug and have to run 'rm -r var/cache/prod' a number of times before the shop starts working again.

Lately I have found a more reliable way and that is to 'rm -r var/cache/prod && service apache2 restart', which I have found to be working every time.

The problem/bug still is severe in a production environment.
The customers I host webshops for does not have server experience nor access and cannot perform the tasks I have had to do to restore the shops functionality in the case of a broken cache.

So I would urge the prestashop team to look into this and try harder to reproduce this issue.
Not sure if the problem only occurs when theres frequent traffic to the shop, i.e. multiple threads trying to load the shop when the cache is not initialized, but its a theory.

The exceptions I see in the log can refer to various files but usually one of these:
PHP Fatal error:  require(): Failed opening required '/var/www/html/xxx/var/cache/prod/ContainerPemfwrx/getPrestashop_AccessDenied_ListenerService.php'
PHP Fatal error:  require(): Failed opening required '/var/www/html/xxx/var/cache/prod/ContainerPemfwrx/getRouting_LoaderService.php'

I'm surprised not more people are facing this issue.
I have been getting it on development, staging and production servers for multiple shop installs.
Appears to only happen for production cache (dev mode off).

Best regards
Perfecticus

**Comment by HartLarsson** [comment]
@Perfecticus 
Please verify also that your PHP version is max. 7.2 version.

**Comment by Perfecticus** [comment]
> @Perfecticus
> Please verify also that your PHP version is max. 7.2 version.

Thanks @HartLarsson , this was resolved, but solution is in #17390
