### ISSUE TITLE
Order status list is under the header not completely displayed

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17717]
**Describe the bug**
Order status list is under the header not completely displayed

**To Reproduce**
1. Go to orders > orders
2. Make sure you have a lot of orders
3. Scroll down and click on an order status in the list 
3. You don't see all status  

https://drive.google.com/file/d/1-LYxdLLRAXxzXastAloSbxVEHqWxWFqP/view?usp=sharing

**Screenshots**
![76763182-ea2e2400-6792-11ea-9a45-e6acf2a51edd](https://user-images.githubusercontent.com/13449658/77053301-72e4d400-69ce-11ea-88fe-d78d0b6ac496.png)

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by #17849

**Comment by marionf** [comment]
Weird, I still have this issue after a `git pull` & I don't have cache
@NeOMakinG 

![capture d'écran_2449](https://user-images.githubusercontent.com/13449658/76763182-ea2e2400-6792-11ea-9a45-e6acf2a51edd.png)

**Comment by marionf** [comment]
@SD1982 Could you recheck on your side because I still have the issue
Thanks :)

**Comment by SD1982** [comment]
Hello @marionf  checked a second time on my side and as you can see on the screenrecord i don't have the same behaviour than you :
https://drive.google.com/file/d/1_WcRi7NniZfvIcthKycyKvtJtAY02i7t/view?usp=sharing

**Comment by marionf** [comment]
@SD1982 
It seems you are not looking the good drop-down, the problem is when you click on the status for a specific order

**Comment by SD1982** [comment]
Hi @marionf sorry my bad didn't share the good screen record but even with the other drop-down as you can see he is displayed on top of the header even when scrolling the page 
https://drive.google.com/file/d/1m48wfazvq6Oz-pW8cZ7ydXOxoUMz_ArS/view

**Comment by marionf** [comment]
@SD1982 it's not with all orders and you need to have a lot of orders, please see the video below

https://drive.google.com/file/d/1-LYxdLLRAXxzXastAloSbxVEHqWxWFqP/view?usp=sharing

**Comment by SD1982** [comment]
@marionf  Indeed it seems that when I carried out my tests I did not have enough orders in my table. And so indeed with more orders in the table the problem is clearly still visible.
https://drive.google.com/file/d/1lJdcuWh4aNatD7aGRsmKhjFGjmKqv3OF/view

**Comment by marionf** [comment]
Thank you @SD1982 :+1: 
As it's not completely fixed, I put it back in to do @NeOMakinG

**Comment by NeOMakinG** [comment]
Hey @marionf on my screen, the dropdown stay under his parent item, but you can scroll to the parent item to see it entirely, is that behavior wrong ? It looks like its the normal behavior (getting it sticky to the screen makes it impossible to be shown entirly in some cases)

![image](https://user-images.githubusercontent.com/14963751/77167741-e3ffb680-6ab6-11ea-963d-afb4e3dff6df.png)

**Comment by marionf** [comment]
Hey @NeOMakinG 

> the dropdown stay under his parent item, but you can scroll to the parent item to see it entirely, is that behavior wrong ? 

Yes, it seems the good behavior, but did you see the screenrecord ? https://drive.google.com/file/d/1lJdcuWh4aNatD7aGRsmKhjFGjmKqv3OF/view 

The problem is when there are a lot of orders, if you scroll down and then click on the status for an order in the middle of the list

**Comment by Progi1984** [comment]
Fixed by #18245
