### ISSUE TITLE
[FIXED] [gsitemap] Hi, why in my sitemap, there aren't links about manufacturers?

### ISSUE THREAD

**Issue by maca91** [PrestaShop/PrestaShop#17771]
**Describe the bug**
In my sitemap I don't have the urls about manufacturer, for example:
https://www.grelaparfum.it/brand/72-acqua-di-parma.
They are very important for my SEO.

The module configuration, seem correct!

This, is my sitemap:
https://www.grelaparfum.it/1_it_0_sitemap.xml

**Screenshots**
Mine configuration:
![image](https://user-images.githubusercontent.com/1758730/75016875-3afc7680-548c-11ea-8798-f1b641b446ea.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.3

**Comment by maca91** [comment]
FIXED using:
https://github.com/PrestaShop/gsitemap/pull/126

**Comment by khouloudbelguith** [comment]
Hi @maca91,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2 and the `gsitemap` module v4.1.0.
It was ok with `gsitemap` module v3.2.2.
![image](https://user-images.githubusercontent.com/16067358/75022233-ff66aa00-5495-11ea-9493-1a1490a28e5d.png)

I will re-open the issue sine the PR not merged yet.

Thanks!

**Comment by danigart** [comment]
No progress on this issue yet? Manufacturers' URLs are still missing in the latest version of this sitemap generator.
