### ISSUE TITLE
If there are many invoices, you can't add a note for the second invoice

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17918]
#### Describe the bug

If there are many invoices, you can't add a note for the second invoice

#### Steps to Reproduce

1. Go to orders > orders
2. Click on View for an order in "payment accepted" status
3. Add a product to the order and select "Create a new invoice"
4. Click on "Documents" tab and on "Add a note" for the second invoice
5. The field isn't displayed and you can't add a note

#### Additional information
https://drive.google.com/file/d/1Xesd_1-4cAXm36JCADXj3WNKxSLRa8bq/view?usp=sharing

It was working in legacy

![capture d'écran_2414](https://user-images.githubusercontent.com/13449658/75684555-4c6a2d80-5c99-11ea-98d4-6708b47ada45.png)

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by tdavidsonas88** [comment]
@matks I take this from this morning. Was able to replicate the bug.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18045

**Comment by marionf** [comment]
Seems not completely fixed: https://github.com/PrestaShop/PrestaShop/issues/18096
