### ISSUE TITLE
install/upgrade/upgrade.php:  Call to a member function trans() 

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#17936]
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "PHP" Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to a member function trans() on null in /publice_html/src/PrestaShopBundle/Install/XmlLoader.php:469
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "Stack" trace:
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#0" /publice_html/src/PrestaShopBundle/Install/XmlLoader.php(349): PrestaShopBundle\\Install\\XmlLoader->flushDelayedInserts()
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#1" /publice_html/src/PrestaShopBundle/Install/Install.php(476): PrestaShopBundle\\Install\\XmlLoader->populateEntity('tab')
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#2" /publice_html/install/upgrade/php/migrate_tabs_17.php(63): PrestaShopBundle\\Install\\Install->populateDatabase('tab')
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#3" [internal function]: migrate_tabs_17()
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#4" /publice_html/src/PrestaShopBundle/Install/Upgrade.php(482): call_user_func_array('migrate_tabs_17', Array)
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#5" /publice_html/src/PrestaShopBundle/Install/Upgrade.php(825): PrestaShopBundle\\Install\\Upgrade->upgradeDb(Array)
Tue Mar 03 12:09:24 2020 warn pid 1998 [fcgid_bucket.c(153):] "client xxx.xxx.xxx.xxx:54352" mod_fcgid: stderr: "#6" /publice_html/install/upgrade/upgrade.php(9 in /publice_html/src/PrestaShopBundle/Install/XmlLoader.php on line 469

**Comment by khouloudbelguith** [comment]
Hi @hekep,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source) before the upgrade
 - PrestaShop version after the upgrade
 - 1-click upgrade module version
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by hekep** [comment]
I "have solved" the issue like this:

/publice_html/src/PrestaShopBundle/Install/XmlLoader.php on line 469

	/*
                $this->setError($this->translator->trans('An SQL error occurred for entity <i>%entity%</i>: <i>%message%</i>', array('%entity%' => $entity, '%message%' => Db::getInstance()->getMsgError()), 'Install'));
				*/
				
				  $this->setError('An SQL error occurred for entity <i>'.$entity.'</i>: <i>'.Db::getInstance()->getMsgError().'</i>' );

**Comment by khouloudbelguith** [comment]
@hekep, since it is fixed, I will close the issue.
Feel free to open a new one when needed.

Thanks!

**Comment by hekep** [comment]
To reproduce the issue you should have  incomplete  Prestashop database, which is unlikely to have.   But the bug or error is still there.  It stops entire process to Apache 500.

**Comment by hekep** [comment]
You are not really foolproofing , the software.

**Comment by hekep** [comment]
I did try this one:
https://www.prestashop.com/forums/topic/607468-call-to-a-member-function-trans-on-a-non-object/

To change 
this->translator->trans()
to 
Context::getContext()->getTranslator()->trans()

And got errormessage:
mod_fcgid: stderr: "PHP" Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Context" from namespace "PrestaShopBundle\\Install".

**Comment by khouloudbelguith** [comment]
@hekep, to reproduce, I need more details

1. PrestaShop version (source) before the upgrade
2. PrestaShop version after the upgrade
3. 1-click upgrade module version

Thanks!

**Comment by hekep** [comment]
Basicly you need to have incomplete database dump which triggers error message code 
in /publice_html/src/PrestaShopBundle/Install/XmlLoader.php on line 469

Prestashop 1.7.6.3.

**Comment by khouloudbelguith** [comment]
@hekep,

How can I have an incomplete database?
Are there any exact steps?

Thanks!

**Comment by hekep** [comment]
perhaps drop modules table from database. or some other tables.

**Comment by khouloudbelguith** [comment]
@hekep, 
>perhaps drop modules table from the database

manually?
This is will be an incorrect behavior.

Thanks!

**Comment by hekep** [comment]
Idea is to foolproof the code and tell correct error message to user, and not just die on displaying error message.

**Comment by khouloudbelguith** [comment]
@hekep, if you drop the ps_module tab from Database, all the BO will be broken.
![image](https://user-images.githubusercontent.com/16067358/75772323-01f5b900-5d4c-11ea-800d-fe384bc17b8d.png)

Thanks!

**Comment by hekep** [comment]
I do not know what problem exactly triggers code  in /publice_html/src/PrestaShopBundle/Install/XmlLoader.php on line 469

However "$this->translator->trans()" is not available in this"install/upgrade/upgrade.php"  context.

  $this->setError($this->translator->trans('An SQL error occurred for entity <i>%entity%</i>: <i>%message%</i>', array('%entity%' => $entity, '%message%' => Db::getInstance()->getMsgError()), 'Install'));

**Comment by khouloudbelguith** [comment]
@hekep, so having an incomplete database is not a solution to reproduce the issue.

Thanks!

**Comment by gyan111** [comment]
I am having the same issue. While auto upgrade this issue is occurring as the new files get downloaded dynamically I can't even change the file. Even if I change that will die with a error message at least or i dont know.

`[INTERNAL] /home/host/public_html/ps17/src/PrestaShopBundle/Install/XmlLoader.php line 467 - Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function trans() on null #0 /home/host/public_html/ps17/src/PrestaShopBundle/Install/XmlLoader.php(347): PrestaShopBundle\Install\XmlLoader->flushDelayedInserts() #1 /home/host/public_html/ps17/src/PrestaShopBundle/Install/Install.php(476): PrestaShopBundle\Install\XmlLoader->populateEntity('tab') #2 /home/host/public_html/ps17/admin187hbb2e8/autoupgrade/latest/install/upgrade/php/migrate_tabs_17.php(63): PrestaShopBundle\Install\Install->populateDatabase('tab') #3 [internal function]: migrate_tabs_17() #4 /home/host/public_html/ps17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(395): call_user_func_array('migrate_tabs_17', Array) #5 /home/host/public_html/ps17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(360): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.0.0', '/* PHP:migrate_...') #6 /home/host/public_html/ps17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(284): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.0.0', '/* PHP:migrate_...') #7 /home/host/public_html/ps17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.6.1.24') #8 /home/host/public_html/ps17/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(101): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.6.1.24') #9 /home/host/public_html/ps17/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #10 /home/host/public_html/ps17/admin187hbb2e8/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #11 {main}`


also I am not getting in the error but a warning that says:

`[WARNING] SQL 1.7.0.0 1062 in INSERT INTO `ps_hook` (`name`, `title`, `description`, `position`) VALUES ('actionValidateCustomerAddressForm', 'Customer address form validation', 'This hook is called when a customer submit its address form', '1'), ('displayAfterCarrier', 'After carriers list', 'This hook is displayed after the carrier list in Front Office', '1'), ('displayCarrierExtraContent', 'Display additional content for a carrier (e.g pickup points)', 'This hook calls only the module related to the carrier, in order to add options when needed.', '1'), ('validateCustomerFormFields', 'Customer registration form validation', 'This hook is called to a module when it has sent additional fields with additionalCustomerFormFields', '1'), ('displayProductExtraContent', 'Display extra content on the product page', 'This hook expects ProductExtraContent instances, which will be properly displayed by the template on the product page.', '1'), ('displayNavFullWidth', 'Navigation', 'This hook displays full width navigation menu at the top of your pages', '1'), ('displayAfterBodyOpeningTag', 'Very top of pages', 'Use this hook for advertisement or modals you want to load first.', '1'), ('displayBeforeBodyClosingTag', 'Very bottom of pages', 'Use this hook for your modals or any content you want to load at the very end.', '1'): Duplicate entry 'displayAfterBodyOpeningTag' for key 'hook_name'`

But I checked there is no duplicated data.
