### ISSUE TITLE
BO - Wrong total when changing currency after placing the order and adding a product

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18443]
#### Describe the bug

When adding a BO product to an order for which the currency has been changed, the order total is displayed in the original currency instead of the new currency.

This is an issue linked to this PR : https://github.com/PrestaShop/PrestaShop/pull/17927. I missed it when I tested the PR, sorry for that.

#### Expected behavior

The total should be displayed in the new currency.

#### Steps to Reproduce

1. Go to BO, add a second currency to the shop
2. Go to FO, make an order with any currency
3. Go to BO, to the order detail
4. In Payment block, change the currency. The change is OK, all Total and prices are converted
5. Add a product to the order : The totals are wrong : The sign is OK, but the number are in the first currency instead of the new one.

**Screenshots**

https://drive.google.com/file/d/16AtymmvvwpaNCO06UBdUmtOTKYFBwJQz/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Previously reported here: https://github.com/PrestaShop/PrestaShop/issues/16937 fixed by https://github.com/PrestaShop/PrestaShop/pull/17927

Is it?

Thanks!

**Comment by Robin-Fischer-PS** [comment]
No @khouloudbelguith , there is a little difference here : I change the currency of the order after the order is done and before adding the product.

#17927 does not fix this specific case.

**Comment by Progi1984** [comment]
Fixed by #18456
