### ISSUE TITLE
PrestaShop Addons returns an iframe in http instead of https

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#18500]
#### Describe the bug

addons.prestashop.com return an iframe not https

#### Steps to Reproduce

Open console go to theme catalogue

![addon-2](https://user-images.githubusercontent.com/5064590/78679848-06813480-78eb-11ea-879c-2c57c702572d.png)

#### Additional information

Why add an google tag ?

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php#L49

* PrestaShop version: N/A
* PHP version: N/A

**Comment by ghost** [comment]
Same at this url index.php/improve/design/themes/

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.4 and PS1.7.5.2
This issue is reproduced when **SSL** is enabled.
![image](https://user-images.githubusercontent.com/16067358/78681933-a8098580-78ed-11ea-9823-52f2fc416e0d.png)
![image](https://user-images.githubusercontent.com/16067358/78681975-b5bf0b00-78ed-11ea-8c77-a3d9733a9d85.png)

Ping @PrestaShop/prestashop-product-team @PrestaShop/prestashop-core-developers what do you think, it is related to PrestaShop Core or it is related to addons issue?

Thanks!

**Comment by ghost** [comment]
> is related to addons issue

**Comment by matks** [comment]
> it is related to PrestaShop Core or it is related to addons issue?

To Core I think 🤔 
It seems https://addons.prestashop.com/iframe/analytics-themes-1.6.html is correct so I'd say we must modify the code inside the software to use HTTPS instead of using HTTP

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php#L49

The content come from addons.prestashop.com

**Comment by ghost** [comment]
J'aurais fait le PR facile sinon @matks :+1: 

First https://addons.prestashop.com/iframe/search-1.7.php

Inside we find an iframe not https

**Comment by matks** [comment]
Found it ! It's actually an iframe injected into the page by MBO module

Http or https is controlled here: https://github.com/PrestaShop/ps_mbo/blob/master/controllers/admin/AdminPsMboModuleController.php#L331
It's supposed to use https when SSL is enabled 🤔

**Comment by ghost** [comment]
![Capture d’écran de 2020-04-07 17-20-25](https://user-images.githubusercontent.com/5064590/78687366-5e706900-78f4-11ea-90cd-ab956f31677a.png)

Call in https it's the same https://addons.prestashop.com/fr/iframe/search-1.7.php

**Comment by matks** [comment]
Ah I finally see what you mean 😄you're right, there are http links inside the response so it's mixed content. And indeed must be fixed on Addons side.
But I think software might also be fixed 🤔not sure that external calls are done using https everywhere

**Comment by ghost** [comment]
J'essaye de parler anglais un maximum ( sur github ) , j'avoue que ce ne doit pas être très compréhensible dès fois ... 

J'ai pas regardé les requêtes du logiciel

**Comment by khouloudbelguith** [comment]
Related to this: https://github.com/PrestaShop/PrestaShop/issues/9807

**Comment by ghost** [comment]
Yes it's like the  #9807

api, doc  and addons subdomains have to check all link ( iframe img css js ...) when return contents

**Comment by Matt75** [comment]
Fixed with ps_mbo v2.0.0

**Comment by marionf** [comment]
@PrestaShop/prestashop-qa Could you check if it's well fixed with ps_mbo v2.0.0 and close this issue if it is ?

**Comment by sarahdib** [comment]
Problem fixed with ps_mbo v2.0.0

**Comment by ghost** [comment]
I check the next release thx @Matt75

**Comment by ghost** [comment]
@Matt75 @sarahdib  not fixed 

https://github.com/PrestaShop/PrestaShop/issues/20879
