### ISSUE TITLE
BO Menu - Sell - Orders Bulk Action Change Order Status Cancelled does not get applied

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19072]
Like sayed,

go for your
BO Menu - Sell - Orders
scroll down and select bulk action dropwdown menu - Change order Status

!!! - Feature Request, it would be great to not first need to scroll down and choose bulk action, it would be great to DIRECTLY incorparate the select all/deselect all and Change Order Status feature into the top of the page - or for minimum, put the Bulk Action Button to the top of the page aswell

AFter you selected Change Status, the site refreshes,
now select for example the first 4 orders and choose as Status Cancelled.
In my case, he cancelled the last Order (the one at the Top). The other 3 do not get altered.
If these 3 are selected again, none of them gets altered.
I went into each order manually and canceled it.
After that I selected all 4, and changed them via bulk again to "Progress in Processing". All 4 got the new status updated successfully.

Now again I choose all 4 and try to cancel them: None of them got altered in the status.

I tried it with selecting single orders bevor using the bulk action - change order status command,
and I tried it with leaving all blank and first activate the bulk option, and than selecting the orders. It made no difference to the outcome.

Q:
Is Bulk Cancelling deactive for security reasons, or why does it behave so unpredictable to me?
If so, I would like an option to activate this feature.

PS: 1.7.6.5
PHP 7.1.3

Thanks

**Comment by sarahdib** [comment]
Hello @6xthFNGR 

In the 1.7.7. this feature request is already done : 
<img width="1278" alt="Capture d’écran 2020-05-12 à 10 35 00" src="https://user-images.githubusercontent.com/3034677/81661549-8f384680-943c-11ea-86f7-bdd6b13ed608.png">

I select 4 orders and in bulk action canceled the all 4 orders and it's working 
https://drive.google.com/file/d/1HxTjJ3opECfJqt5RXg824T6aZ1PHWMWv/view

**Comment by pitkz** [comment]
@sarahdib:
Well, it isnt working for me :P What should I say?

**Comment by colinegin** [comment]
The good news is that this feature had already been requested, so we implemented it in 1.7.7.
The beta version has been released just a few hours ago, so you can already test it (be careful not to use it in production) and see if this is what you were looking for ! The final PrestaShop 1.7.7 should be released in a few weeks, so you just need a bit of patience :-D

I close this issue, feel free to open a new one if you have other comments !

Thanks,

Coline

**Comment by pitkz** [comment]
@colinegin 
Why do you close this topic?
Reopen it as it is NOT solved!
You replied to just one part of it, and it wasnt even the mayor part! The bug still is existing.
This is not the first time some mod. closes some topic that is NOT solved, so I get quite upset about this.

Thanks

**Comment by colinegin** [comment]
As you can imagine, the error is human, so please stay cool, we are doing our best ! 
As you were talking about feature request, I did not see that you were also talking about a bug. Each issue needs to refer to a single bug or improvement so that we can better handle it.

About your bug, I've just tested it, and it seems to be working on my side : https://drive.google.com/file/d/1izEc9-SLkKfCbbMeQVc07mVRa4N25zKx/view

Can you please review it and tell me if i missed something ?

**Comment by pitkz** [comment]
Hello @colinegin 
I see your video and that you could not reproduce such behaviour.
I tried it again, with exactly the same "test orders" which are already written in PS.
It worked.
I tried my later orders again - which worked aswell.

This is an odd behaviour, as I did tested it several times the day I posted the issue (like mentioned, checking the boxes before using bulk action, and checking it after choosing bulk actions already. Also I tried to change it to another status and to cancel it again, like mentioned, which showed the behaviour I explained before).
Neither my Browser Conf. changed (and I tested some custom FireFox and some untouched Opera) nor my PS install.
I will be glad to try to reproduce this issue again and report back. For the moment I can not do extended testing. You may want to close it and if I reply again with more evidence we can open it again.


Thanks


May you advise me what I can "send in" for your help, as I just tested my 1.7.6.5 PS again, which is not modified in the core and "only" uses some modules by PS like the GDPR compliance and 1-click upgrade, and like PayPal and Stripe by 202 - which shouldnt cause this behaviour I guess?

**Comment by florine2623** [comment]
Hi @6xthFNGR ,
It is possible that the request did not go through entirely. 
You can check your log file to see if there are any fatal errors.
Thanks!

**Comment by florine2623** [comment]
Since we had no news from you, I'll close this ticket. Feel free to open another one if you can give specific details.
