### ISSUE TITLE
Changing titles of the Module "Contact Information" translation is not updating

### ISSUE THREAD

**Issue by north-sun** [PrestaShop/PrestaShop#19229]
#### Is your feature request related to a problem?
I'm using standard theme and I would like to modify footer. 
There are 4 block and in 2 of them I can modify everything including titles, but rest 2 I can't modify title. In the block "your account" I can't modify anything in block "store information" I can't modify the title. I thought I found field to change in translations but it was not effective. Would appreciate any help.

#### Describe the solution you'd like
I could modify these blocks in BO

---
#### Describe the bug
Title of "Contact Information" is not updating, even if i translate block title and text. It shows in database, but not in frontend.
"Store Information" on the footer shows up like this in frontend: 

![kuva](https://user-images.githubusercontent.com/8841448/108629660-a4c9aa80-7469-11eb-8f88-e670f632777a.png)

It shows up in database:
![kuva](https://user-images.githubusercontent.com/8841448/108629682-bca12e80-7469-11eb-8a2d-7176a0371554.png)

#### Expected behavior

Its tested with multiple themes, including default theme, it should show "Yhteystiedot".
![kuva](https://user-images.githubusercontent.com/8841448/108629698-d9d5fd00-7469-11eb-8bcd-474baf2ab003.png)

#### Steps to Reproduce

1. Go to 'International -> Translations'
2. Click on 'Installed modules translations -> Contact information -> Language: Suomi ( Finnish)'
3. Scroll down to ''Shop -> Store information and you see "valikko_määritykset", translate it and go to frontend".

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3.27

---
Headlines 1 and 2 are 18 px, 3 and 4 are 16 px. => **Fixed on Develop (1.7.8.0), see the screen record below**

**Screenshots**

https://www.awesomescreenshot.com/video/2837485?key=eef72337618faf11d46b4a7b096913f0

<img width="280" alt="Screenshot 2020-05-20 at 17 57 20" src="https://user-images.githubusercontent.com/65652765/82468685-66125880-9ac3-11ea-84a3-d7fb7a41a105.png">

<img width="246" alt="Screenshot 2020-05-20 at 17 57 29" src="https://user-images.githubusercontent.com/65652765/82468690-67438580-9ac3-11ea-9834-d669b73fc533.png">

**Comment by LouiseBonnard** [comment]
Dear @north-sun, could you please provide us with more info? We need more details to understand how we can reproduce your issue: your PrestaShop version, screenshots, etc.

You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report. Many thanks!

**Comment by operator2010** [comment]
- There is also a bug in footer colum 4 with the German translation -> Its called "SHOP-EINSTELLUNGEN" instead of "Kontakt" per Default
- the Colum headlines 3 and 4 has smaller font-size

**Comment by north-sun** [comment]
> Dear @north-sun, could you please provide us with more info? We need more details to understand how we can reproduce your issue: your PrestaShop version, screenshots, etc.
> 
> You don't know how to get this information? Please read the following article: http://build.prestashop.com/howtos/misc/how-to-create-bug-report. Many thanks!

Thank you for your reply. I'm using version 1.7.6.5. 
In the screenshot with blue arrows I'm showing fields I can't change. 
First 2 blocks in the footer I can change as I want but this 2 not. 

Thank you!

![Screenshot 2020-05-20 at 17 47 26](https://user-images.githubusercontent.com/65652765/82467903-80980200-9ac2-11ea-88f1-54d88742b016.jpg)

**Comment by north-sun** [comment]
> * There is also a bug in footer colum 4 with the German translation -> Its called "SHOP-EINSTELLUNGEN" instead of "Kontakt" per Default
> * the Colum headlines 3 and 4 has smaller font-size

I must admit I've noticed same problem. Headlines 1 and 2 are 18 px, 3 and 4 are 16 px.
<img width="280" alt="Screenshot 2020-05-20 at 17 57 20" src="https://user-images.githubusercontent.com/65652765/82468685-66125880-9ac3-11ea-84a3-d7fb7a41a105.png">
<img width="246" alt="Screenshot 2020-05-20 at 17 57 29" src="https://user-images.githubusercontent.com/65652765/82468690-67438580-9ac3-11ea-9834-d669b73fc533.png">

**Comment by LouiseBonnard** [comment]
Hi all, thanks for your feedback! Indeed, the two blocks in the footer you mentioned are related to the **My Account Block** and **Contact Information** modules.

You can just enable or disable them, or unhook them in _Design > Positions_, you cannot really modify their information - but note that your contact information is the one entered in the _Shop Parameters > Contact > Stores_ page of the back office, in the ‘Contact details’ section.

If you want to improve the translation, you can subscribe to [Crowdin](https://crowdin.com/project/prestashop-official) and suggest a better translation for your language in the _Modules/Contactinfo_ and _Modules/Customeraccountlinks_ repertories.

If you want to customize the wording, you can just go to the _International > Translations_ page of your back office and search for the wording in the 'Modify translations' section.

As for the design, nice catch, let's wait for a UX to study it. ;-)

**Comment by prestascott** [comment]
Hi @north-sun,

I agree with you, size of these titles need to be the same either 16px or 18px.

**Comment by NeOMakinG** [comment]
Titles sizes have been fixed months ago on develop (1.7.8)

**Comment by hibatallahAouadni** [comment]
Thanks @NeOMakinG but I think the original issue is not fixed yet :wink:

**Comment by M4ketech** [comment]
Its not about sizes, we can not have multiple language stores with 1.7.7.1? Seems like that, RIP multilingual stores who start with 1.7.7.1

![kuva](https://user-images.githubusercontent.com/8841448/108710427-b455fb80-751c-11eb-95d0-e8bb840d2adf.png)

**Steps to Reproduce**

Steps to reproduce the behavior:

1. Go to 'International -> Translations'
2. Click on 'Installed modules translations -> Contact information -> Language: Suomi ( Finnish)'
3. Scroll down to ''Shop -> Store information and you see "valikko_määritykset", translate it and go to frontend".
4. See error

Screenshots

If applicable, add screenshots or screen recordings to help explain your problem.
Additional information

    PrestaShop version: **1.7.7.1**
    PHP version: 7.3.27

Now i remember, when last time i did get this working with Prestashop, i was using 1.7.7.0, so maybe something is changed?

**Comment by hibatallahAouadni** [comment]
Hello @M4ketech 

I know you're frustated :confused:  but I already added your description in the bug report :wink: 
So, please be patient till it's fixed or f you want to help us fixing the problem, please create a Pull Request (PR).
We will galdly accept it :slightly_smiling_face: 

Thanks!

**Comment by M4ketech** [comment]
Tested with clean install of 1.7.7.2 problem is still there.

**Comment by MinnaLaa** [comment]
Found this location in server files where this translations could be:
/store_path/app/Resources/translations/fi-FI/ModulesContactinfoShop.fi-FI.xlf
And I also changed source language "en" to "en_US" which was the default language code.
Need to clear cache and force compilation files after saving the file. Hope this helps.

**Comment by boo-code** [comment]
The title is not in the domain people are editing, which is why translating the module changes nothing. This is still exactly the case on 9.2.x.

`ps_contactinfo` emits that heading three times, all with the theme domain:

```
ps_contactinfo.tpl:28        {l s='Store information' d='Shop.Theme.Global'}
ps_contactinfo.tpl:63        {l s='Store information' d='Shop.Theme.Global'}
ps_contactinfo-rich.tpl:27   {l s='Store information' d='Shop.Theme.Global'}
```

Its other nine strings use `Modules.Contactinfo.Shop`, so this one label is the outlier. The counts across the module's templates are 9 uses of `Modules.Contactinfo.Shop` against 3 of `Shop.Theme.Global`, and all three of those are this heading.

`ModuleProviderDefinition::getFilters()` restricts the "Installed modules translations" page to `Modules<Name>*` domains, so the heading is not on that page at all. Whatever is typed there lands in a domain the template never reads, which matches "It shows in database, but not in frontend".

**Where it can be edited today:** `FrontofficeProviderDefinition` declares `['^Shop*']`, so `Shop.Theme.Global` belongs to *Front office translations*. Translating "Store information" there does reach the footer, without touching any file.

On changing the code rather than the documentation, there is a trade-off worth stating before anyone picks this up. Moving the heading to `Modules.Contactinfo.Shop` would put it where merchants look, and would match the module's own convention. But the source string exists today in `translations/default/ShopThemeGlobal.xlf` and is translated there for every shipped locale, while `ModulesContactinfoShop.xlf` does not contain it. Moving the domain therefore drops the existing translation in every language until Crowdin catches up, so a non-English shop would see an English heading in its footer after upgrading. That is a translation-workflow decision rather than a code one, which is probably worth settling before the one-line change.

Separately, the Finnish string in the original screenshot looks like a translation-data problem in the `Shop.Theme.Global` catalogue rather than anything in the code, and would be fixed on Crowdin as @LouiseBonnard suggested in 2020.
