### ISSUE TITLE
Faceted search rebuild index counter is not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20109]
#### Steps to Reproduce

1. Create 500 products.
2. Go to Faceted search setting.
3. Hit Rebuild price index button (second from the left)
4. The button will show 100 prices to index all the time. It should show a total count of products decreasing by hundreds.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 3.5.0

I made this just for "not-to-forget" purposes, do not invest any time pls 😄.

**Comment by Hlavtox** [comment]
@florine2623 Weeeel, could be fixed, someday. Can you put it to the Faceted search epic? 😄

**Comment by florine2623** [comment]
I will put it under "Other issues".
Feel free to ping me under this issue if needed !

**Comment by marionf** [comment]
Hi @Hlavtox 
Is this issue fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/177 ?

**Comment by Hlavtox** [comment]
Hi @marionf,

no it did not fix it. There is no variable in the code that holds remaining product count I think, we would need to calculate. Maybe it was somehow forgotten during refactoring. :-)

Ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Maybe, I will have a check :)

**Comment by PierreRambaud** [comment]
@Hlavtox Can you check my pull request, is it what you need?

**Comment by Hlavtox** [comment]
@PierreRambaud You're the man!!! Works 🚀

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/190
