### ISSUE TITLE
Thumbnails are not automatically generated for 2x formats

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20218]
#### Describe the bug

If an image miniature is missing, it gets automatically generated, but not for images in 2x resolution.
Add it to #18518 pls.

#### Steps to Reproduce

1. Enable high-dpi images in prestashop image settings.
2. Put this to /themes/classic/templates/catalog/_partials/category-header.tpl:
```
<img src="{$link->getCatImageLink($category.link_rewrite, $category.id_image, 'category_default')|escape:'html':'UTF-8'}">
<img src="{$link->getCatImageLink($category.link_rewrite, $category.id_image, 'category_default2x')|escape:'html':'UTF-8'}">
```
2. Assign image to some category. Remember ID of that category. For example 100.
4. Go to /img/c and delete all images beginning with 100-, except the original **100.jpg**.
5. Visit this category in FO, only one image will be regenerated and visible.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
Thanks for your suggestion, but before adding this issue to the epic, could you tell me what the 2 lines of code are about ?
And in what case a PS user would add them to their /themes/classic/templates/catalog/_partials/category-header.tpl file ?
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 I wrote the 2 lines to make the bug reproducible more easily.

Prestashop offers an option to generate extra thumbnails of images in double the resolution. These images are used in image source sets in templates and can be displayed to people who have display scaling higher than 1. For example, I am using these images in my subcategories with this code.
`
<img src="https://www.trendo.cz/c/96-category_default/nerezove-drezy.jpg" srcset="https://www.trendo.cz/c/96-category_default2x/nerezove-drezy.jpg 2x" alt="Category name">
`
______________

If you don't know about display scaling and srcsets - Display scaling means that your screen resolution is not the same as the "content size". Every modern smartphone has a higher scaling, nearly every modern laptop. If using Windows, you can check your display scaling by right clicking on desktop and selecting "Display settings", you will see Scaling section with a percentage settings there.

For example, your iPhone has real screen width 1125 px, but displays the websites with width of 360 px. The image get's zoomed many times and gets blurred, if there is only one version of the image.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Isn't your issue similar to this ticket: #13957 which fixed with this PR: #16097?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Hi, tried just now and the issue is **not fixed** with this PR.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #19798
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/19965 to fix the issue.
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #19798

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/19965
