### ISSUE TITLE
Error  with the context->language in multistore context

### ISSUE THREAD

**Issue by dgonzalez360** [PrestaShop/PrestaShop#20807]
#### Describe the bug

There is an error in selecting the correct language when using a multishop and different languages for each store. 

 For example, let's assume that we have two shops (multistore) in the same domain with a virtual URL for each one:

SHOPA is using www.teststore.com/shopa with only English as a main and default language.
SHOPB is using www.teststore.com/shopb with only Spanish as a main and default language. 

English is only associated to ShopA and Spanish is only associated to ShopB. 

Both stores are in the same group. 

If you go to SHOPB you can see all the information in spanish, but if you access SHOPA then the selected language from the cookie is Spanish wich is not associated to SHOPA. 

This error is created in the config.inc.php file 

#### Expected behavior

When changing shops the id_lang from the cookie should be checked and validated in the config.inc.php before start loading the translations. 

#### Steps to Reproduce

1. Create two shops in the same group, assign the same domain and a virtual url for each one.
2. Assign one language to SHOP A and other Language to SHOPB , different languages for both and only associated one language per store. 
3. Go to SHOPA and then go to SHOPB, the language in SHOPB is the language set in SHOPA (To validate this just dump($context->language) in config.inc.php around line 200).

* PrestaShop version: 1.7.6.1 (But still happening up to 1.7.6.5)
* PHP version: 7.2.27

**Comment by florine2623** [comment]
HI @dgonzalez360 ,

I managed to reproduce your issue in PS 1.7.5.1 (related to https://github.com/PrestaShop/PrestaShop/issues/13928) and on PS 1.7.6.1.
However this has been fixed in PS 1.7.7.0.
You can see my screen record below :
In my case shop2 is in English and shop3 in French.
https://drive.google.com/file/d/1Oql7RyhaVBPZO-fKJXka5rM5BwRUBKvA/view

I'll close this issue, as it is fixed, thank you for your understanding !

**Comment by dgonzalez360** [comment]
Hi @florine2623 , 

I have read all the comments on issue #13298 and it seems it's not fixed. 

One user reported an admin language context error (Not related to my issue) and other reported the same I did and it appeared to be fixed in ps_facetedsearch change but it's not related at all. 

The issue I'm describing is caused by a bug in the config.inc.php file, and as long as it's not fixed there it will keep happening. 

My issue only happens the first time you load the second page and that is because there is a validation inside the Dispatcher that calls Tools::switchLanguage and change the language for the front. 

Can you just double check that this is fixed?

**Comment by ghost** [comment]
1.7.7 Context Language multistore NOT FIXED
