### ISSUE TITLE
Error when upgrading from 1.7.4.x and previous to 1.7.7.0 Stable 2 Build

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#22141]
#### Describe the bug

Using 1 click upgrade module, there is an error when upgrading from 1.7.4.4 to 1.7.7.0 Build Stable 2. This happens with fresh install, and with PHP 7.1 and 7.2.
The autoupgrade module version used is v4.10.1.
Upgrade from 1.7.3.3 to 1.7.7.0 is KO.
Upgrade from 1.7.4.2 to 1.7.7.0 is KO.

Upgrade 1.7.4.4 to 1.7.6.9 is OK.

This was reproduced by @khouloudbelguith and @sarahdib .

#### Expected behavior

Upgrade should be fine.

#### Steps to Reproduce

1. Install 1.7.4.4 version of PrestaShop (the bug also happens with 1.7.4.2 version and probably all 1.7.4 versions)
2. Upload autoupgrade module (v4.10.1)
3. Make the upgrade using "Local Archive" and the 1.7.7.0 Stable 2 Build
4. There is the following error during the upgrade

```
[INTERNAL] /projet/1744/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Improve\AddonsStoreController" in file "/projet/1744/src/PrestaShopBundle/Controller/Admin/Improve/AddonsStoreController.php" while importing services from resource "/projet/1744/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /projet/1744/app/config/config.yml (which is being imported from "/projet/1744/app/config/config_prod.yml"). 
#0 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/projet/1744/ap...', NULL, false, '/projet/1744/ap...') 
#1 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/projet/1744/ap...') 
#2 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/projet/1744/ap...') 
#3 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/projet/1744/ap...', NULL) 
#4 /projet/1744/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/projet/1744/ap...') 
#5 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) 
#6 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() 
#7 /projet/1744/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#8 /projet/1744/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot()
#9 /projet/1744/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
#10 /projet/1744/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 
#11 /projet/1744/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#12 /projet/1744/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#13 {main}
```

**Screenshots**

https://drive.google.com/file/d/1KVuPaRsvJS368giDjj9c70gML_SMxbrm/view

#### Additional information

* PrestaShop version: presta1770stable2
* PHP version: 7.1 and 7.2

**Comment by PierreRambaud** [comment]
We found the source of the problem, it's because of this pull request: #18475

The previous version had controllers that are now removed or moved to a new directory. In my case, it's the `PrestaShopBundle\Admin\ModuleController` which is not available.
The block trying to auto-wire controllers is fetching the whole directory in `src/PrestaShopBundle/Controller/*` with a `glob`, the controller is not available because not register in the autoloader and we provide an optimize composer autoload.

Two possible solutions:
  - Remove an optimized option for the composer to keep the fallback usage.
  - Use whitelist instead of a glob and register all our controllers manually

**Comment by jolelievre** [comment]
I'd go for the quick fix to patch the 177 build (disable `classmap-authoritative` when building composer autoload)

It should also fix other issues when a shop has been modified and other controller and services have been added (but are not mapped) And it has few to none drawback since it only slows down the autoload when the class is not found in the static classmap

**Comment by PierreRambaud** [comment]
I confirm removing the `classmap-authoritative` make it works

**Comment by matks** [comment]
Sadly it seems the issue cannot be detected by autoupgrade CLI tests https://travis-ci.com/github/matks/autoupgrade/builds/204985933

(or it's fixed in `1.7.7.x` and not in build because this test uses latest 1.7.7.x nightly build)

**Comment by Progi1984** [comment]
Fixed by #22146

**Comment by bullmade** [comment]
The fix has not solved the issue, and the issue is still persistent when trying to upgrade from 1.6.4.2 to 1.7.7.0 with the latest version of the updater module.

**Comment by SimonGrn** [comment]
> The fix has not solved the issue, and the issue is still persistent when trying to upgrade from 1.6.4.2 to 1.7.7.0 with the latest version of the updater module.

Hello @bulldesign 
1.6.4.2 is not a valid version number, could you give us your version please ?

Also, you posted in this thread, but are you absolument certain you have exactly the same error ?

Thank you.

**Comment by bullmade** [comment]
@SimonGrn oh yea, sorry, obviously i meant 1.7.4.2. :) 

Yes, we are getting the exact same error that the that Robin is getting.

**Comment by bullmade** [comment]
We also tested: Upgrading from 1.7.4.2. to 1.7.6.9 is working, and only upgrading to 1.7.7.0 was not.
Even upgrading from 1.7.6.9 to 1.7.7.0 gave the same issue.

Also our enviroment is 7.1, and we have tried with 7.0 and 7.2.

**Comment by idefax** [comment]
I can confirm that I get exact same error messages as Robin does.

I use PHP 7.2, 1Click upgrade module 4.11.0 and I did try to upgrade from 1.7.6.9 to 1.7.7.0.

It's a native PS installation = without any 3rd party modules and using Classic theme.

**Comment by bullmade** [comment]
Yes, im getting it still aswell. Could someone put some attention to the issue?

**Comment by idefax** [comment]
I'm glad I'm not the only one who can reproduce it :)

I did retry a few more times and all the time I still get this error.

Note/reminder for the devs: It's **1.7.6.9** to **1.7.7.0** as well as to **1.7.7.1**

BTW: They closed this issue... If I add a new issue they remove it because of duplicate. So I have no idea of how to get help.

**Comment by cocolate13** [comment]
Hi, I have the same error.
Autoupgrade Prestashop 1.7.6.7 to 1.7.7.1. PHP version 7.3.20. 1clickUpgrade v4.12.0.
All my modules are updated (before launch upgrade). All are green on the upgrade page.
I am the following error (like @Robin-Fischer-PS). I read lots of issue on github/prestashop and I don't find the solution.

`[INTERNAL] /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/home/barthele/www/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/home/barthele/www/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /home/barthele/www/app/config/config.yml (which is being imported from "/home/barthele/www/app/config/config_prod.yml"). #0 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/home/barthele/...', NULL, false, '/home/barthele/...') #1 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/home/barthele/...') #2 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/barthele/...') #3 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/barthele/...', NULL) #4 /home/barthele/www/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/barthele/...') #5 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /home/barthele/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/barthele/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /home/barthele/www/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/barthele/www/admin****/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

(Excuse-me for my bad englich)
Thanks in advance.

**Comment by matks** [comment]
Hi @bulldesign @cocolate13 @idefax 

As explained in the top comment, @Robin-Fischer-PS  was able to see the error message `Expected to find class "PrestaShopBundle\Controller\Admin\Improve\AddonsStoreController" in file "/src/PrestaShopBundle/Controller/Admin/Improve/AddonsStoreController.php" while importing services from resource` when doing these steps:

1. Install 1.7.4.4 version of PrestaShop
2. Upload autoupgrade module v4.10.1
3. Make the upgrade using "Local Archive" and the 1.7.7.0 Stable 2 Build
4. See the error

This error, _and this one exactly_, has been solved by https://github.com/PrestaShop/PrestaShop/pull/22146. The one reported by @Robin-Fischer-PS, with the specific settings of his environment, with the specific conditions of his test.

> Yes, we are getting the exact same error that the that Robin is getting.

It's not because you see the same error message than the root issue is the same. Also we have identified one issue, that led Robin observe the error message, and we traced the issue to a root cause that we have fixed. There might be _other issues_ that lead to the _same error message_. It's not because you see the same error message than it is the same bug 😄 . It can be, but until proven, it's not.

So please understand that until proven otherwise by an exploration of a developer or a QA analyst, you are actually talking about _other issues_ 😉 . You are observing, on your shop, another bug than https://github.com/PrestaShop/PrestaShop/issues/22141. Issue 22141 is fixed, and there are other issues that need to be fixed as well.

Please create new bug reports for the unresolved issues. This issue, this one, has been identified and solved. We cannot explore, identify then fix issues if the bug reports are mixed together in a single github issue. We need 1 bug = 1 github issue.

Also remember that PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. Do not just wait "for PrestaShop maintainers to fix it". It's a community project, it works because everybody puts efforts into it. The most important thing is to share these efforts (not keep them to yourself) with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by cocolate13** [comment]
Thanks a lot. I'm very aware that this is an opensource project  and it's based on people free involvment. This is a very great and usefull software ! I'm going to try to upgrade again with PHP 7.2 (answer from support #23257 ) - I'm currently with PHP 7.1.
Have a nice day.

**Comment by dulismo** [comment]
Hello @cocolate13 , how did your prestashop upgrade go with PHP 7.2 ?

**Comment by cocolate13** [comment]
Hello,
I have to scheduled this update with backups before the next week.
Thanks for your mail.

**Comment by charlie404** [comment]
Good morning all,

I have exactly the same problem.

I tested all the methods and all versions, impossible to update Prestashop.

I still have the same error message.

`[INTERNAL] /**********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/**********/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/**********/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /**********/app/config/config.yml (which is being imported from "/**********/app/config/config_prod.yml"). 
#0 /**********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/homepages/2/d6...', NULL, false, '/homepages/2/d6...') 
#1 /**********/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/homepages/2/d6...') 
#2 /**********/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/homepages/2/d6...') 
#3 /**********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/homepages/2/d6...', NULL) 
#4 /**********/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/homepages/2/d6...') 
#5 /**********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) 
#6 /**********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() 
#7 /**********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#8 /**********/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() 
#9 /**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() 
#10 /**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 
#11 /**********/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#12 /**********/coucouadmin/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#13 {main}`

@ cocolate13, can you tell me if you managed to update?

Thank you

**Comment by cocolate13** [comment]
Hello,
I scheduled this update again, next week if I have time enough. If you
manage to solve this problem, please, tell me how do you process.
I think PHP7.1 (PHP platform version during the first update) is not the
problem...
I would like to know, too, how to continue manually this updated after this
error, instead of restoring some backups.
Thanks in advance.

Le jeu. 25 févr. 2021 à 14:46, Charlie404 <notifications@github.com> a
écrit :

**Comment by cocolate13** [comment]
Did you open ticket on github ?

Le ven. 26 févr. 2021 à 08:35, Laurent Lathus <laurent.lathus@gmail.com> a
écrit :

**Comment by cocolate13** [comment]
Hello all,
I still can't upragde from 1.7.6.9 to 1.7.7.4. I tried lots of methods : 
- manual unzip file in directory and execute upgrade/upgrade.php
- manual unzip all files an copy/paste in the prod directory and execute upgrade/upgrade.php
- upgrade from to 1.7.7.0, next .1, next .2, next .3, etc, always same error
Strange thing : src/PrestaShopBundle/Controller/Admin/Sell/index.php is empty on prod server 1.7.6.9, is that normal ?
@PierreRambaud : is the fix available ? I don't understand well history of ticket #23964
Thanks a lot.
Is there a way to do a fresh install in 1.7.6.9, import all date from my 1.7.6.9 and try upgrade ?

**Comment by cocolate13** [comment]
I see lots of pepole who havethis error on forums and no one have a solution :-(
Thnaks a lot

**Comment by cocolate13** [comment]
UP. An error message that confirm src/PrestaShopBundle/Controller/Admin/Sell/Address/index.php is empty but why is it empty ?
![image](https://user-images.githubusercontent.com/79048790/120478293-fceb4380-c3ac-11eb-992a-a605168e9df1.png)

**Comment by cocolate13** [comment]
And always this error while executing install/upgrade/upgrade.php in web brownser :

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\Address\index" in file ".../src/PrestaShopBundle/Controller/Admin/Sell/Address/index.php" while importing services from resource ".../app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource. in .../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:157 Stack trace: #0 .../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(57): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('PrestaShopBundl...', '/home/.../...', '/home/.../...') #1 .../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(578): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\D in .../vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 168`

**Comment by cocolate13** [comment]
I have just succeed upgrade from 1.7.6.9 to 1.7.7.4.
I deleted these files after copying 1.7.7.4 files and before execute upgrade.php manulay :
rm -rf src/PrestaShopBundle/Controller/Admin/Sell/Address/index.php
rm -rf src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/index.php
rm -rf src/PrestaShopBundle/Controller/Admin/Sell/index.php
rm -rf src/PrestaShopBundle/Controller/index.php
I hope it was very usefull for all !

**Comment by pafoscan** [comment]
It is still not working. I can`t upgrade to 1.7.7 and above. Using 1 click update can only upgrade from 1.7.6.3 to 1.7.6.9. When cen we expect to fix this issue?

**Comment by cocolate13** [comment]
Hi,
Delete theses files before upgrade :

rm -rf src/PrestaShopBundle/Controller/Admin/Sell/Address/index.php

rm -rf src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/index.php

rm -rf src/PrestaShopBundle/Controller/Admin/Sell/index.php

rm -rf src/PrestaShopBundle/Controller/index.php

Do upgrade. Enjoy.

**Comment by pafoscan** [comment]
But form current version or from new version (zip file)?
Thanks

**Comment by cocolate13** [comment]
From current prod version, delete theses file. After, apply upgrade with
1-click upgrade module.
You can see that these files are empty...
