### ISSUE TITLE
Installation keeps failing at 67% on Install Addons Modules - 1.7.7.0

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#22260]
#### Describe the bug
It is not mine first installation, this time I wanted to test 1.7.7.0 so I'm trying to install in a subdomain on a quite powerful server running PHP 7.3. Tested with phppsinfo, all green. Installation keeps failing at 67% on Install Addons Modules.

 If it is a clean installation, why errors? Any ideas please?

#### Expected behavior
The installation goes with no errors

#### Steps to reproduce 

1. Download PS1.7.7.0 from the officiel [site](https://www.prestashop.com/fr/versions-precedentes)
2. Install the shop
3. See error

_**PS: I use MariaDB and Cloudflare DNS on my VPS, could this be the problem? But even if I set Proxy status to DNS only, it is still failing to install.**_

#### Screenshots

![error](https://user-images.githubusercontent.com/31688689/101275833-166a5480-37a9-11eb-9d1b-0045aedabea5.png)

In var\logs\prod.log I see these errors:
```
[2020-12-05 09:24:47] app.ERROR: The addon with id 29992 does not have name. [] []
[2020-12-05 09:24:49] app.ERROR: Cannot register tab "AdminLinkWidget" because it already exists [] []
[2020-12-05 09:25:07] app.ERROR: The addon with id 29992 does not have name. [] []
```
#### Additional informations

- **PS version:** 1.7.7.0
- **PHP version:** 7.3
- MySQL version: 10.4.17-MariaDB. 

Also here's my php.ini:
```
allow_url_fopen = On
allow_url_include = Off
display_errors = On
enable_dl = Off
file_uploads = On
max_execution_time = 1800
max_input_time = 600
max_input_vars = 10000
memory_limit = 1024M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/tmp"
upload_max_filesize = 128M
zlib.output_compression = On 
```

**Comment by tklivan** [comment]
app.ERROR: The addon with id 29992 does not have name

What error is this. I am getting this now.

**Comment by tklivan** [comment]
I raised this in #22265 but was closed citing database performance. But I have the same error as yours and my DB is on AWS and running at 1% load.

**Comment by matks** [comment]
Hi, I think `app.ERROR: The addon with id 29992 does not have name` is not responsible for the issue. It's a warning about a module that has incomplete configuration but that is not supposed to stop the install.

There must be something else that creates the issue 😞 

I just tested and I can install PS 1.7.7.0 without issues

**Comment by mrabsinthe** [comment]
I'm trying to install on a server where I'm already running two instances of PS. 
Not sure if this helps, but I'm using MySQL version: 10.4.17-MariaDB. Also here's my php.ini:
allow_url_fopen = On
allow_url_include = Off
display_errors = On
enable_dl = Off
file_uploads = On
max_execution_time = 1800
max_input_time = 600
max_input_vars = 10000
memory_limit = 1024M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/tmp"
upload_max_filesize = 128M
zlib.output_compression = On 

Also, using Cloudflare DNS, just for the info.

Seems like the error doesn't tell us much:

![error](https://user-images.githubusercontent.com/31688689/101275833-166a5480-37a9-11eb-9d1b-0045aedabea5.png)

**Comment by matks** [comment]
The error `app.ERROR: The addon with id 29992 does not have name` is fixed so it should not annoy anymore.

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 

Thanks @matks for your quick replies and fix :wink: 

@mrabsinthe Could you please check if you can install PS1.7.7.0 without problem. 
Waiting for your feedback.

Thanks!

**Comment by mrabsinthe** [comment]
Hello,
it is still the same I'm afraid, error 404. No errors in prod.log. In the meantime, I managed to install PS with the same host on a shared! server and no issues. The only difference I can think of (apart from the performance), is that I use MariaDB and Cloudflare DNS on my VPS, could this be the problem? But even if I set Proxy status to DNS only, it is still failing to install.

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 

Thanks for your feedback!
Ping @matks @atomiix @jolelievre I think these details may help you :sweat_smile: 

Thanks for your hard working :smile:

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 

I just edit your issue description. Cloud please confirm all details and infos are correct?
**Please next time follow our template to report a complete bug report.**

Thanks!

**Comment by mrabsinthe** [comment]
It is correct, I hope that someone will figure it out.

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 

Well, I didn't manage to reproduce your issue.
But, could you please increase your **upload_max_filesize** to **512M**
And, check your connection, cause this issue only occurs when the connection is slow.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by pshashipreetham** [comment]
I am getting the same Error at 67%
![image](https://user-images.githubusercontent.com/42883804/125635681-d1d09225-1c03-498e-9cb7-940bcfb9575c.png)

what does **"1: Error sent by Addons. You may need to be logged."** mean and how to solve it?

**Comment by hibatallahAouadni** [comment]
Hello @psp316r 

> what does **"1: Error sent by Addons. You may need to be logged."** mean and how to solve it?

It means you have low connection :wink:

**Comment by pshashipreetham** [comment]
Hi @hibatallahAouadni, 

Been Trying for a Long time, it's the same issue I am facing...
![image](https://user-images.githubusercontent.com/42883804/125644241-692e9a62-fe72-4b05-8479-73d5641396a3.png)

**Comment by hibatallahAouadni** [comment]
@psp316r that's weird :confused: try another fresh install

**Comment by tim-pushak** [comment]
I have the same thing, 67% and that's all. Interesting that I installed Prestashop web site, a few days ago, and now i try to install another. I have no idea, why it doesn't works. I doing exactly like previous installation.

**Comment by matks** [comment]
It might be interesting to look at your PHP error logs and webserver error logs.

In some situations, modules installation can be slow, and the install process reaches the php timeout or the webserver timeout (usually it's 30 seconds or 60 seconds, depends on hosting environment). You would see it in the error logs

Example with apache - fastcgi
```

[Wed Jul 07 21:04:15.751759 2021] [fastcgi:error] [pid 8481:tid 140595955693312] [client 172.17.0.1:61280] FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: idle timeout (30 sec), referer: http://localhost:8888/install-dev/index.php?restart=true
[Wed Jul 07 21:04:15.751858 2021] [fastcgi:error] [pid 8481:tid 140595955693312] [client 172.17.0.1:61280] FastCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/php5-fcgi", referer: http://localhost:8888/install-dev/index.php?restart=true
```

**Comment by diezsiete** [comment]
the problem has to do with the ps_metrics module which on installation downloads the ps_accounts module. This download is done through the CsaGuzzleBundle whose default configuration has a 5 seconds timeout. Increasing this timeout solved the problem and the installation of PrestaShop finished successfully

```
# app/config/config.yml  
csa_guzzle:
    ...
    clients:
        addons_api:
            config:
                ...
                defaults:
                    timeout: "60.0"

**Comment by ManuelOscar** [comment]
![Captura de pantalla 2021-07-25 192921](https://user-images.githubusercontent.com/87954288/126918576-69cc8a47-fd2d-42bc-b75d-f91bd084c8b9.png)
esta es la solución aumentar el tiempo de espera

**Comment by Magnusvb** [comment]
Anyone found a solution for this? I have tried with increasing the memory_limit (php.ini) and the timeout for csa_guzzle. But the installation always stops at 67%

I'm trying to install version 1.7.7.5

**Comment by hibatallahAouadni** [comment]
Hello @Magnusvb 

I tried with @SD1982 to reproduce the issue but we couldn't, the install is done without any problem.
We install PS1775 with PHP7.3 and MariaDB, the **install Addons modules** step is completed successfully.
See the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/127338660-50de9478-d868-49e6-8576-7ea05c0e7de2.png)

Thanks!

**Comment by matks** [comment]
The issue is linked to a specific environment setting. Could be memory, timeout, disk space... until we find out what is the bottleneck this issue will not be solved.

**Comment by Magnusvb** [comment]
Thanks!
Installation is now successful. The problem was a timeout with fastCGI.
I'm using Mamp Pro 6, and to solve the timeout, one must Xdebug.

**Comment by RobertRaul** [comment]
Yo tenia el mismo problema de instalación con la versión 1.7.7.5, actualice PHP a 7.4 y Mysql a MariaDB 10.2, reinstale todo y funciono correctamente.

I had the same installation problem with version 1.7.7.5, I had to update PHP to 7.4 and Mysql to MariaDB 10.2, reinstalled everything and it worked correctly.

**Comment by TimexPeachtree** [comment]
I have been using IIS 10 with **PHP via FastCGI** had resolved the issue by increasing IIS->Server->FastCGI Setting -> php-cgi.exe Edit ->  **Activity Timeout** to 180  and **Request Timeout** to 300

**Comment by hentaro** [comment]
In my case the problem was in nginx config from prestashop site
https://devdocs.prestashop-project.org/1.7/basics/installation/nginx/
I changed the timeout settings from 30s to 60s:
fastcgi_read_timeout **60s**;
fastcgi_send_timeout **60s**;
and after that the installation completed successfully!
(Before that I changed my php timeout settings but it didn't help)
