### ISSUE TITLE
Pagination is not working on Product Quick Navigation Popup 1.7.7

### ISSUE THREAD

**Issue by agroundworld** [PrestaShop/PrestaShop#22278]
#### Describe the bug

After upgrading from 1.7.6.9 to 1.7.7.0, the pagination on the quick navigation popup no longer works.  In 1.7.6.9 when I scrolled to the bottom of navigation screen I could use the pagination to move to the next page of products.  This is now not available.  Screenshot attached.

#### Expected behavior

Ability to paginate on larger product lists

#### Steps to Reproduce

1. Go to 'Products'
2. Click on any product
3. In the upper right-hand tool bar select 'Product List'
4. The Product List will pop-up.  Scroll to the bottom.  If you have more than 100 Products, previous versions would allow for Pagination to occur from the Quick Navigation list.
5. The Pagination is missing.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/75636570/101390109-f2ca0b80-3887-11eb-998d-e07acb06524f.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @agroundworld 

I managed to reproduce the issue with PS1.7.7.0 fresh install and PS1.7.6.9 upgraded to PS1.7.7.0, see attached screen records below:
- **1.7.6.7:**
https://drive.google.com/file/d/1Ca0-URxHSH4G-UZF8AGXPUOXCVvM7phd/view

- **1.7.7.0 (fresh install):**
https://drive.google.com/file/d/1YByK2_7qLyN-6e0NT6pmsfx1J8-8uHgf/view

- **1.7.6.9 upgraded to 1.7.7.0:**
https://drive.google.com/file/d/1AyfCN0dy6amQQmGRD_M8BhtqMT83oHSq/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by Progi1984** [comment]
Fixed by #22406

**Comment by agroundworld** [comment]
I applied the fix to the file and it is still not working for me.  Any suggestions? Sent from Mail for Windows 10 From: Progi1984Sent: Tuesday, December 15, 2020 2:13 AMTo: PrestaShop/PrestaShopCc: agroundworld; MentionSubject: Re: [PrestaShop/PrestaShop] Pagination is not working on Product Quick Navigation Popup 1.7.7 (#22278) Closed #22278.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
