### ISSUE TITLE
One-time discounts are not checked again when you log in at the checkout page.

### ISSUE THREAD

**Issue by dbalas** [PrestaShop/PrestaShop#23191]
#### Describe the bug

Discounts are not checked again when you log in at the checkout page. If you apply a one-time discount, which you have already used, before logging in, and then log in at checkout, it remains active.

#### Expected behavior

When you log in on the checkout page the discounts must be checked and removed if they do not meet the conditions.

#### Steps to Reproduce

1. Add some products to cart
2. Apply discount code
3. Log in at checkout page
4. Finish checkout
5. Log out
6. Add some product to card
7. Apply discount page
8. Log in at checkout page
9. Finish checkout when same discount applied

but

1. Log In
2. Add some products to cart
2. Apply discount code
3. You can't apply it because it's already used

**Screenshots**

![image](https://user-images.githubusercontent.com/1343562/107374642-1a3b8f80-6ae8-11eb-871d-a13ba488449b.png)
![image](https://user-images.githubusercontent.com/1343562/107374752-38a18b00-6ae8-11eb-9e08-c80e11e1df27.png)
![discounts](https://user-images.githubusercontent.com/1343562/107376329-0e50cd00-6aea-11eb-9220-7e9ddf859e65.gif)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @dbalas 

I reproduced the issue with PS1.7.7.0 but it seems has been fixed with PS1.7.7.1, cause I didn't manage to reproduce it.
See the attached screen record below:

https://drive.google.com/file/d/1AgU-Da22yp3pyXPeSyKCtRyQKvuvG9L-/view

I close this issue cause it's fixed :wink: 

Thanks!

**Comment by dbalas** [comment]
@hibatallahAouadni I have tried 1.7.7.1 and it still does not work, and I have found why you do, it only happens with the second order of a new user. Maybe something related with the usage count?

**Comment by hibatallahAouadni** [comment]
@dbalas Could you please provide a screen record. Thanks!
