### ISSUE TITLE
BO - Dashboard Date, compare period can't be selected

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#23302]
#### Describe the bug

On the dashboard, when selecting a date, and checking the checkbox for compare, the period selector for the period to compare to is disabled and don't change to enabled, so it is not possible to compare two periods.

#### Expected behavior

When checking the checkbox for compare, the selector for selecting a period should be enabled so the user can select what period to compare to.

#### Steps to Reproduce

1. Go to admin dashboard.
2. Click on the date selector.
3. Check the checkbox for compare.
4. Try to select compare period.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @Prestaworks ,

I was able to reproduce the issue with PrestaShop version 1.7.7.1 and PS 1.7.6.9.
We should be able to choose an element in the dropdown like so (PS 1.7.5.2):
![Capture d’écran 2021-02-19 à 10 23 58](https://user-images.githubusercontent.com/16019289/108484916-a8f49d00-729c-11eb-873b-cb2003d365be.png)


I’ll add this to the debug backlog so that it’s fixed.

Thank you for your PR.

**Comment by florine2623** [comment]
@Prestaworks 
This issue is fixed in https://github.com/PrestaShop/PrestaShop/issues/22973, PS version 1.7.7.2

I'll close this issue.

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22973

**Comment by Webbrent** [comment]
This problem persists even though upgraded to the 1.7.2.2 version of Prestashop.

**Comment by cyrillg77** [comment]
Same problem in Prestashop 1.7.8.4
