### ISSUE TITLE
 search engine does not find any product

### ISSUE THREAD

**Issue by delecluse** [PrestaShop/PrestaShop#23334]
Hello, my site search engine is no longer working, it can no longer find anything ...

I've already done that :

- Add missing products to the index
 - Rebuild the index
- You can define a cron job that will rebuild your index using the following URL:

I have cleared the site cache + my cookies and search engine file

but nothing helps .. to peter a cable

Type of installation (new / updated):
PS Version: 1.7.7.1
URL of the site concerned: www.newmart.fr
Theme (default / custom): Zone theme
Hosting: clouding host
PHP version: 7.1.33
MySQL version: 5.7.33
Browser (s) concerned: opera

Thanks to what can help me

Thibault

**Comment by hibatallahAouadni** [comment]
Hello @delecluse 

I didn't manage to reproduce your issue with PS1.7.7.1 on Opera browser and it seems your issue is not related to PS Core. Could you please switch your theme to the default theme and check if the search works or no?
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
I have similiar issue after upgrading from PS 1.7.6.8 to 1.7.7.2. After the upgrade, my search results are cut by a factor of 10 or even more in some cases.

I noticed something interesting. On 1.7.6.8 when i search for example "red apple" the prestashop will find products with "red apple" but also with only "red" or only "apple". But if I try to search same thing on 1.7.7.2 it searches for "red apple" only and I can't find any place in BO to change this behaviour. I tried everything I can, rebuilding indexes, change search settings, but it didn't help at all.

I don't know if it is the same case as yours, but for now, I rolled back my store to 1.7.6.8.

**Comment by hibatallahAouadni** [comment]
Hello @Anidatte 

> But if I try to search same thing on 1.7.7.2 it searches for "red apple" only

Did you get any result?

**Comment by ghost** [comment]
> 
> 
> Hello @Anidatte
> 
> > But if I try to search same thing on 1.7.7.2 it searches for "red apple" only
> 
> Did you get any result?

It depends on the search query, sometimes I've got nothing, sometimes I've got 10 products, where on the 1.7.6.x it was more than 200. The worst thing is there's nothing I can do with it, except for a rolling back to older version.

**Comment by delecluse** [comment]
It’s good, resultat it’s resolu 😊

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@delecluse so your problem has been solved? 
If so, could you please share what you have done to fix it, it may help @Anidatte 

Thanks!

**Comment by ghost** [comment]
I think it's not solved (sadly...) I don't know if it's bug or feature, but in my case it looks like intended behaviour of search engine, but I don't know, why there's no option to enable search by any word just like in the previous versions of PS 1.7.x. In my case, it doesn't work "bad"... but it's different. I wish I could just have an option to enable search by any word typed in the search box. But there's none (or I can't find it in the BO).

**Comment by hibatallahAouadni** [comment]
Hello @Anidatte 

Could you please attach a screen record showing the issue.

Thanks!

**Comment by delecluse** [comment]
Le problème est résolu merci !

**Comment by hibatallahAouadni** [comment]
Hello @delecluse 

That's great :tada: So, I close this issue cause ih been fixed and it's not related to PS Core.
Thanks for your feedback.

PS: please next time use English :wink: English is the norm on GitHub.

Thanks!
