### ISSUE TITLE
No detection of tags in prestashop

### ISSUE THREAD

**Issue by amanv8060** [PrestaShop/PrestaShop#23888]
#### Describe the bug

I am using prestashop metrics and ps_googleanalytics 4.0.0 . 

i can see the google analytics code in beteween head tags in my frontend 

```
	(window.gaDevIds=window.gaDevIds||[]).push('d6YPbH');
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'mytrackingcode', 'auto');
                        ga('send', 'pageview');
    
    ga('require', 'ec');

```
i can also see data in google analytics
but prestashop metrics shows 
`It looks like no tag has been installed on your store yet. You can configure one easily using our free Google Analytics module. Click here to configure this module.`

Also Ecommerce data is not being recorded 

#### Expected behavior

Ecommerce data should be recorded and prestashop metrics should detect tag

#### Steps to Reproduce

I believe sufficient info already there

**Screenshots**

https://imgur.com/a/tud4Biz

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @amanv8060 

Could you please provide steps to reproduce the issue and your PHP version.
Please check and feedback.

Thanks!

**Comment by amanv8060** [comment]
php version : 7.3.27
Steps to reproduce :
1 ) configure google analytics by prestashop 4.0.0 ,
2 ) install and configure prestashop metrics 1.3.3.
 
 And this problem appears

**Comment by amanv8060** [comment]
Also can't see ecommerce data in google analytics

**Comment by amanv8060** [comment]
i can see ecommerce data now

**Comment by hibatallahAouadni** [comment]
Hello @amanv8060 

> i can see ecommerce data now

How did you fix your issue? Could you please explain the process.

**Comment by amanv8060** [comment]
reconfiguring the analytics module

**Comment by florine2623** [comment]
I close your issue as this is fixed.

**Comment by amanv8060** [comment]
@florine2623 the issue is not resolved , tag is still not being detected
