### ISSUE TITLE
BO - Orders - An exception is displayed when we add a discount with space in the name 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24537]
#### Describe the bug
In the BO > Orders > Order view page, when we add a discount with space ` ` in the name, an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/118530472-fc17a800-b744-11eb-9ef2-76ea53c79541.png)

#### Expected behavior

In the PS1769 => no exception
![image](https://user-images.githubusercontent.com/16067358/118530610-223d4800-b745-11eb-9db6-f7c77e3faf35.png)

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. View any order
3. Add a discount 
4. In the Name field, set a space ` `, and a value discount
5. Click save
6. See error

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2,7.4

**Comment by MatShir** [comment]
Since the migration of the form, we don't accept empty field anymore.

**Comment by Progi1984** [comment]
@MatShir A space is not empty ;)

**Comment by MatShir** [comment]
You are right aha ! I mean empty or just spaces :)

**Comment by Progi1984** [comment]
@MatShir So we need to avoid empty string. I will block the submit button if the name is empty or just spaces.

**Comment by PululuK** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/24565

**Comment by khouloudbelguith** [comment]
Hi!

The issue is still reproduced with PS1775 build1 and 177x branch.
https://drive.google.com/file/d/1RPGenM18kD3TMb0i1dUOfC_0gUquis5x/view?usp=sharing
I will re-open the ticket.

Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith Could you check it on `1.7.7.x` branch ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Yes, it is ok :heavy_check_mark: 
https://drive.google.com/file/d/1X2rW3uPbl2ibmYrIZNLeFFYrOx7XrKQ_/view?usp=sharing

Thank you!
