### ISSUE TITLE
SQL Manager SQL Form throws FatalThrowableError - Type Error on JOIN SQL query (but works with simple SELECT)

### ISSUE THREAD

**Issue by DevWL** [PrestaShop/PrestaShop#25011]
#### Describe the bug

SQL Manager throws Fatal Error when trying to run complex query with JOIN.

```
Error:
Type error: Argument 1 passed to PrestaShop\PrestaShop\Adapter\SqlManager\SqlQueryValidator::getFromKeywordError() must be of the type array, bool given, called in ...\src\Adapter\SqlManager\SqlQueryValidator.php on line 88
```

#### Expected behavior

It should take the SQL query and save it so it can be run later on.
It works in PhpMyAdmin without any issue
![image](https://user-images.githubusercontent.com/4503417/122487265-2629e780-cfdb-11eb-88d3-94abec18a267.png)

#### Steps to Reproduce

1. Go to 'SQL Manager'
2. Try to save this query:
`SELECT MAX(o.date_add), COUNT(o.id_order), SUM(o.total_paid_tax_incl), c.id_customer, c.firstname, c.lastname, c.email, c.last_passwd_gen, c.newsletter_date_add, c.date_add, c.date_upd FROM ps_customer c LEFT JOIN ps_orders o ON c.id_customer = o.id_customer GROUP BY c.id_customer;`
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/4503417/122486955-5f158c80-cfda-11eb-8133-d62d3546a31f.png)
![image](https://user-images.githubusercontent.com/4503417/122486991-718fc600-cfda-11eb-96cf-badf6d2d284b.png)

#### Additional information

Simple select from single table works fine (green markup). Adding red markup will trigger the error:
![image](https://user-images.githubusercontent.com/4503417/122488607-16f86900-cfde-11eb-9ccb-bd3ec61f14a4.png)

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.28

**Comment by florine2623** [comment]
Hello @DevWL ,

I was able to reproduce the issue with PrestaShop version 1.7.7.5, 1.7.8 and develop, so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @DevWL 

Thanks for reporting this issue!
I didn't manage to reproduce the issue with PS1.7.6.7, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/122824617-3692d880-d2e1-11eb-9ed9-0060d74fd728.png)

I only reproduced with PS1.7.7.5 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/122824812-6d68ee80-d2e1-11eb-822b-aca6f4abcd3f.png)

It's a regression! ’ll add this to the debug backlog so that it’s fixed.

Thanks!

**Comment by Progi1984** [comment]
Fixed in #25106 by @Progi1984

**Comment by angerangel** [comment]
I have **1.7.8.6** and bug still persist. I can't add complex SELECT query to the SQL manager. I got always:

`Type error: Argument 1 passed to PrestaShop\PrestaShop\Adapter\SqlManager\SqlQueryValidator::getWhereKeywordError() must be of the type array, boolean given, called in /var/www/html/presta17/src/Adapter/SqlManager/SqlQueryValidator.php on line 92
[Symfony\Component\Debug\Exception\FatalThrowableError 0]`
