### ISSUE TITLE
Product V2 Page - Exception when associated file name in  virtual product is empty 

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25315]
#### Describe the bug

On Product V2 Page, when adding an associated file to a virtual product, if the Filename field is empty, an exception is displayed when saving. This can happen a lot since the filename is not pre-filled in Product V2 Page.

#### Expected behavior

Two behavior should be implemented on associated file form of Product V2 page : 
- When the filename field is empty and the user try to save the settings, an error should be displayed on the field, as in Product V1 Page : 
![product V1 associated file empty](https://user-images.githubusercontent.com/55688534/125235527-e35de580-e2e2-11eb-8fcc-3795c5fd18a7.png)

- When uploading a file, the name of the file should be used to fill the "Filename" field, as in Product V1 Page : 
![product V1 associated file prefilled](https://user-images.githubusercontent.com/55688534/125235700-2a4bdb00-e2e3-11eb-83ca-47a09e6f684e.png)

#### Steps to Reproduce

0. Go to Advanced Parameters > Experimental features : Enable Experimental product page
1. Go to Catalog > Products : Edit a virtual product on experimental page
2. Go to Virtual product tab, Set "Does this product have an associated file?" to "Yes"
3. Upload a file, and without filling the "FIlename" field, save the product
4. See exception

**Screenshots**

Filename empty : 
![virtual product file no name](https://user-images.githubusercontent.com/55688534/125235351-9d088680-e2e2-11eb-84cc-f4002e53148c.png)

Exception : 
![virtual product file no name exception](https://user-images.githubusercontent.com/55688534/125235350-9c6ff000-e2e2-11eb-84d3-fb65b1eaf649.png)

#### Additional information

* PrestaShop version: 1.7.8, develop
* PHP version: N/A

**Comment by matthieu-rolland** [comment]
@Robin-Fischer-PS couldn't reproduce this issue on develop, I have the correct error message, maybe it has been fixed already

**Comment by Robin-Fischer-PS** [comment]
@matthieu-rolland I still have the exception : Did you try in debug mode ON, and on a virtual product ? (it works fine on standard product)

**Comment by jolelievre** [comment]
The bug should have been fixed in a previous PR, this should just be checked but I think it can be closed

**Comment by florine2623** [comment]
No more exception, this is fixed on `8.0.x`, `8.1.x` and `develop`.
