### ISSUE TITLE
Actions "free shipping" button in vouchers does not work

### ISSUE THREAD

**Issue by Vitamixlife** [PrestaShop/PrestaShop#25393]
Dears, I know it's not a bug properly so:

1. I've set some carrier rule: free shipping over >98€ amount of cart, and 7€ shipping cost < 98€. That's ok.
2. I create a voucher that has got 25% of discount on chart amount.
3. I need that this voucher makes Carrier cost to zero.
4. In the Vouchers section, under tab "Actions" there is a button "Free Shipping" yes/no, if I switch on it, I mean that climbs over the carrier/rules but it doesn't works so.
So I need that this switch (Free shipping in voucher's actions) overwhelms carrier rules, if not possible why is it available in the settings?

thks you
ps ver 1.7  

![Screenshot 2021-07-21 at 11-49-48 Regole Carrello Modifica ECOMIX25ALL • Vitamix srl](https://user-images.githubusercontent.com/87757765/126473437-7259c17b-9d02-4b9a-8734-5452ceb176a0.png)
#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2.34

**Comment by Vitamixlife** [comment]
> 
> 
> Dears, I know it's not a bug properly so:
> 
>     1. I've set some carrier rule: free shipping over >98€ amount of cart, and 7€ shipping cost < 98€. That's ok.
> 
>     2. I create a voucher that has got 25% of discount on chart amount.
> 
>     3. I need that this voucher makes Carrier cost to zero.
> 
>     4. In the Vouchers section, under tab "Actions" there is a button "Free Shipping" yes/no, if I switch on it, I mean that climbs over the carrier/rules but it doesn't works so.
>        So I need that this switch (Free shipping in voucher's actions) overwhelms carrier rules, if not possible why is it available in the settings?
> 
> 
> thks you
> ps ver 1.7
> 
> ![Screenshot 2021-07-21 at 11-49-48 Regole Carrello Modifica ECOMIX25ALL • Vitamix srl](https://user-images.githubusercontent.com/87757765/126473437-7259c17b-9d02-4b9a-8734-5452ceb176a0.png)
> #### Additional information
> 
>     * PrestaShop version: 1.7.6.9
> 
>     * PHP version: 7.2.34

**Comment by florine2623** [comment]
Hello @Vitamixlife ,

This bug has been fixed in PS 1.7.7.X.
Please check my screen record on my PS 1.7.7.5 :
https://drive.google.com/file/d/1hIc27Mxa_KYWv-KX2vLWRjE_EPSepXxw/view

104.40 * 25%100 + 8.40 = 34.50

I'll close the issue as it is fixed.
Thanks!

**Comment by Vitamixlife** [comment]
Thank you very much @florine2623, but I can't upgrade to 1.7 for some reasons, is it possible to fix this by editing the code?

thks in advance

**Comment by Vitamixlife** [comment]
Dear, 
I've test same situation on a new installation of p.s. 1.7.7.5 but the bug persist.

- Cart Rule: free shipping from 60€ otherwise you pay 7€ of shipping cost.
- Voucher: 15€ discount and "free shipping" switch is on.
- I've a cart with 38€ (2 items), whne I apply the voucher, the cart shows: -22€ discount, shipping free, that's ok!
- 38€ minus 22€ subtotal: 23€ ??? wait: 16€ of course, not 23€.
- something is wrong
- site: bruttosito.com

![immagine](https://user-images.githubusercontent.com/87757765/128541251-e7dd8460-383a-42dc-880d-d3661342a9fd.png)

![immagine](https://user-images.githubusercontent.com/87757765/128541321-55cdc616-8070-4607-abdf-5ecfda5bb728.png)

**Comment by Vitamixlife** [comment]
dear florine, in your video  that's an error:

https://drive.google.com/file/d/1hIc27Mxa_KYWv-KX2vLWRjE_EPSepXxw/view

104,4 - 34,50 makes 78.3??? its 69.9€  (78.3€ its with the shipping cost of 8.4€ calculate but i need free shipping )

**Comment by Vitamixlife** [comment]
Only difference beetwen ver 1.7.6.9 and 1.7.7.5 its voucher mode shows: gratis/free shipping instead the value but the total count of cart its incorrect.
