### ISSUE TITLE
Unable to uninstall native module ps_dataprivacy

### ISSUE THREAD

**Issue by Matt75** [PrestaShop/PrestaShop#25597]
#### Describe the bug

Unable to uninstall native module [ps_dataprivacy](https://github.com/PrestaShop/ps_dataprivacy)

#### Expected behavior

Be able to uninstall native module [ps_dataprivacy](https://github.com/PrestaShop/ps_dataprivacy)

#### Steps to Reproduce

1. Go to Module Manager
2. Click on Uninstall module ps_dataprivacy

**Screenshots**

<img width="289" alt="ps_dataprivacy" src="https://user-images.githubusercontent.com/5262628/129385742-014ead67-5930-4c4b-bc4a-b459625b1eaf.png">

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: PHP 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Matt75 

Thanks for your issue and your PR :rocket: 
I reproduce the issue with `PS1770` and `PS1776` with `PHP 7.2` and `ps_dataprivacy v2.0.1`, see the attached screen record below:

https://drive.google.com/file/d/19ZMZQ3kR5ZF5sbMgPBPHy52OE1CSTEow/view

But I didn't reproduce it with `PS1767`, `PHP 7.2` and `ps_dataprivacy v2.0.1`.
So, it's a **regression**! ’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by ghost** [comment]
Issue closed by https://github.com/PrestaShop/ps_dataprivacy/pull/31

**Comment by hibatallahAouadni** [comment]
Thanks @okom3pom for the tip :wink:

**Comment by hibatallahAouadni** [comment]
Fixed by https://github.com/PrestaShop/ps_dataprivacy/pull/31

**Comment by alfonsolr09** [comment]
the bug is not fixed, please reopen the topic @hibatallahAouadni

**Comment by alfonsolr09** [comment]
I have this problem even having version 2.0.1

Prestasop 1.7.7.3
https://www.awesomescreenshot.com/video/6280974?key=3a7c0711685e27352f2c10e0273e8822

Prestasop 1.7.8.0
https://www.awesomescreenshot.com/video/6281019?key=8bd2711d6efa9e2d1c7caabba93e6bdf

**Comment by alfonsolr09** [comment]
#26844

**Comment by alfonsolr09** [comment]
#26869
