### ISSUE TITLE
After upgrade, theme must be updated to be able to pay into the final step on PrestaShop 1.7.8

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#26274]
#### Describe the bug

Since PrestaShop 1.7.8, a change inside the core.js affect all themes and disallow the possibility of payments inside the checkout.

This issue was introduced with this pull request: https://github.com/PrestaShop/PrestaShop/pull/18904/

As now, the disabled thing is moved on class and not on attribute.
As like every theme have followed the Classic theme about that, if someone update it's PrestaShop without using Classic (and even without update CLassic, as it's possible), it will disallow the payment.

#### Expected behavior

We can add the disabled class, but the remain of disabled attribute into the JavaScript is needed.

#### Steps to Reproduce

1. Install PrestaShop 1.7.7.8
2. Update to PrestaShop 1.7.8.0 without updating Classic theme.
3. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by matks** [comment]
Hi @PrestaEdit and thanks for the bug report !

I changed a bit the title because I dont want people to be confused. We're not talking about something broken here, we're talking about a change in the Core that require Theme developers to update. Don't get me wrong: I'm not saying this is not serious and that it's not a big issue, I just want to make sure title accurately describes the situation.

> Since PrestaShop 1.7.8, a change inside the core.js affect all themes and disallow the possibility of payments inside the checkout.

Same for this 😅 payments are not disallowed inside the checkout. It's rather 'without a change in the theme, some themes* will not be able to perform payments"

*Because not all themes rely on this system

**Comment by matks** [comment]
After looking a bit more into it, I see different ways on how to solve this. I'll wait for my peer maintainers to have a look too and see how it can be solved in a nice and long-term way :) but feel free to also suggest ideas or even a PR of your own.

Thanks again for the bug report ❤️

**Comment by matks** [comment]
Pull Request from @NeOMakinG https://github.com/PrestaShop/PrestaShop/pull/26289

**Comment by starqus** [comment]
As a simple solution, I changed in the old theme file in templates/checkout/partials/steps
payment.tpl
Search 🔎 disable
Change to enabled
Currently working But it's not the exact solution. Theme file needs to be edited

**Comment by NeOMakinG** [comment]
The exact solution is already pushed, you'll get it in the next patch version

**Comment by starqus** [comment]
> The exact solution is already pushed, you'll get it in the next patch version

Could you tell me how you solved it?

**Comment by NeOMakinG** [comment]
@LordIndustry https://github.com/PrestaShop/PrestaShop/pull/26289/files

**Comment by hibatallahAouadni** [comment]
@matks related to https://github.com/PrestaShop/PrestaShop/issues/26171#issuecomment-940186128

**Comment by michaeldebetaz** [comment]
> @LordIndustry https://github.com/PrestaShop/PrestaShop/pull/26289/files

Hi guys ! I'm trying to fix that bug having a theme that seems to depend on those old features. I wanted to already add the solution to my code, but I can't find the "themes/_core/js/checkout-payment.js" file in my theme, or anywhere in fact.

Any tips ?

**Comment by starqus** [comment]
> > @LordIndustry https://github.com/PrestaShop/PrestaShop/pull/26289/files
> 
> Hi guys ! I'm trying to fix that bug having a theme that seems to depend on those old features. I wanted to already add the solution to my code, but I can't find the "themes/_core/js/checkout-payment.js" file in my theme, or anywhere in fact.
> 
> Any tips ?

As a simple solution, I changed in the theme file in templates/checkout/partials/steps
payment.tpl
Search 🔎 disabled
Change to enabled

**Comment by michaeldebetaz** [comment]
Thanks, I saw your workaround above and it is a good one for the time. It's what I actually already did :

##### httpdocs/themes/.../templates/checkout/_partials/steps/payment.tpl
` <button type="submit" {if !$selected_payment_option} disabled {/if} class="btn btn-primary center-block">...`

I removed the conditional rendering "{if !$selected_payment_option} disabled {/if}". But it's not the solution in the js core that should come in the next update, it's just disabling one verification :)

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #26289

**Comment by PascalB67** [comment]
Hi, 
And add: "cb modules not display" (1.7.8.1) same in 1.7.8.0
-> Hook not modifiable.
After update : from 1.7.6

**Comment by oscherler** [comment]
– It’s a patch release;
– It even affects the default theme;
– There’s nothing easily findable about the changes required to themes, or even the requirement to update the default theme (https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/);
– It breaks checkout, which is the most important feature of the whole software.

If that’s not broken, then I haven’t written a bug in my life.

But you’re right, it doesn’t *really* prevent payment. I could place my order in the shop where I’ve been affected by this as a customer: by inspecting the payment button and removing the `disabled` attribute.

**Comment by eternoendless** [comment]
@oscherler to the best of my understanding, the bug has been fixed in 1.7.8.1
Can you please confirm?

**Comment by PhotoSoft** [comment]
> Thanks, I saw your workaround above and it is a good one for the time. It's what I actually already did :
> 
> ##### httpdocs/themes/.../templates/checkout/_partials/steps/payment.tpl
> ` <button type="submit" {if !$selected_payment_option} disabled {/if} class="btn btn-primary center-block">...`
> 
> I removed the conditional rendering "{if !$selected_payment_option} disabled {/if}". But it's not the solution in the js core that should come in the next update, it's just disabling one verification :)

Thx bro!

This bug STILL EXISTS IN 1.7.8.7 you **** presta devs!

**Comment by ghost** [comment]
@PhotoSoft 

If you are the only one to have the bug since the 1.7.8.1, you should ask yourself some questions?

**Comment by PhotoSoft** [comment]
About what? I have only one payment method and here is bug:

> {if ($selected_payment_option == $option.id || $is_free) || **($payment_options|@count === 1 && $module_options|@count === 1)**} checked {/if}

Solution:

> {if ($payment_options|@count === 1 && $module_options|@count === 1)}
> {assign var="selected_payment_option" value="option.id"}
> {/if}

**Comment by PhotoSoft** [comment]
About what? I have only one payment method and here is bug:

> {if ($selected_payment_option == $option.id || $is_free) || **($payment_options|@count === 1 && $module_options|@count === 1)**} checked {/if}

Solution:

> {if ($payment_options|@count === 1 && $module_options|@count === 1)}
> {assign var="selected_payment_option" value="option.id"}
> {/if}

**Comment by ghost** [comment]
What is the problem with one payment?


https://user-images.githubusercontent.com/5064590/184474941-7f2a9254-464f-4060-98e1-db738f552e86.mp4

**Comment by PhotoSoft** [comment]
https://snipboard.io/wPyYMC.jpg

And next f** bug, now with API. Customisation for probably company account isn`t returned by webservice!

OK: https://snipboard.io/S02jK6.jpg
Bug: https://snipboard.io/KZMJ9j.jpg

I`m back to 1.7.7.7 from this bugged version where everything WORKS FINE.

**Comment by kpodemski** [comment]
@PhotoSoft please, calm down, either respect the Code of Conduct of the project or stop commenting on the issues

**Comment by Steppenw** [comment]
I would not like to rekindle controversy but I would like to say that PhotoSoft is not the only one to have encountered the problem in version 1.7.8.7, I am there too.
I also have **only one** payment method and initially, perhaps ignorantly, I had simply commented the line
'{if ($selected_payment_option == $option.id || $is_free) || ($payment_options|@count === 1 && $module_options|@count === 1)}', otherwise the effect would be:
  - the payment method selected but not expanded to fill in the fields
  - obviously the impossibility of deselecting it
  - the 'submit' button deactivated

In doing so I solved it but then I applied the solution proposed by PhotoSoft which, in addition to working, I think is cleaner than mine.
A comment from any contributor would be welcome.
Otherwise thanks anyway.

**Comment by ghost** [comment]
Hello @Steppenw

Can you open [a new issue](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml) with a screen recording, php version, theme .... . As you can see I can't reproduce; with more informations if there is still a bug we should be able to solve it. 

https://user-images.githubusercontent.com/5064590/184474941-7f2a9254-464f-4060-98e1-db738f552e86.mp4

**Comment by Steppenw** [comment]
Hi @okom3pom, unfortunately I'm not very familiar with GitHub yet ...
The PHP version is 7.4.30, the theme used is the 'child_classic' (basically the 'classic' theme), the payment module used is 'Stripe'.
The first screenshot refers to the checkout before the changes to the 'payment.tpl' file (among other things, 'Terms and conditions' is deactivated in the back office and yet an invitation to accept them appears at the bottom).
![Screenshot_1](https://user-images.githubusercontent.com/76645799/184934674-ec10150c-1ea9-4113-8648-f4eb21ee3060.png)

The second screenshot refers to the checkout after adding in the 'child_classic' the 'payment.tpl' file with the above changes (I also 'cut off' the invitation to accept 'Terms and conditions' at the bottom).
![Screenshot_2](https://user-images.githubusercontent.com/76645799/184934826-c05c91bf-45bf-42ed-8e27-986ea8da612b.png)

By selecting the payment method, the form expands, the invitation at the bottom to select a payment method disappears and the purchase takes place regularly.
I add that I am a novice developer, I may have made some mistakes but I think I have acted correctly.

EDIT: @okom3pom, I watched your video carefully.
Actually, if 'Terms and conditions' is active, I don't have any problems either, no modification is necessary.
But I don't want the 'Terms and Conditions' active (on the other hand, it can be deactivated) for reasons related to my client and also because the link doesn't work and I can't solve it (problem that I know others have also encountered).
Are you experiencing the same problem as me by deactivating 'Terms and conditions' and with only one active payment module?

**Comment by ghost** [comment]
Ok, it's an other issue not related to this one.

```
{if ($payment_options|https://github.com/count === 1 && $module_options|https://github.com/count === 1)}
{assign var="selected_payment_option" value="option.id"}
{/if}
```

This code is not a solution because you don't have extra information from the module.

A way is to set 

```
        if (count($paymentOptions) === 1) {
            $this->selected_payment_option = 'payment-option-1';
        }
```

And check before hide `this.additionalInformatonSelector` like :

```
    if (!this.getSelectedOption()) {
      this.collapseOptions();
    }
```

i will open an issue

**Comment by Steppenw** [comment]
Hi @okom3pom, first of all tell me if I can continue writing here or in #29371.
I looked at #29373 and thought I'd test the changes (3 files changed) but my installation doesn't have this path: /themes/_core/js/checkout-payment.js .
The '_core' folder is completely missing: something is wrong with my installation?

**Comment by ghost** [comment]
Plz continue here https://github.com/PrestaShop/PrestaShop/issues/29371
