### ISSUE TITLE
Simple anchors do not work

### ISSUE THREAD

**Issue by Stephane1874** [PrestaShop/PrestaShop#26326]
#### Describe the bug

When I try to link to an anchor on a page, the page refreshes and doesn't stay.

Not easy to explain I hope the video will be clearer :)

#### Steps to Reproduce

1. Created a lot of text on a CMS page
2. Make a link to reach the bottom of the page
`<a href="#id777">Test ancre</a>`
`<p>Text.....</p>`
`<p id="id777">`
4. click on the link and see the error, the page is refreshed and straightened out.

**Screenshots**

https://user-images.githubusercontent.com/46202635/137910770-307466ef-21a3-424c-b654-89977606fbcd.mp4

#### Additional information
* No cache
* Test locally and in production (similar error)
* PrestaShop version: 1.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Stephane1874 

Thanks for reporting the issue!
I reproduce the issue with PS1780 and develop, it's a **regression**! Cause I didn't manage to reproduce the issue PS1778.
I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Stephane1874** [comment]
Hello @alexandrebrubeyonds ,

I tried to apply the changes to the file listing.js of your PR but it doesn't change for me.

Maybe something else needs to be done ?

**Comment by alexandrebru83** [comment]
Hello @Stephane1874, you need to compile assets, clear Prestashop cache from BO and clear browser cache :)

**Comment by Stephane1874** [comment]
Thank you very much @alexandrebrubeyonds, 

I learned today how to compile asset :)

The PR works very well.

**Comment by hibatallahAouadni** [comment]
Ping @Progi1984 Could you please specify this issue status :pray: 
I can see that it has two PRs (one **merged** on `develop` and the other **not merged** on `1.7.8.x`) :confused:

**Comment by Progi1984** [comment]
@hibatallahAouadni the issue is always on todo as we need to backport the fix in 178x.

**Comment by Progi1984** [comment]
Fixed in #26410 by @alexandrebrubeyonds

**Comment by Prestapepe** [comment]
> Ping @Progi1984 Could you please specify this issue status pray I can see that it has two PRs (one **merged** on `develop` and the other **not merged** on `1.7.8.x`) confused

I also see this marked as fixed but just in dev mode. 

How can we make this work in the current prestashop version??

I didnt find a equivalent file.... 

Thanks

**Comment by hibatallahAouadni** [comment]
@Prestapepe this issue has been fixed with the stable version 1.7.8.1

**Comment by Prestapepe** [comment]
No, Its not solved.

I have 1.7.8.3 running and the bug is there.

The solution is [themes/classic/_dev/js/listing.js] and the folder _dev does not exist one the production files. (I guess because is a folder ment for development folder not for production)

Just go to prestashop.com download latest version and try to find the _dev folder.

**Comment by hibatallahAouadni** [comment]
@Prestapepe did you try this fix #26410?

**Comment by Prestapepe** [comment]
Yes that solotion doest apply to producto files,

Thats why im telling...  [themes/classic/_dev/js/listing.js] and the folder _dev does not exist one the production files.

**Comment by Prestapepe** [comment]
@hibatallahAouadni Yes that solution doest apply to production files, 

Thats why im telling... [themes/classic/_dev/js/listing.js] and the folder _dev does not exist one the production files.

**Comment by Prestapepe** [comment]
@hibatallahAouadni 
I have lastets version and It is not solved.

Am I missing something or the solution does not apply to production releases???

I have lastets version and It is not solved.

Thanks!!!

**Comment by hibatallahAouadni** [comment]
Hello @Prestapepe 

Sorry but I can't help you any more as I didn't reproduce the issue :disappointed: 
You can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
