### ISSUE TITLE
Product stock fails when stock is shared in the group on product page v2

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#26738]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On product page v2
- in a multishop scenario
- where you have a Shop group that shares its stock amongst the group (let's call it "Sharing group")
- the product page fails to load when trying to access it with a shop belonging to "Sharing Group"

![Capture d’écran 2021-11-24 à 19 00 39](https://user-images.githubusercontent.com/13801017/143291298-cc86cff5-ee45-467c-b088-810a97545a9a.png)

### Analysis

The query condition to get the StockAvailable are automatically filled with context values for now
The product has no StockAvailable associated for its shop group so no StockAvailable ID can be found and an exception is thrown

### Expected behavior

The problem comes from missing data for group stock, there should be a StockAvailable bound by its groupId

There are two approaches for this bug:

### Correct filling of data

During the shop creation when products are copied the stock available is not copied when the group is the one responsible for stock. See this line:

https://github.com/PrestaShop/PrestaShop/blob/ea657db565709475c488f1a9859f71802c86fd22/classes/shop/Shop.php#L1214-L1219

That's where the missing data comes from. First solution is to handle the creation of this missing data on product creation or when they are copied to another shop via the `CopyProductToShop` command.

This would ensure us the consistency of our data, however we can't be sure that upgrading shop will have this consistency so the bug would remain.

### Be more resilient about StockAvailable

The problem had already risen about this missing StockAvailable even in single shop context, so an alternative solution would be to be more resilient. When the StockAvailable is not detected (regardless of the context) a StockAvailable should be created. Naturally, its quantity would be 0. We will have to handle two cases though:

- the selected shop handles its own stock -> create a StockAvailable associated by shopId
- the selected shop belongs to a group that handles its shared stock -> create a StockAvailable associated by shopGroupId

### Suggested solution

The solution I suggest is a mix:
- the getter should be more resilient to missing data, this can be done by two ways:
  - ignore the missing StockAvailable and use 0 as a fallback quantity
  - detect the missing StockAvailable and create the appropriate one
- the CopyProductToShop command should handle the creation appropriately
- we can't fix all the legacy code especially not the shop creation right now but we can improve the new product code to be more resilient and self-fixing so that it fixes current bugs and avoid inconsistencies from an upgraded shop

### Steps to reproduce

- in the default group (that doesn't share stock quantity) create a new shop and copy all data
- create a shop group that shares stock quantity
- create two shops and copy all data
- select shop context Single shop from first group
- the page is correctly displayed
- switch to a shop from the first group
- the page is correctly displayed
- switch to a shop from the second group
- an exception is thrown (see screencast)

### Screencast

https://watch.screencastify.com/v/msTVVCMW8NfxTnUhJeRf

### PrestaShop version(s) where the bug happened

8.0

**Comment by Progi1984** [comment]
Blocked because "Waiting for UX & Wording"

**Comment by jolelievre** [comment]
@MatShir this one is about multishop which is not in the scope of 8.0.0 so it should be targeting the 8.1 version instead

**Comment by jolelievre** [comment]
This issue should have been fixed by the two associated PRs It should be tested again

**Comment by florine2623** [comment]
@jolelievre @MatShir 

With `8.0.x branch`, I still have the exception :x: 
<img width="1155" alt="Screenshot 2023-04-06 at 17 16 58" src="https://user-images.githubusercontent.com/16019289/230423563-d288f909-1f74-47d6-aa52-8b91ad5987cc.png">


With `8.1.x` and `develop branch`, no more exception, I can go from shop to shop ✅ 

https://user-images.githubusercontent.com/16019289/230423777-30b3e358-de5e-4073-9315-63d3e8556a7e.mov

As it is fixed in 8.1.x and develop, I will close the issue !
Thanks!
