### ISSUE TITLE
Side menu is in English even if the shop is installed in another language (docker)

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#27029]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With the docker image the side menu is always in english even if the shop is installed (CLI or manual install) in spanish or french for example

### Expected behavior

If the shop is installed in a language, the side menu should be translated in this language and not in english

### Steps to reproduce

1. Install docker image from https://hub.docker.com/r/prestashop/prestashop 
(i installed with this command `docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -e PS_DEV_MODE=0 -e DB_USER=root -e DB_PASSWD=admin -e DB_PREFIX=ps -e DB_NAME=testdocker -e PS_INSTALL_AUTO=0 -e PS_ERASE_DB=1 -e PS_INSTALL_DB=1 -e PS_DOMAIN=localhost -e PS_LANGUAGE=fr -e PS_COUNTRY=fr -e PS_ALL_LANGUAGES=0 -e PS_FOLDER_ADMIN=admin-dev -e PS_FOLDER_INSTALL=install-dev -e PS_ENABLE_SSL=0 -e ADMIN_MAIL=demo@prestashop.com -e ADMIN_PASSWD=prestashop_demo -p 8181:80 -d prestashop/prestashop`)
2. Install shop in manual (install in fr and country in fr) or with CLI 
(i installed with this command `runuser -g www-data -u www-data -- php -d memory_limit=1 /var/www/html/$PS_FOLDER_INSTALL/index_cli.php --domain=localhost:8181 --db_server=some-mysql --db_name="$DB_NAME" --db_user=root --db_password=admin --prefix="$DB_PREFIX" --firstname="John" --lastname="Doe" --password=$ADMIN_PASSWD --email="$ADMIN_MAIL" --language=$PS_LANGUAGE --country=$PS_COUNTRY --all_languages=0 --newsletter=0 --send_email=0 --ssl=$PS_ENABLE_SSL`)
3. Go to the BO of your shop and login 
4. See error =>  side menu is in english but should be in french

### PrestaShop version(s) where the bug happened

1.7.8.0 // 1.7.8.1 // 1.7.8.2

**Comment by saulaski** [comment]
@SD1982 Hello good sir,
Using `ps` instead of `ps_` as prefix option in installation command is causing failure of all translations in database, not only the menu options.
Bug fix is coming up.

**Comment by SD1982** [comment]
Hi @hibatallahAouadni @saulaski did a PR #27722 that can be linked with this issue.  
Thanks @saulaski :+1:  !!

**Comment by Progi1984** [comment]
Fixed by @saulaski in #27722 and tested by @khouloudbelguith

**Comment by khouloudbelguith** [comment]
Hi @SD1982,

I tried to install PS1778 with cli
`php 1778/install-dev/index_cli.php --language=it --country=it --base_uri=1778 --domain=localhost --db_server=127.0.0.1 --db_user=user --db_name=presta --db_password=User@2022 --prefix=sktest --firstname=demo --lastname=demo --email=demo@prestashop.com --password=123456789 --db_create=1`
=> ok
![image](https://user-images.githubusercontent.com/16067358/161728287-394b3f3e-8d5a-4358-b750-3bffbb71a1d7.png)

I tried to install PS1785 with cli
=> NOK
![image](https://user-images.githubusercontent.com/16067358/161728428-3bb757ff-fce6-4ce1-8f02-365fbce2b119.png)

In fact, it is random
test1 => ok

https://user-images.githubusercontent.com/16067358/161728631-30745eb9-f73f-4376-b672-285d64499976.mp4


test2 => nok

https://user-images.githubusercontent.com/16067358/161728645-1c6f80a2-38a0-4da3-af05-9987cf1c7fec.mp4


test3 => ok

https://user-images.githubusercontent.com/16067358/161728660-250d4f3d-e3bc-4655-89e9-4e8d10f2339a.mp4

With a shop created with O3T

- 1778 => ok
- 1785 => NOK

With PS1785, to fix the issue we can go to BO > International > Translations > Update the language 

I will re-open the issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hello @MatShir,

This issue is a regression from PS1780.
Can we re-add it to the 1.7.8.7 project?

Thanks!

**Comment by adminvr** [comment]
Hi, I use docker to deploy and install prestashop and  i have exactly this problem in version 1.7.8.6 . 

Is the bug fix will be added to the 1.7.8.7 version ?  If yes, Have you got a release date of the 1.7.8.7?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @adminvr 

> Have you got a release date of the 1.7.8.7?

No, we haven't!
To be informed when it's fixed, please subscribe to this issue or to #28522 

Thanks!

**Comment by FabienPapet** [comment]
1.7.8.7 is out since last week, I think this issue can be closed as the bug is fixed and a release is available.

**Comment by SD1982** [comment]
It seems that the issue is not fixed, I reproduced it again this morning with the docker 1.7.8.7 image
![image](https://user-images.githubusercontent.com/40635814/182339688-000ffda1-41f0-4774-b301-c9509cad8428.png)

**Comment by adminvr** [comment]
Hi,

I ve exactly the same problem again with 1.7.8.7, with docker image and auto install.  It’s not fixed.

Have you got a solution ?

(https://user-images.githubusercontent.com/107860048/182701755-49c606ac-1ec6-4dc8-8cf3-8f6b535cf921.png)


Thanks.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29420

**Comment by matks** [comment]
Next release 1.7.8.8 should be working as expected :) @SD1982 @adminvr

**Comment by JSSSX** [comment]
I just installed 1.7.8.8, and the issue is still present on both BO and FO.


![2022-12-20_172648](https://user-images.githubusercontent.com/35422561/208632091-908b2b7b-c102-4081-80ba-989e5ec16921.jpg)
![2022-12-20_172706](https://user-images.githubusercontent.com/35422561/208632119-b0d7822a-6e28-420f-b818-e81e16c7f77e.jpg)

**Comment by MatShir** [comment]
@JSSSX Could you provide the exact step of your installation and your environment ?

**Comment by dngraphisme** [comment]
> I just installed 1.7.8.8, and the issue is still present on both BO and FO.

Same for me ! 1.7.8.8 exactly the same problem :(

**Comment by ArnasL** [comment]
Very strange. I can confirm that in version 1.7.8.7 this bug is solved, but in 1.7.8.8 bug is back! Any fix?

**Comment by MatShir** [comment]
@ArnasL are you facing the issue with same step? Could provide a bit more details, so we can reproduce it in our end please :)

**Comment by LameuleFR** [comment]
I can confirm this bug is present on fresh installation of 1.7.8.8 using classic table prefix (ps_)

**Comment by dngraphisme** [comment]
I confirm it is always present on a new installation in 1.7.8.8 ...

**Comment by MatShir** [comment]
docker installation ?

**Comment by dngraphisme** [comment]
Hello @MatShir , normal setup. To return the menu to French, you must reinstall the language pack in back office.

**Comment by jonasburneika** [comment]
Good day,
we noticed that this error occurs on multistore. We have 1.7.8.1 
![Screenshot 2023-05-12 at 10-42-23 Languages](https://github.com/PrestaShop/PrestaShop/assets/44444305/a16779cd-3e78-45de-86d9-e6d7f48248b6) with installation with the English language. The website has 3 different stores and domains for each baltic state. If the admin changes the language to English it works fine. But if it changes into Latvian or Estonian. It does not work properly. Part of the Dashboard is translated, but the other part is not. I have found out that translation load information from `app/Resources/translations` folder with the wrong Locale. 

If you enter BackOffice tru a different domain (LV/EE) then your Dashboard is in the default language. And if you try to load i.e. Lithuanian language in the Latvian domain - it fails.

**Comment by OliverCG** [comment]
I can confirm that this bug is still present on fresh installation of PrestaShop 1.7.8.10 with no custom settings:

- ps_ as prefix.
- Spanish as the default language.
- No multistore.
- No more than one language.

**Comment by MatShir** [comment]
@OliverCG in the meantime, you can update the translation. It is a very random bug, for now we can't reproduce it

**Comment by OliverCG** [comment]
> @OliverCG in the meantime, you can update the translation. It is a very random bug, for now we can't reproduce it

I've tried to import the language and update it, but the menu elements are still in English. Or is there any way to force the language like adding a new one, change it and then revert to Spanish?

**Comment by MatShir** [comment]
Cache pb 🤷 that is weird, @PrestaShop/committers have you faced any issue about language update ?

**Comment by kmorgen** [comment]
I just updated a (Danish language) PS 1.7.8.10 to PS 8.1.2 with 1-Click Upgrade v4.16.4 and the **left side Menu** then becomes English.

Changing language inside Team will not change the menu language accordingly (it will remain in English). 

Updating the language pack solved it though (International -> Translations -> Add/Update a language)

**Comment by szildaniel** [comment]
Same problem here PS 1.7.8 UPGRADE by 1 Click Upgrade module to PS 8.1.2 - left side backoffice menu is in English even if I change language in my admin profile. Rest of backoffice is in my choosen language
![Screenshot_410](https://github.com/PrestaShop/PrestaShop/assets/44669565/fdfc2d93-0200-4177-bd0f-15a86a0bf39c)

**Comment by kmorgen** [comment]
Preferably it should be solved by the 1-click Upgrade if possible.

In the meantime you can easily solve it by updating the language pack in: International -> Translations -> Add/Update a language.

**Comment by kmorgen** [comment]
> Same problem here PS 1.7.8 UPGRADE by 1 Click Upgrade module to PS 8.1.2 - left side backoffice menu is in English even if I change language in my admin profile. Rest of backoffice is in my choosen language!

Preferably it should be solved by the 1-click Upgrade if possible.

In the meantime you can easily solve it by running the auto language update: International -> Translations -> Add/Update a language.

**Comment by szildaniel** [comment]
@kmorgen yup after Add/Update language menu is in desired language ;) thanks
