### ISSUE TITLE
There are no Spanish translations in the ps_emailalerts module

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#27026]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There are no Spanish translations in the ps_emailalerts module
![image](https://user-images.githubusercontent.com/62474824/146686610-54f1bcb5-6129-46d2-8148-85312987e6bf.png)

### Steps to reproduce

Ps_mailalerts

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_mailalerts

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

You encounter this issue cause there's missing traductions, please follow these steps:

1. **BO**>**IMPROVE**>**International**>**Translations**
2. In the first block **`Modify translations`**
3. Choose **Installed modules translations** as **`Type of translation`**
4. Select **Mail alerts** as **`Select your module`**
5. Set **Spanish** as **`Select your language`**
6. Click on **Modify** button
7. Search the sentences with English traduction:
![image](https://user-images.githubusercontent.com/23308427/146758850-1616e816-683e-459a-815c-5d3c11f1b577.png)
8. Change it
![image](https://user-images.githubusercontent.com/23308427/146758864-274d73da-30a0-45bb-9f19-58b856c19b32.png)
9. Save
10. Check the module 
![image](https://user-images.githubusercontent.com/23308427/146758874-8572d78f-e8ae-4a1d-8b4f-6a3963a2040e.png)

Closing the issue :wink: 
Thanks!

**Comment by alfonsolr09** [comment]
I want to add the Spanish translations but i cant find the file...
reopen this pls

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

> I want to add the Spanish translations but i cant find the file...

What file you want to add?? and where?
Waiting for your feedback.

Thanks!

**Comment by alfonsolr09** [comment]
Spanish translations but not only for me. I want to add here on github

**Comment by rickygzz** [comment]
@alfonsolr09  Translations are made within [crowdin.com](https://crowdin.com/translate/prestashop-official/). I you want to collaborate you can ask to join anytime. 

Although Spanish is fully translated, there is space for translation improvements.

![image](https://user-images.githubusercontent.com/36200981/147499534-4c5fcf64-62cd-40ee-9824-61a12261103e.png)

![image](https://user-images.githubusercontent.com/36200981/147497536-a1626fda-bb76-47dc-a052-c4328ece3f57.png)

However, I am not sure why ps_emailalerts is not showing the translations.

The development of ps_emailalerts may be tracked from https://github.com/PrestaShop/ps_emailalerts . 

Waiting to see any update from the team

**Comment by alfonsolr09** [comment]
It is true, I already checked the translations previously and as you say PrestaShop is completely translated in crowdin. 

For some reason that I do not know the translations of that module are not shown...

**Comment by hibatallahAouadni** [comment]
FYI @Julievrz

**Comment by Julievrz** [comment]
> FYI @Julievrz

Hi there,

Sorry for the late answer, I was out of the office.

Indeed, all ps_emailalerts strings are translated and validated in Crowdin, so Spanish translations should appear in the BO. I don't know why it doesn't work. 🤔

**Comment by atomiix** [comment]
From what I can see, translations for module ps_emailalert are not included in the language pack downloaded from [i18n.prestashop.com](https://i18n.prestashop.com/translations/1.7.8.2/fr-FR/fr-FR.zip) and it seems "normal" as the module ps_emailalert is not a native module (not included in [composer.json](https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json))

**Comment by MatShir** [comment]
@atomiix will the issue be fixed after the module will be included in the zip (see issue https://github.com/PrestaShop/PrestaShop/issues/24643)?

**Comment by atomiix** [comment]
@alfonsolr09 @Julievrz @MatShir plot twist: translations are there but in the module `ps_emailalert` we use the translation domain `Modules.Emailalerts.Admin` but the translations are in the `Modules.Mailalerts.Admin` domain 😅
It seems that it was a desired change from [this PR](https://github.com/PrestaShop/ps_emailalerts/pull/49) and [Pablo stated ](https://github.com/PrestaShop/ps_emailalerts/pull/49#pullrequestreview-474453284) that we'd have to re-extract the default catalogue

**Comment by Progi1984** [comment]
Fixed by @jolelievre in #27193

**Comment by marioquartz** [comment]
Im using the last version 1.7.8.5. ITS NOT FIXED. So I have a question: How I fix manually. What file I have to modify. Or how modify the domain.
Because I need spanish translations. And of course I dont gonna translate from scratch.

**Comment by MatShir** [comment]
@marioquartz have you update the module ? It is weird on my site it is working

**Comment by marioquartz** [comment]
With v2.3.3 the only way to "fix" it is download the translated mails from other version and copy it in the child theme.

**Comment by MatShir** [comment]
Are we talking about the same thing ? Create a new issue [here](https://github.com/PrestaShop/PrestaShop/issues/new/choose) with screenshots and details steps, so we can try to reproduce your issue ?

**Comment by marioquartz** [comment]
The shop is in production now. So its not posible touch nothing. Maybe in the next shop I can make test.

**Comment by alfonsolr09** [comment]
now works good, thanks :+1:

**Comment by lmeyer1** [comment]
@marioquartz You have to update the translations
![Capture d’écran 2022-04-12 120151](https://user-images.githubusercontent.com/7520695/162935116-463854a9-acb2-4047-84c9-bc3a7b3d69c0.png)

**Comment by marioquartz** [comment]
> You have to update the translations

I updated two times, as minimun. In the end, copy the files from other version in my theme folder was the fix. I hope your open issue makes them fix it in their end.

**Comment by alfonsolr09** [comment]
> > You have to update the translations
> 
> I updated two times, as minimun. In the end, copy the files from other version in my theme folder was the fix. I hope your open issue makes them fix it in their end.

What have you updated?

Have you tried to update ps_mailalerts module?
And the translations??

**Comment by marioquartz** [comment]
I updated (April 1st):
-Shop
-Module
-Translations
So yes. All, the 100% of all things that can be updated is updated. And no, the translations were broken. The only fix were copy the translations of other version in the folder of my child theme of clasic theme.
I can not update now (April 13th) because I had to change some strings related with tax.

**Comment by alfonsolr09** [comment]
I have updated everything, the store to the latest version 1.7.8.5 and the module also to the latest version and the translations work correctly in
