### ISSUE TITLE
FO - ps_dataprivacy- Bad display of Customer data privacy message when the text contains a link 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27155]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display of Customer data privacy message when the text contains a link 
![image](https://user-images.githubusercontent.com/89604350/147811228-a252f6ce-6ae0-4af6-b5e8-9f6cbb1c656b.png)

### Steps to reproduce

1. Go to BO> Modules> Module manager > Configure the module Customer data privacy block
2. add a link in the message and save
3. Go to Front office and open the account creation page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

ps_dataprivacy v2.0.1

**Comment by FabienPapet** [comment]
Hello @marwachelly looks like the fix is merged, so can we close this issue ?

**Comment by marwachelly** [comment]
Hello @FabienPapet,

I retested the module on the dev branch but the issue still exist.

https://user-images.githubusercontent.com/89604350/183600390-7512db75-f425-4a63-a95e-d532763af6b4.mp4

Could you please check?
