### ISSUE TITLE
BO - Products - Wrong position of information message in multistore context

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27908]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related: https://github.com/PrestaShop/PrestaShop/issues/27840
Wrong position of information messages in multistore context
**Product V1**
![image](https://user-images.githubusercontent.com/16067358/158355900-cc2ff4ba-382b-483c-b943-a83235009d94.png)
**Product V2**
![image](https://user-images.githubusercontent.com/16067358/158356058-9970b3f0-3137-48cb-8d3a-242f00b41457.png)

It should be
![image](https://user-images.githubusercontent.com/16067358/158356796-d1750c5c-eb02-4c10-84f3-344860699f78.png)

### Steps to reproduce

1. Enable Multistore & create a new shop without a color
2. Go to BO > Catalog > Products > Select a new shop
3. Edit a product V1 & V2
4. the information message is in the header but it should be below the tabs

![image](https://user-images.githubusercontent.com/16067358/158356656-13eba89c-963d-4e6f-9080-a53bdef75ccf.png)

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

7.4, 7.3

**Comment by Progi1984** [comment]
@atomiix It should be fixed in your PR. No ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,
No, I checked a fresh install today and it is not fixed on the Edit product page.
It is fixed only on the Stocks page
![image](https://user-images.githubusercontent.com/16067358/158358274-8e73b0cc-58c8-40d0-b315-12087f0331ac.png)

Thanks!

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Could you check it (in the `develop` branch) ? I think it's fixed.

![image](https://user-images.githubusercontent.com/1533248/161271421-4bdc78f7-7aa0-4ab4-a291-fc1a3f315d7e.png)

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

In fact, the issue is displayed on the Product Edit page and not on the product list page
![image](https://user-images.githubusercontent.com/16067358/161313030-be973aae-97af-42a7-a870-3b2926dd2d00.png)

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith : it's fixed.
