### ISSUE TITLE
Can't modify Front Office translations after upgrade to 1.7.8.6.

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#29164]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's not possible to find and modify front office expressions any more. The theme cannot be selected.

### Expected behavior

It is possible to find and modify  the front office expressions.

### Steps to reproduce

1. With 1.7.7.5 version, Go to International -> Translations
2. Choose Themes translations / Classic / English language > Click on Modify button
3. Update a translation you want and save
4. Check in FO if the translation is well updated
5. Upgrade to an 1.7.8.6 version your shop
6. With 1.7.8.6 version, go to FO and see that the translation is always here
7. Go to International -> Translations
8. Choose Front Office Translation / Core (no theme selected), the theme cannot be selected, Classic in my case / English language > Click on Modify button.
10. Enter  in the Search field text of the expression you've got modified in the earlier version of PS and see error. It's not found any more. Particularly, I can't find modified expression "Unfortunately, there are no payment method available." to change it. But the shop keep using it.
11. You can't find it, you can't modify it.

![2022-07-26 003039](https://user-images.githubusercontent.com/11665990/180878591-d2b113f4-cf53-4225-800f-5a2b7b07e3c4.png)

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

13.3.31

**Comment by florine2623** [comment]
Hello @AndreyOgleznev ,

Indeed between 1.7.7.8 and 1.7.8.x, the behavior is a little different. 
I can't choose my theme in 1.7.8.X, it is displayed: "Core(no theme selected)" 

PS 1.7.7.8:
<img width="1006" alt="Screenshot 2022-07-26 at 11 44 10" src="https://user-images.githubusercontent.com/16019289/180977484-ead6fd79-2823-4e99-9680-0d985569f5f4.png">

PS 1.7.8.x:
<img width="1202" alt="Screenshot 2022-07-26 at 11 44 30" src="https://user-images.githubusercontent.com/16019289/180977518-78a0f647-c8fb-4907-aa8c-86c13b287a76.png">

Although, I didn't have a problem with translating my string:
In FO:
<img width="745" alt="Screenshot 2022-07-26 at 11 47 39" src="https://user-images.githubusercontent.com/16019289/180977619-37de114c-0fc7-4740-81c3-3d94164cc3b5.png">
In translation in BO:
<img width="861" alt="Screenshot 2022-07-26 at 11 49 25" src="https://user-images.githubusercontent.com/16019289/180977655-8cb0e6ca-d925-4a44-bcc5-944bd2b8006f.png">

Can you confirm you can translate without problem ?
Thanks!

**Comment by Andre-N-73** [comment]
Hello @florine2623 ,
Thank you for the quick answer. Unfortunately in my case it's different. The shop doesn't use in the FO the expression I can see in the BO Translations. If I edit the expression it's not used neither. I've tried to use the Clear Cache button in the Advanced Parameters -> Performance page, but the issue still persists.

**Comment by florine2623** [comment]
You should find some more info here : https://build.prestashop.com/prestashop-specs/1.7/back-office/international/translations/translations.html#front-office-translations

Can you do a screen record of your `BO > Translation page > Save` like mine. 
You should be able to find your phrase. Even if on the BO, your theme is not selected :)

https://user-images.githubusercontent.com/16019289/181015332-4480063b-672b-4fc7-9911-0e9344aac15e.mov

**Comment by Andre-N-73** [comment]
@florine2623 Thank you very much for the documentation link. I think I've found the culprit. It looks like the problem is in the "theme" field of the  preXXX_translation table. BO interface now operates with NULL value. I'm not surprised since there is no theme selected. But FO interface still operates with the "classic" value. So one can neither find nor change the translation through the BO interface. Please see my screenshot attached.
![2022-07-26_18-13-09](https://user-images.githubusercontent.com/11665990/181045093-66c758a2-dabc-4cab-a07f-5af0145858cb.png)

**Comment by Andre-N-73** [comment]
EDIT: the interaction logic seems to be more complicated. When I reset translation through the BO interface it deletes the translation with the classic theme and keeps the translation with the NULL theme. FO starts to use the translation with the NULL theme left.

**Comment by florine2623** [comment]
On my end, I only have NULL as theme:
<img width="920" alt="Screenshot 2022-07-26 at 18 16 31" src="https://user-images.githubusercontent.com/16019289/181057936-628b46fe-efec-4ef2-86c9-d195f276b38f.png">

My translation is well saved:

https://user-images.githubusercontent.com/16019289/181058292-cb78ab57-5626-4fb7-9020-cc1dc4dc5111.mov

Maybe the issue comes from the upgrade itself.
Can you tell me which version you upgrade from ?
I will try on my end.

**Comment by Andre-N-73** [comment]
I've got a few NULL theme along with classic theme records in the table.
I upgraded from 1.7.7.5

**Comment by sLorenzini** [comment]
Hello @AndreyOgleznev ,

I reproduce the issue with an upgrade from 1.7.7.5 to 1.7.8.6.

My translation made before the upgrade is still saved in database and display in FO but in BO it disappeared and we can update it with another translation. Here's my screenrecord and screenshots:

- Before upgrade:

![Capture d’écran 2022-07-27 à 10 56 28](https://user-images.githubusercontent.com/2854834/181214718-0c85f9cf-8d4f-4c67-847f-c8afd3bfd7de.png)

![Capture d’écran 2022-07-27 à 10 56 51](https://user-images.githubusercontent.com/2854834/181214750-1f65a9b5-a565-4263-98c8-66db72e7d69d.png)

![Capture d’écran 2022-07-27 à 11 32 26](https://user-images.githubusercontent.com/2854834/181214173-d9d39d47-9ab7-4bc3-9ee1-27ccb0f813fa.png)

- After upgrade

https://user-images.githubusercontent.com/2854834/181214925-84b317c1-0220-47ba-8c46-391dac85b3c7.mp4

We can update another translation with no change of the first translation:

https://user-images.githubusercontent.com/2854834/181213845-84bcbde9-a55d-456b-b7b6-e8fba9f58308.mp4

![Capture d’écran 2022-07-27 à 11 33 40](https://user-images.githubusercontent.com/2854834/181214418-cb850cac-ebe1-4bdb-bc89-6f319f896949.png)

I'll add this to the backlog so it can be fixed. I will update the steps to test this issue

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Andre-N-73** [comment]
Hello @sLorenzini,
Thank you very much!

**Comment by hibatallahAouadni** [comment]
Ping @sLorenzini & @florine2623 is it a regression or an old bug?

**Comment by sLorenzini** [comment]
> Ping @sLorenzini & @florine2623 is it a regression or an old bug?

Hello,

@hibatallahAouadni, after a new test with an upgrade from 1.7.6.9 to 1.7.7.8, there is no bug and the translation is ok and can be updated. 
The issue only concerns all upgrade to 1.7.8.x versions.
It's a regression.

Thank you

**Comment by atomiix** [comment]
@sLorenzini @florine2623 I think this one is fixed by #27422

**Comment by sLorenzini** [comment]
hello, 

@atomiix, I've retested with an upgrade from 1.7.7.5 to 1.7.8.7 (with the fix of https://github.com/PrestaShop/PrestaShop/pull/27422)

The error is still here:

- Before upgrade:

![Capture d’écran 2022-09-09 à 10 25 41](https://user-images.githubusercontent.com/2854834/189315995-4e41615b-e366-4ac5-882d-67749e679835.png)
![Capture d’écran 2022-09-09 à 10 26 01](https://user-images.githubusercontent.com/2854834/189316012-40a44363-d3a1-49ff-951d-c457bb88abd8.png)
![Capture d’écran 2022-09-09 à 10 26 09](https://user-images.githubusercontent.com/2854834/189316027-c9392c1b-52d7-4f86-82cf-9b947d6f9f82.png)

- After upgrade:

https://user-images.githubusercontent.com/2854834/189316119-183823d2-b283-4ae4-a051-fb85adb956ae.mp4

I add it again to the backlog.

Thanks

**Comment by atomiix** [comment]
@sLorenzini I think you changed the wrong translation. You went to `Shop.Theme.Catalog` instead of `Shop.Theme.Global`.
But anyway, it looks like there's still an issue when I see the DB

**Comment by sLorenzini** [comment]
> @sLorenzini I think you changed the wrong translation. You went to `Shop.Theme.Catalog` instead of `Shop.Theme.Global`. But anyway, it looks like there's still an issue when I see the DB

indeed @atomiix my bad 😅. Here's the good screen of my translation of `Shop.Theme.Global` after the upgrade:

![Capture d’écran 2022-09-09 à 15 48 51](https://user-images.githubusercontent.com/2854834/189365662-a46e9c4f-6076-41e7-9dd5-359bcfd00004.png)

It doesn't keep the translation made before the upgrade. So there is still the issue 😉 
Thanks

**Comment by florine2623** [comment]
ping @MatShir @eshraw 

Tested the following:
- install 1.7.7.5
- modify translation in Shop.Theme.Global in BO
<img width="1211" alt="Screenshot 2022-09-13 at 15 07 53" src="https://user-images.githubusercontent.com/16019289/189909304-737e3075-92bd-4723-9377-004a944c0477.png">
Translation is well saved in FO:
<img width="493" alt="Screenshot 2022-09-13 at 15 08 34" src="https://user-images.githubusercontent.com/16019289/189909454-973f60d1-faf9-4df4-a8b5-b35cbda1b42f.png">

- uninstall modules (Facebook, Marketing, Checkout, etc)
- upgraded to 1.7.8.6 - successful upgrade
- Check in FO, translation is kept (after clear cache PS and browser): ✅ 

<img width="470" alt="Screenshot 2022-09-13 at 15 24 53" src="https://user-images.githubusercontent.com/16019289/189912902-edfe668d-11d6-4a15-97b1-f9f6aa959f6d.png">

- In DB, seems fine too: ✅ 
<img width="627" alt="Screenshot 2022-09-13 at 15 28 55" src="https://user-images.githubusercontent.com/16019289/189914022-29571f3a-9c3a-47eb-bc09-d42e2941800b.png">


- But in BO, translation has disappeared: ❌ 

<img width="1184" alt="Screenshot 2022-09-13 at 15 20 36" src="https://user-images.githubusercontent.com/16019289/189912819-52376299-2154-4c33-8a82-27d88d3bf968.png">


I can reproduce the issue when upgrading from 1.7.7.5 to 1.7.8.6. It is 👎 

Could you define the complexity please ?
Thanks!

**Comment by atomiix** [comment]
I think that the issue is that with PrestaShop 1.7.8.x, the column `theme` should be `null` instead of `classic` when translating core translations. An autoupgrade script removing the theme column when theme is `classic` should be enough to fix the issue.

**Comment by mauricecec** [comment]
I have same problem , in my case i installed a fresh Prestashop 1.7.8.7
Than after that i did :
International - Translate front office Select Theme , no Theme Classic Found 
as i understand there is a file that can be Modified from Null to Classic , but i do not understand which one
Thanks
