### ISSUE TITLE
Upgrade using actionBeforeUpgrade does not execute migrations

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#29542]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Have 2 modules :

First one implementing the hook `actionBeforeUpgrade` which we will call The Updater : As expected on PS 8.0.0, this hook will retrieve the updated module new files, extract them into the modules folder and let the ModuleManager continue the upgrade (migrations, update DB, ...)

A second one which is a classic module implementing an "early hook" : a hook executed before the upgrade, like `actionDispatcherBefore` (this one is called when any request is made on the shop. It detects which controller domain it is front/admin/other and perform authentication checks)

Have an update version available for module 2 and execute the upgrade through The Updater

Observation : The module 1 files are well replaced but the migrations are not executed and the version in DB is wrong
Other observation : the file config_ISO.xml in the root folder of the module 1 contains the old version number

### Steps to reproduce

1 - have a fresh install of PS 8.0.0

2 - Install [prestashopexamplemodule_1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/9495809/prestashopexamplemodule_1.0.0.zip) : This module is a classic module implementing `actionDispatcherBefore`. It is in the version 1.0.0 and register a config value in ps_configuration EXAMPLE_MODULE_CONFIG = "VALUE FOR 1.0.0"

3 - Install [prestashopexampleupdatermodule.zip](https://github.com/PrestaShop/PrestaShop/files/9495840/prestashopexampleupdatermodule.zip) : This module is The Updater. It implements `actionBeforeUpgrade`. This hook will extract and install the module prestashopexamplemodule_1.0.1.zip built in it. This new version of module 1 will have the version 1.0.1 and change the config value to EXAMPLE_MODULE_CONFIG = "VALUE FOR 1.0.1"

4 - once the 2 modules are installed. You will see that module 1 have an upgrade available.
Execute that update and observe that files are replaced (v1.0.1 in config.xml and prestashopexamplemodule.php) but the migrations are not executed : You'll have the same value for "EXAMPLE_MODULE_CONFIG" in ps_configuration and the version of module 1 in DB is still 1.0.0
If your shop is in french for example. You'll also have a file config_fr.xml containing version 1.0.0 instead of 1.0.1

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by sowbiba** [comment]
Technical clue

Because the hook actionDispatcherBefore is executed before the actionBeforeUpgrade hook, the module 1 is loaded through ServiceLocator::get to execute the hook

Before executing the upgrade migrations, we perform LegacyModule::getModulesOnDisk to get the modules properties before saying if migrations are needed. To do that, we also use ServiceLocator::get to get the module instance

ServiceLocator::get have a static cache. Once the module is loaded (with the old version), you will always get the same instance.

So migrations are always not needed and DB update won't be done too

**Comment by sLorenzini** [comment]
Hello @sowbiba,

Thank you for this report.
I couldn't reproduce your issue, the version is well updated after upgrade on the .xml / .php files and DB. 
Tested on develop and 8.0.x branches. See my screenshots and screenrecord of develop branch:

Config.xml after upgrade

![configxml](https://user-images.githubusercontent.com/2854834/188661884-da130c83-95ef-4817-acea-5181f35bd130.png)

prestashopexamplemodule.php file after upgrade

![phpfile](https://user-images.githubusercontent.com/2854834/188661897-3e4d0bc1-ec7e-4bf9-aef5-8c37859d16de.png)


https://user-images.githubusercontent.com/2854834/188661669-a64ca1d8-201d-4491-a23d-a6433e9fe4a0.mp4

Furthermore, I need to launch the upgrade two times. An error is displayed. I don't know if it's related to the module itself.

As discussed with you, waiting for your feedbacks to allow to reproduce this issue

Thank you

**Comment by sowbiba** [comment]
https://user-images.githubusercontent.com/7426640/188670363-4807d325-4e4b-4b2e-9ea5-affe4eca606b.mp4

**Comment by sowbiba** [comment]
Other way to test ... same result

https://user-images.githubusercontent.com/7426640/188672217-8152b0bc-1cfb-4976-bc6a-8ce80f81ee50.mp4

The zip for v1.0.1
[prestashopexamplemodule_1.0.1.zip](https://github.com/PrestaShop/PrestaShop/files/9498362/prestashopexamplemodule_1.0.1.zip)

**Comment by jolelievre** [comment]
Hi @sowbiba 

If I understood everything, your [prestashopexampleupdatermodule.zip](https://github.com/PrestaShop/PrestaShop/files/9495840/prestashopexampleupdatermodule.zip) module implements the `actionBeforeUpgrade` hook and handles the extraction of its internal zip in place of the current module code. This mimic the action of downloading a module from an external API right? So this part is functional since the module's class has been correctly updated (this reprenset L173 on the following code).

https://github.com/PrestaShop/PrestaShop/blob/b81d298e518368bd211697a2a699a1789f88c162/src/Core/Module/ModuleManager.php#L173-L176

However what fails after this is the upgrade scripts execution, from what you said it could be because the module returned L175 has actually been cached at the beginning of the process so its `version` attribute still contains `1.0.0` therefore the scripts for `1.0.1` are not executed right?

In a nutshel, if we could force the cache refresh on L175 we would have up-to-date data and the upgrade should happen as expected? Or at least it's your main lead of the problem right?

I believe @FabienPapet you noticed this kind of issue a few weeks ago, and you proposed a solution that would allow forcing the refresh of the cache no?

**Comment by atomiix** [comment]
The main issue is that because a module can register a hook that is triggered very early like `actionDispatcherBefore`, the module is instanciated, that means that you can't instanciate the new version of the module later, when the files have been changed. That prevents the new information about the module (like its version) to be accessed directly from its instance and the potential `update()` method of the new module to be executed if it is different from the old version of the module.

**Comment by sowbiba** [comment]
> If I understood everything, your [prestashopexampleupdatermodule.zip](https://github.com/PrestaShop/PrestaShop/files/9495840/prestashopexampleupdatermodule.zip) module implements the `actionBeforeUpgrade` hook and handles the extraction of its internal zip in place of the current module code. This mimic the action of downloading a module from an external API right? So this part is functional since the module's class has been correctly updated (this reprenset L173 on the following code).

Exactly

====

For the module being cached when calling  $module = $this->moduleRepository->getModule($name); 
We already noticed that too but even if you disabled the cache retrieval by commenting

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Module/ModuleRepository.php#L145

From L145 to L151, you'll face the same issue

What I suspect is when we execute a hook, we call

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Hook.php#L888

then https://github.com/PrestaShop/PrestaShop/blob/52a2498bb9940f394f1e2771be7330750900138e/classes/module/Module.php#L1193

and https://github.com/PrestaShop/PrestaShop/blob/52a2498bb9940f394f1e2771be7330750900138e/classes/module/Module.php#L1214

Here ServiceLocator::get loads the module 

(That's why I require an "early" hook in this issue description)

When performing module update, to check if updateMigrations is needed we call again ServiceLocator::get
https://github.com/PrestaShop/PrestaShop/blob/52a2498bb9940f394f1e2771be7330750900138e/classes/module/Module.php#L1452

In ServiceLocator, there is a static cache and the objects returned are always the same

**Comment by HanaRebaiQA** [comment]
Hello @sowbiba 

I tried to reproduce your issue using develop branch and the same steps to reproduce. I didn't reproduce your issue in DB. The version is well updated.

https://user-images.githubusercontent.com/92912932/189104515-ff55bf9d-9a82-49bf-9d24-2c68a307512b.mp4


Here is my whole feedback : 

- Check in the DB :  **ps_configuration** table: The version is well updated  when upgrade the `prestashopexamplemodule` module ==> It's **1.0.1** version 

![image](https://user-images.githubusercontent.com/92912932/189102350-6a500a2a-fb3c-4709-b0fc-d3a102a67e2c.png)

- Check the **config.xm**l file : The version is well updated ==> It's **1.0.1** version

![image](https://user-images.githubusercontent.com/92912932/189102726-014161f5-e6ea-491a-9874-b8fedef18e60.png)

But, it's not updated in config_fr.xml because my shop is not in frensh: OK

- Check in **prestashopexamplemodule.php** file : Two values : 

==> It's **1.0.1** version here 

![image](https://user-images.githubusercontent.com/92912932/189103702-a92bb563-05b7-454a-807c-a929d3149523.png)

==> It's **1.0.0** version when check with `EXAMPLE_MODULE_CONFIG` 

![image](https://user-images.githubusercontent.com/92912932/189103955-b45150e2-eb1e-410a-9141-8c9ca196b40d.png)
 

Could you please check again ?

Thank You!

**Comment by sowbiba** [comment]
@HanaRebaiQA You did not execute the test correctly. You upgraded the module twice.
From one execution to another the module is reloaded, so the container have the correct module version when you run it the second time


Reinstall the modules, upgrade just one time and check the values of ps_configuration EXAMPLE_MODULE_CONFIG and version in ps_module

**Comment by HanaRebaiQA** [comment]
Hello @sowbiba 

Thank you for your feedback.
Yes, indeed, i tried again to reproduce your issue when click one time to upgrade the module.
So, when i upgraded for the first time, the module is not upgraded : NOK
I think, this is the original issue, is that the module is not upgraded for the first time.

When, i click for the second time : OK

https://user-images.githubusercontent.com/92912932/189164695-babfda12-6419-4116-af96-9fde8228ffdf.mp4


I checked on PS1778 with your modules, the option to upgrade was not available.

https://user-images.githubusercontent.com/92912932/189164857-8dd3cd19-1700-413a-821b-da4572405c5c.mp4


Also, i tried the upgrade of another module and it's well upgraded for the first time.

https://user-images.githubusercontent.com/92912932/189165235-e8a675e7-3dca-42a6-bc8e-72adc8d58d2c.mp4

So, i think it's related to your module and not to Core. 
What do you think ?

A related issue for upgrade is mentioned [here](https://github.com/PrestaShop/ps_distributionapiclient/pull/6#pullrequestreview-1062265091) (Issue 5)

Thank You!

**Comment by sowbiba** [comment]
It is related to the Core. It depends on what hook are implemented by the module

To reproduce it in 1.7.8, use the second way I gave : upload the version 1.0.0, upload 1.0.1 and you'll have the same bug

**Comment by sowbiba** [comment]
> Other way to test ... same result
> 
> https://user-images.githubusercontent.com/7426640/188672217-8152b0bc-1cfb-4976-bc6a-8ce80f81ee50.mp4
> 
> The zip for v1.0.1
> [prestashopexamplemodule_1.0.1.zip](https://github.com/PrestaShop/PrestaShop/files/9498362/prestashopexamplemodule_1.0.1.zip)
> 
> 

This way @HanaRebaiQA

**Comment by HanaRebaiQA** [comment]
@sowbiba Do you think it's a regression ?

**Comment by sowbiba** [comment]
The bug already exists in 1.7.8, so it's not a 8.0.0 regression

**Comment by HanaRebaiQA** [comment]
@sowbiba Cause I didn't found the upgrade option on PS1778 to reproduce the issue. So, I'm asking if it's a 1.7.8 regression.

**Comment by atomiix** [comment]
If it worked in 1.7.7.x, I'm really curious to know... HOW? 😅

**Comment by sowbiba** [comment]
The upgrade process have changed in 8.0.0
The way I did it with the module prestashopexampleupdatermodule giving the upgrade for prestashopexamplemodule doesn't exist for 1.7.8

To reproduce in 1.7.8 or previous versions, upload prestashopexamplemodule v1.0.0 and then upload prestashopexamplemodule v1.0.1, you'll have the same bug

**Comment by HanaRebaiQA** [comment]
Hello @sowbiba 

Thank you for the provided details.
I tried to reproduce the issue on PS1787 using the [prestashopexamplemodule_1.0.1 (2).zip](https://github.com/PrestaShop/PrestaShop/files/9533749/prestashopexamplemodule_1.0.1.2.zip) for the upgrade.

I noticed that the upgrade option is added to the `prestashopexamplemodule` module and then the upgrade is well done from the first time.
The **1.0.1** version is well updated in : 

- The DB, ps_configuration 
- The config.xml 
- And, the prestashopexamplemodule.php

![image](https://user-images.githubusercontent.com/92912932/189310232-1b4baa0a-f285-4c80-8553-f28eadb5248d.png)

![image](https://user-images.githubusercontent.com/92912932/189310462-87fd38b0-0ec5-43f7-a9cb-0dc56b1694dc.png)

![image](https://user-images.githubusercontent.com/92912932/189310582-734f8722-2a07-4543-812f-6ceaca82a3bc.png)



https://user-images.githubusercontent.com/92912932/189308889-4d35a2ef-d7e9-4aa6-9e5b-453f3aa136c8.mp4

So, i think it's a 8.0.0 regression. What do you think ?

Thank You!

**Comment by matks** [comment]
Very good idea for a solution by @Quetzacoalt91 : start setting module version inside a composer.json file in the module. Reading this JSON file does not require to load a PHP file and allow to workaround the problem.

If we introduce this system, we have to be aware 99% of modules will _not_ contain a composer.son at the beginning so it needs to be a fallback system. When we attempt to fetch the module version 1) look inside composer.json and if it cannot be found/read 2) look inside main PHP module class.

If we implement this "read module version from composer.json" strategy inside the Core we should be able to fix this bug.

**Comment by eternoendless** [comment]
> start setting module version inside a composer.json file in the module. Reading this JSON file does not require to load a PHP file and allow to workaround the problem.

Why not use the `config.xml` file which exists already in all modules for this exact purpose?

**Comment by Quetzacoalt91** [comment]
At the moment, the `config.xml` file is not considered as a definition file of the module but more as a cache. It is not mandatory, PrestaShop itself creates or modifies it and there is as many config_XX.xml as installed lang on the shop...
I took the opportunity to suggest a new way of defining basic properties of a module, and chose `composer.json` because it is widely used in the PHP ecosystem, but this is obviously not the only one (We decided to used yml files for themes for a similar need).

**Comment by sowbiba** [comment]
> Very good idea for a solution by @Quetzacoalt91 : start setting module version inside a composer.json file in the module. Reading this JSON file does not require to load a PHP file and allow to workaround the problem.
> 
> If we introduce this system, we have to be aware 99% of modules will _not_ contain a composer.son at the beginning so it needs to be a fallback system. When we attempt to fetch the module version 1) look inside composer.json and if it cannot be found/read 2) look inside main PHP module class.
> 
> If we implement this "read module version from composer.json" strategy inside the Core we should be able to fix this bug.

An example of usage of solution 2

https://github.com/PrestaShopCorp/ps_mbo/pull/413/files#diff-dd5851563503813f4b4f71e99e321a5b7409389be75b8f7251726baa6369f730R180

**Comment by matks** [comment]
@sowbiba I think this is now solved by https://github.com/PrestaShop/PrestaShop/pull/31137 wdyt ?

**Comment by matks** [comment]
I think https://github.com/PrestaShop/PrestaShop/pull/31137 solves this problem 😉 so I close the issue. If I made a mistake please ping me

**Comment by hschoenenberger** [comment]
> I think #31137 solves this problem 😉 so I close the issue. If I made a mistake please ping me

@matks The bug is still there, creating a module with `actionDispatcherBefore` hook you can reproduce it. So far I tested with PrestaShop 1.7.8.8, 8.1.5, 8.2 & nightly.
