### ISSUE TITLE
BO - Import - Popup for data import has non-escaped text

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29959]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I do an import, at the end, there's a popup.
This popup should not have non escaped text:
<img width="611" alt="Screenshot 2022-10-11 at 14 18 05" src="https://user-images.githubusercontent.com/16019289/195101627-c73ba188-6a4b-4844-9690-df1c7b4342c7.png">

It's a regression, it 1.7.8.7, it looked normal:
<img width="607" alt="Screenshot 2022-10-11 at 15 21 19" src="https://user-images.githubusercontent.com/16019289/195102313-ec91cdc7-ef20-44ec-bc2c-078187426766.png">

### Expected behavior

I should see the text without the HTML elements.

### Steps to reproduce

1. Go to BO > Advanced Parameters > Import
2. Download import file of your choice
3. Choose your file to import > match all fields > Import
4. See the popup appear at the end

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanks for reporting the issue.
I reproduce the issue with **PS1778 OK , PS1787 OK , develop / ps80x NOK ,  and PS800 OK ,**
see the attached screen shot for develop/80x 
![Import • prestashop](https://user-images.githubusercontent.com/31663369/195117731-5e4018e2-9fb5-4329-8902-1d6c10aa8818.png)

see the attached screen shot for 800 

![Import • rc_800](https://user-images.githubusercontent.com/31663369/195117633-711421c7-070f-476c-9a6a-110bdbf5c598.png)

Thank you !

**Comment by thomasDelaporte** [comment]
Hey,

It seems to me to be related to the modification of @yanmakouf (#29584) . If I understand a little the differences between 1.7.8 and 8.0.x, before the function `htmlspecialchars` was applied only on the text so in our case "[1]%percentage%[/1]% validated" while now the whole translation with the tags is passed in this function what makes that it is displayed as text.

I can't go further in solving the problem because I don't know the reasons of these changes.

For a quick solution, we can add the attribute html="true" in the template: 
`{l s="[1]%percentage%[/1]% validated" sprintf=[
                '[1]' => '<span id="validate_progression_done">',
                '%percentage%' => '0',
                '[/1]' => '</span>'
                ] d="Admin.Advparameters.Notification" html="true"}`

Good luck!

**Comment by eshraw** [comment]
Is it related to #29940 ?

**Comment by thomasDelaporte** [comment]
It seems related, I have the same problem where in the method `replaceSpecialCharsWithLegacyFunctions`, the variable `$message` includes the whole sentence:

For example `<b>Visiteur</b> - Toutes les personnes n'ayant pas de compte client ou n'étant pas identifiées.` and that if I do a `htmlspecialchars` it makes it display as text and more as an HTML element.

![code](https://user-images.githubusercontent.com/55890466/200386978-933882bd-59a8-4438-aced-a0c38c88e1fb.png)

**Comment by jolelievre** [comment]
Fixed by #30415

**Comment by nagarou-fr** [comment]
Hello,
I can confirm that this issue is still present in PrestaShop 8.2.3.
When importing data through the Back Office, the completion popup still displays non-escaped HTML text. Instead of showing a clean progress message, the raw HTML tags (like <span id="validate_progression_done">) are visible as plain text.
I'm attaching a screenshot showing the issue on version 8.2.3.  

<img width="728" height="220" alt="Image" src="https://github.com/user-attachments/assets/5053db7a-a149-4cb4-a7dd-1576ea2b3d05" />
