### ISSUE TITLE
Webservice - The category isn't well displayed 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#30987]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you go on on [your shop]/api/catogeries/4, you'll have an error with a different display different from usual as you can see : 

![image](https://user-images.githubusercontent.com/100699445/213742639-d8f20831-a683-404b-bfbe-8fa7bbdacb12.png)

For information this one is present on 8.0.1 and 8.0.x and not on develop 

### Expected behavior

We need to have this type of visual : 
![image](https://user-images.githubusercontent.com/100699445/213743254-39392ab4-cdcf-412f-a239-49d3b6678555.png)

### Steps to reproduce

1. Go to BO 
2. Be on PHP 8.0 or more 
3. Go to Advenced Parameters > Webservice 
4. Set up your Webservice 
5. Go to  [your shop]/api/catogeries/4
6. See error 

### PrestaShop version(s) where the bug happened

8.0.1 - 8.0;x

### PHP version(s) where the bug happened

8.0 or more

**Comment by AureRita** [comment]
Hi @MatShir ! 

About this issue, we have an issue that seems to show the same problem : https://github.com/PrestaShop/PrestaShop/issues/29666

But this one should be corrected on 8.0.1 or 8.0.X as you can see : 
https://github.com/PrestaShop/PrestaShop/pull/29756

did we keep this issue ? even if this one can't be reproducted on develop ?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team it seems this regression doesn't occur on develop.
So should we fix this issue only on branch 8.0.x or close this issue as it will be fixed when we merge develop into 8.0.x??

**Comment by danilocarta** [comment]
Hello I found the problem at classes/webservice/WebserviceOutputBuilder.php 717
you need to change this condition from:

```
 if ($field_name == 'id' && !isset($field['sqlId'])) {
                    $field['sqlId'] = 'id';
                    $field['value'] = isset($object_assoc['id']) ? $object_assoc['id'] : null;
                } elseif (!isset($field['sqlId'])) {
                    $field['sqlId'] = $field_name;
                    $field['value'] = isset($object_assoc[$field_name]) ? $object_assoc[$field_name] : null;
                }
```
to:

    ```
            if (
                    ($field_name == 'id' && !isset($field['sqlId']))
                    || (!$field_name && !isset($field['sqlId']))
                ) {
                    $field['sqlId'] = 'id';
                    $field['value'] = isset($object_assoc['id']) ? $object_assoc['id'] : null;
                } elseif (!isset($field['sqlId'])) {
                    $field['sqlId'] = $field_name;
                    $field['value'] = isset($object_assoc[$field_name]) ? $object_assoc[$field_name] : null;
                }
```

**Comment by hibatallahAouadni** [comment]
Hello @danilocarta

I see you manage to get the problem fixed, so please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
I also have the same issue, but with a different error :
It happens on all element, categories or others

<img width="746" alt="Screenshot 2023-02-07 at 15 00 17" src="https://user-images.githubusercontent.com/16019289/217265819-efd6096e-a8fb-4de0-98a2-b9100932bf5e.png">

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31023

**Comment by HassanKapadia** [comment]
Hello there,

The issue mentioned here: https://github.com/PrestaShop/PrestaShop/issues/30987#issuecomment-14208234370
is still not fixed by #31023 and appears in 8.1.0-beta.1

Edit: Issue created with details: #31698 

![image](https://user-images.githubusercontent.com/74450062/224048415-de10544a-b503-46a8-8fea-7d2836527a4b.png)
