### ISSUE TITLE
Updating module during development does not work

### ISSUE THREAD

**Issue by mxmus** [PrestaShop/PrestaShop#30980]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Before updating to PrestaShop 8.0.1 (from 1.7.8.8 using 1-Click Upgrade) I used the following method to upgrade database for my module:
1. I was creating upgrade file like upgrade-0.0.18.php (with code to modify database or make any other changes)
2. I changed version of my module in constructor like $this->version = '0.0.18';
3. I went to Module Manager and saw Updates tab marked like Updates (1) - 1 update available
4. I open tab Updates and updated module with Upgrade action button

And now this scheme does not work - tab Updates displayed with mark (0) - no updates available.

### Expected behavior

Module updating using Module Manager should work as before.

### Steps to reproduce

1. Install attached module "mxxmus"
2. Go to Module Manager and have found installed module Mxxmus Test (v0.0.1 - by mxxmus) in the Other category
3. Edit mxxmus.php - change string from $this->version = '0.0.1'; to $this->version = '0.0.2';
4. Extract and copy attached upgrade-0.0.2.php to module upgrade folder
5. Refresh Module Manager page
6. In my case I not see Upgrade available label and Upgrade item in action dropdown for Mxxmus Test module
7. Then reset any other module and then refresh page 
8. Now I see Upgrade available label and Upgrade item in action dropdown

[mxxmus.zip](https://github.com/PrestaShop/PrestaShop/files/10517017/mxxmus.zip)
[upgrade-0.0.2.zip](https://github.com/PrestaShop/PrestaShop/files/10517136/upgrade-0.0.2.zip)

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.20

**Comment by sallemiines** [comment]
Hello @mxmus 

Unfortunately your steps  are not clear enough to reproduce the issue ! Could you please provide us  the module/file/code .. that you used ! or more more infos, screenshots, .. 

Waiting for yout feedback ! 
Thank you !

**Comment by matks** [comment]
@mxmus Would it be possible to share the module ZIP? depending on the content of your steps it could be a simple error in your code, not a problem of the system

We have plenty modules and they seem to work fine :/

**Comment by mxmus** [comment]
@matks 

Screen video attached.
I've found the method to have Upgrade action.
Need to reset another module to have PrestaShop updated information about my module.

https://user-images.githubusercontent.com/10479502/214535960-97e2a4b3-82d2-4067-9cb2-d7715484a114.mp4

**Comment by mxmus** [comment]
@matks 
Unfortunately this module uses methods of another my module.
So I think it will be better I create new simple module and test it.

**Comment by mxmus** [comment]
@matks 
test module zip attached.
Steps to reproduce:
1. Install attached module "mxxmus"
2. Go to Module Manager and have found installed module Mxxmus Test (v0.0.1 - by mxxmus) in the Other category
3. Edit mxxmus.php - change string from $this->version = '0.0.1'; to $this->version = '0.0.2';
4. Extract and copy attached upgrade-0.0.2.php to module upgrade folder
5. Refresh Module Manager page
6. In my case I not see Upgrade available label and Upgrade item in action dropdown for Mxxmus Test module
7. Then reset any other module and then refresh page 
8. Now I see Upgrade available label and Upgrade item in action dropdown

[mxxmus.zip](https://github.com/PrestaShop/PrestaShop/files/10517017/mxxmus.zip)
[upgrade-0.0.2.zip](https://github.com/PrestaShop/PrestaShop/files/10517136/upgrade-0.0.2.zip)

**Comment by hibatallahAouadni** [comment]
Hello @mxmus 

Thanks for your feedback and your patience 🙏 
Ping @PrestaShop/prestashop-core-developers could you please try to reproduce it 🙏 

PS: @Progi1984 it seems that the issue bot didn't work last week 😞 

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni Ping @PrestaShop/committers for issuebot ;) (Sorry, it's the committers scope).

**Comment by hibatallahAouadni** [comment]
Hello @mxmus 

Do you still encounter the issue with PS81x? Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment]
@mxmus It's because the module list is cached for some reason. 

And the clearing mechanism doesn't work properly in versions lower than 8.0.5.

**Comment by mxmus** [comment]
> Hello @mxmus
> 
> Do you still encounter the issue with PS81x? Please check and feedback.
> 
> Thanks!

Yes. The problem is still present in PS 8.1.1.

**Comment by globalworming** [comment]
can reproduce in PS 8.2.3: 
- edit `PrestaShop/modules/ps_banner/ps_banner.php` and increment the version 
```diff
        $this->tab = 'front_office_features';
-       $this->version = '2.1.2';
+       $this->version = '2.1.3';
        $this->author = 'PrestaShop';

```
- refresh module manager page -> no new update noted
- run `console cache:clear` 
- refresh page -> new update visible

**Comment by AureRita** [comment]
Hello ! 

Thank you for your report, I tried to reproduce it on 9.0.3 and I currently can"t as you can see : 

https://github.com/user-attachments/assets/7d8c876a-5870-45b7-96df-819ecfc019fa

Did I miss something ? 
Maybe this one is fixed on v9, Moreover, if the issue is because of cache, you can disable it on 
BO > Advanced Parameters > Performance 

Waiting for feedback

**Comment by boo-code** [comment]
Still reproduces on 9.2.0, and the reason the reproductions on this thread contradict each other is the editing method, not the version.

@globalworming's recipe measured through the real `ModuleRepository` service:

```
1. version from repository: 2.1.2   (dir mtime=1788692124, file mtime=1788692124)
2. file on disk now says:   9.9.9   (dir mtime=1788692124, file mtime=1788692441)
3. version from repository: 2.1.2   <-- stale
```

**Root cause.** `ModuleRepository::getModule()` decides whether its cached entry is still fresh with `filemtime($this->getModulePath($moduleName))`, and `getModulePath()` checks `is_file()` on the main class but returns the **folder** (`src/Core/Module/ModuleRepository.php`). A directory's mtime only moves when an entry is added, renamed or removed inside it - not when a file it already holds is edited. Measured:

```
in-place edit of mymod.php               file mtime moved, folder mtime UNCHANGED   -> stale
adding a new upgrade/ subdirectory       folder mtime moved                         -> invalidated
adding a 2nd file to an existing upgrade/  folder mtime UNCHANGED                   -> stale
```

So bumping `$this->version` in the main class - the one change this workflow is built on - is invisible to the cache, while `cache:clear` or resetting another module wipes the entry and makes the update appear. That matches @Hlavtox's read that the list is cached and the clearing is what differs.

**Why @AureRita could not reproduce it on 9.0.3 and @globalworming could on 8.2.3.** It depends on how the file is written, not on the version. `sed -i`, most editors' atomic-save, and any unzip/deploy write a *new inode* and rename it into place, which does move the folder's mtime and hides the bug completely. A true in-place write (truncate and rewrite, inode preserved) does not. Both observations are correct; they were editing the file differently.

The reporter's step 4 has the same split: dropping `upgrade-0.0.2.php` into a module that has no `upgrade/` folder yet creates a directory entry and invalidates the cache by luck, while adding another script to an `upgrade/` folder that already exists does not.

A fix is prepared: keep the folder's mtime in the check and add the main class file's own, since every attribute cached for a module is read from that file. `getModulePath()` is public and stays as it is; the file mtime is computed in a private helper. Covered by an integration test that pins the folder mtime with `touch()` so the case is deterministic, and reverting only the repository change fails exactly that test.

One note for whoever picks this up: #42272 also edits `ModuleRepository::getModule()`, on the two `return` statements rather than the mtime computation, and adds a constructor argument - so whichever lands second needs a trivial rebase of the test's `new ModuleRepository(...)` call.
