### ISSUE TITLE
Autoupgrade 8.0.2 to 8.0.3 error database update

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#32131]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When AutoUpgrade tries to upgrade from version 8.0.2 to version 8.0.3, an error occurs when updating the database.

`[INTERNAL] /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result #0 
/var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys() #1 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute() #2 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run() #3 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand() #4 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #5 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun() #6 
/var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #7 
/var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run() #8 
/var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() #9 
/var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #10 
/var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb() #11 
/var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 
/var/www/vhosts/blanolove.pl/httpdocs/admin1965i5ry5datq5wbm2f/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

### Expected behavior

I expected a successful update.

### Steps to reproduce

Go to autoupgrade module and update prestashop 8.0.2 to 8.0.3
Finally, when updating the database, I get an error.

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_autoupgrade

### Your company or customer's name goes here (if applicable).

Grafidea

**Comment by amazingballzs** [comment]
I had too a similar error, was caused by the fact I have a prefix for the database tables different from ps_ and prior to update from 8.0.2 to 8.0.3 I updated the psgdpr module, which has a bug and in its version 2.0.0 can work only if the tables prefix is ps_.

Read in this post about this issue https://github.com/PrestaShop/psgdpr/pull/208

I then tried to upgrade from prestashop 8.0.2 to 8.0.3 without having first updated psgdpr, the upgrade process ended well but the psgdpr module was updated to version 2.0. causing other kind of problems as this causes the effect to have the old table yourprefix_psgdpr_log being abandoned and to have a new empty ps_psgdpr_log table created, so the logged data is left behind in the old table and a new table with default ps_ prefix is going to be used.

In practice if one used the default ps_ prefix for the database tables is not going to notice errors, who used a different prefix for the tables if updated the psgdpr module will not be able to autoupgrade, if did not update the psgdpr module will be able to autoupgrade but will run into problems as will have one table using a different prefix.

Overall very messy and baffling, in fact if one prior to update/autoupgrade tries to change the prefix to the default ps_ one do get other kind of troubles with 500 internal sever errors in the back office if debug is disabled, if debug is enabled all works fine but cannot figure out which are the problems., also I found no documentation about how to change tables prefix in PS 8, the only info I got is that one has to change the names of the tables and change a line in a file in /app/config/parameters.php, but obviously that is not enough at all... truly baffling and seriously annoying

**Comment by eveneme** [comment]
I have a standard database prefix. Upgrading from 8.0.1 to 8.0.2 was successful without any errors. From 8.0.2 to 8.0.3 there is a problem.

**Comment by AureRita** [comment]
Hi @eveneme 

Thank you for your report, I tried to reproduce your issue, even with the different database's prefix, but I can't reproduce it, as you can see : 

[Untitled_ Apr 13, 2023 11_57 AM.webm](https://user-images.githubusercontent.com/100699445/231727292-487b562e-18c8-4d47-9606-b3e3f43f3996.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by MatShir** [comment]
The bug is fixed for the upgrade. We have revert the release and the module is not upgradeable from the 1-clickupgrade or in the BO in the Module manager. But the bug is still present and keep this https://github.com/PrestaShop/PrestaShop/issues/32138 open. 
Thanks @nicosomb & @amazingballzs for being reactive!

**Comment by eveneme** [comment]
When and how can I update to 8.0.3 without problems?

**Comment by MatShir** [comment]
It should be working, now! 
The module will not interfere anymore in the shop upgrade process.
I suggest you try on local or preprod to make sure (and don't forget backup).

FYI, an [8.0.4](https://github.com/PrestaShop/PrestaShop/issues/31979) with a security fix will be available soon

**Comment by eveneme** [comment]
Not working: update DB:

[INTERNAL] /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result #0 /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys() #1 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute() #2 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run() #3 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand() #4 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #5 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun() #6 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #7 /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run() #8 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() #9 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #10 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb() #11 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/vhosts/blanolove.pl/httpdocs/admin1965i5ry5datq5wbm2f/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

**Comment by MatShir** [comment]
We have fixed this issue https://github.com/PrestaShop/PrestaShop/discussions/32348 that blocked the upgrade. Don't really think it is related, but I'm still share in case. 
Hope you will find what cause your issue, so we can find a fix

**Comment by eveneme** [comment]
Upgrading from 8.0.2 to 8.0.4 still the same problem.

`[INTERNAL] /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result #0 /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys() #1 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute() #2 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run() #3 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand() #4 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #5 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun() #6 /var/www/vhosts/blanolove.pl/httpdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #7 /var/www/vhosts/blanolove.pl/httpdocs/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run() #8 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() #9 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #10 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb() #11 /var/www/vhosts/blanolove.pl/httpdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/vhosts/blanolove.pl/httpdocs/admin1965i5ry5datq5wbm2f/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`
