### ISSUE TITLE
Raw HTML displayed in notifications area

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#32216]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

See screenshots.

New product page:
https://capture.dropbox.com/2X1VCpqrvcaW5lDN

Dashboard:
https://capture.dropbox.com/nWPC6GwtwH1OmVJi

### Expected behavior

There should be a link instead of plain HTML.

### Steps to reproduce

1. Visit the back office of clean installation.
2. Click on the notifications bell, you'll see the new order
3. Clic on Catalog
4. Clic on the notifications bell

### PrestaShop version(s) where the bug happened

8.1.0 - 8.0.3

### PHP version(s) where the bug happened

7.4

**Comment by eternoendless** [comment]
This one is a regression on the 8.0 branch

**Comment by AureRita** [comment]
Hi @kpodemski  ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.0.3 and not with the version 1.7.8.9, as you can see : 

![image](https://user-images.githubusercontent.com/100699445/233402806-072ad6c6-b629-42b6-8654-57837ce6459e.png)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by eternoendless** [comment]
Fixed in #32215

**Comment by Tofandel** [comment]
Using prestashop 8.1.1 this issue is still present (at least in the french language), the fix is not working properly

**Comment by kpodemski** [comment]
@Tofandel 

Screenshot from 8.1.1:
https://capture.dropbox.com/tZ3BStlrPayKi90W

**Comment by Tofandel** [comment]
Is it develop or really 8.1.1 ?

Looking at the source I see 
```php
    protected function trans($id, array $parameters = [], $domain = null, $locale = null)
    {
        if (isset($parameters['_raw'])) {
            @trigger_error(
                'The _raw parameter is deprecated and will be removed in the next major version.',
                E_USER_DEPRECATED
            );
            unset($parameters['_raw']);

            return $this->translator->trans($id, $parameters, $domain, $locale);
        }

        return htmlspecialchars($this->translator->trans($id, $parameters, $domain, $locale), ENT_NOQUOTES);
    }
```

Which explains why

It seems it was changed again after https://github.com/PrestaShop/PrestaShop/pull/31900/files

**Comment by kpodemski** [comment]
@Tofandel it's 8.1.1, the fix was introduced in 8.0.5:
https://github.com/PrestaShop/PrestaShop/pull/32215

and then merged to 8.1.x, so if you search for the code differences you should take a look at this file:
https://github.com/PrestaShop/PrestaShop/pull/32215/files

**Comment by Tofandel** [comment]
That's my point, in the meantime the `_raw` parameter has been deprecated and even completely removed 

See https://github.com/PrestaShop/PrestaShop/blob/8.1.x/classes/controller/Controller.php#L354

In develop this seems fixed, so I believe there was a wrong merge somewhere

**Comment by Tofandel** [comment]
It was also there on 8.x https://github.com/PrestaShop/PrestaShop/blob/8.0.x/classes/controller/Controller.php#L354

Introduced by

https://github.com/PrestaShop/PrestaShop/commit/7c9200c123185f7e17c2606fa70ad9f08af87acf

This method has been fixed and unfixed times and times again, now it seems the merge to 8.0 and 8.1 is the broken version

**Comment by Tofandel** [comment]
Okay NVM, I had 2 versions open, one on 8.0.4 and one on 8.1.1, it's working correctly

Sorry for the false alarm

**Comment by Tofandel** [comment]
So then just adding a note that the fix will actually not work on develop because `_raw` was removed, and https://github.com/PrestaShop/PrestaShop/pull/31900 did not include this notification in the list of changes

**Comment by kpodemski** [comment]
It works on the develop, no worries 👍🏻 
Screenshot:
https://capture.dropbox.com/12AB4XhOsejyOzLu
