### ISSUE TITLE
PPV2 + Multiple image formats : WebP is not generated when a cover image is uploaded

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32265]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

WebP is not generated when a cover image for product is uploaded

### Expected behavior

WebP is generated when a cover image for product is uploaded

### Steps to reproduce

1. Enable Product Page v2
2. Enable Multiple image formats
3. Enable WebP in Image Format page
4. Create a product with a JPEG/PNG/WebP file for cover
5. The `img/p/{idProduct}/{idProduct}.jpg` exists and is a WEBP file => **ERROR**
6. The `img/p/{idProduct}/{idProduct}-cart_default.jpg` exists and is a JPEG file => **OK**
7. The `img/p/{idProduct}/{idProduct}-cart_default.webp` exists and is a WEBP file => **OK**
8. When I go on the front office
9. The `img/p/{idProduct}/{idProduct}-cart_default.webp` is generated.

#### Acceptance Test
Remove the `.skip` rule 
https://github.com/PrestaShop/PrestaShop/blob/d72b2235a746a79ea7f487d05255548a2882b63a/tests/UI/campaigns/functional/BO/08_design/06_imageSettings/13_checkProductImageFormat.ts#L246-L247

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.3

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Progi1984** [comment]
It's not a bug. Sorry.

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Tested on `develop` branch.

I don't see the option to Enable Multiple image formats.
This is what I have chosen:
<img width="468" alt="Screenshot 2023-04-28 at 15 12 18" src="https://user-images.githubusercontent.com/16019289/235157061-e3ee0d58-78a0-4a35-aba3-9fe20e60e68d.png">

Even after regenerating all the images for my product, the images are .jpg instead of .webp.

Is that the issue ?

**Comment by Progi1984** [comment]
@florine2623 You can enable it on the "New & Experimental Features" page

![image](https://user-images.githubusercontent.com/1533248/235623602-d6ce03f2-47f8-4e93-9d0f-882a526572fa.png)

Sorry. I fixed : it's not on 9.1.x but 8.1.x.

**Comment by AureRita** [comment]
Hi @Progi1984,

I reproduce the issue with PrestaShop version 8.1 and not with the version 8.0.1 as you can see : 

[Untitled_ May 4, 2023 5_45 PM.webm](https://user-images.githubusercontent.com/100699445/236261147-d1b4ef16-38dc-4790-8b4b-209bda059f42.webm)

Nice catch ! It's a regression on a new feature ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by 0x346e3730** [comment]
Hey @kpodemski I've changed this issue to blocked as I see [you've blocked the PR for it](https://github.com/PrestaShop/PrestaShop/pull/32615#pullrequestreview-1439091612), can you elaborate ? What needs to be done to unblock this issue ?

**Comment by kpodemski** [comment]
@0x346e3730 I didn't understand why to handle different type we need to provide imageId, it didn't make sense for me when I blocked it, neither for @Hlavtox

**Comment by M0rgan01** [comment]
@kpodemski Thank you for the feedback. I completed the description of the PR, to explain the changes.

**Comment by MatShir** [comment]
Fixed by #32615

**Comment by Progi1984** [comment]
I reopen the issue.

The UI test is not fixed.

The image is well generated `img/p/{idProduct}/{idProduct}-cart_default.jpg` but it's not a WebP image. I added it a acceptance test.

**Comment by Hlavtox** [comment]
@Progi1984 img/p/{idProduct}/{idProduct}-cart_default.jpg should be a JPG/PNG image, not a webp image.

**Comment by Progi1984** [comment]
I check... and I looked up again the intial scenario.

You're right.

The `img/p/{idProduct}/{idProduct}.jpg` should be at the original format of the uploaded file.
The `img/p/{idProduct}/{idProduct}-cart_default.jpg` should be a JPEG (or PNG if the uploaded file is a PNG)
The `img/p/{idProduct}/{idProduct}-cart_default.webp` should be a WebP.

So it's not fixed.

I updated the "Steps" and the UI test.

**Comment by MatShir** [comment]
Not sure to understand, the PR went through QA & QA autom. Everything was validated 🤷

**Comment by Hlavtox** [comment]
@Progi1984 The img/p/{idProduct}/{idProduct}.jpg should be at the original format of the uploaded file. - not sure about this, it should be converted to JPG/PNG.

Ping @kpodemski

**Comment by Progi1984** [comment]
@Hlavtox So it's the original file ? I have not this information.

**Comment by MatShir** [comment]
closed by https://github.com/PrestaShop/PrestaShop/pull/34172
