### ISSUE TITLE
Bug using template for import function: Saved configuration is not working

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#32798]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you create an tamplate for importing items in the store and you want to load it the columns of the template won't be set properly.

### Expected behavior

Import columns should be set.

### Steps to reproduce

1. Go to the import page in the Backoffice
2. Choose something to import
3. Go to the nex page to asign the collumns of your document.
4. Save your template.
5. Go back to te start page
6. Go to the next page to set the columns again.
7. Try to load your saved template.

### PrestaShop version(s) where the bug happened

1.7.8.7 , 8.2

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

MARK-APP

**Comment by mark-app** [comment]
I have created an fix for it.

in the file js/admin/import.js on line 78 change:

`$('#type_value\\['+i+'\\]').val(matchs[i]).attr('selected',true);`

to:

`$('#type_value\\['+i+'\\]').val(matchs[i]).attr('selected',true).trigger("chosen:updated");`

I don't use git so maybe someone can add it to fix this in the next update for PS 8 and PS 1.7.8.

**Comment by AchrafKchaou1991** [comment]
Hello @mark-app 
I tried to reproduce the issues using PS 8.0 .2
Did I miss any steps?

[Untitled_ Jun 2, 2023 12_45 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/0da16dd6-18f9-4b1d-9c61-8f513830874d)

Waiting for your feedback,
Thank you

**Comment by mark-app** [comment]
I had the problem with the product import in firefox.

**Comment by AureRita** [comment]
Hi @mark-app 

Thank you for your report and your details,I reproduce the issue with PrestaShop version 8.0.4 and not with the version 1.7.8.9 as you can see : 

[Untitled_ Jun 2, 2023 3_16 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/3d3237c0-3763-4365-a91c-ad3af31e2662)

 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mark-app** [comment]
@AureRita 

I already fixed the issue. See my second comment:



> I have created an fix for it.
> 
> in the file js/admin/import.js on line 78 change:
> 
> `$('#type_value\\['+i+'\\]').val(matchs[i]).attr('selected',true);`
> 
> to:
> 
> `$('#type_value\\['+i+'\\]').val(matchs[i]).attr('selected',true).trigger("chosen:updated");`
> 
> I don't use git so maybe someone can add it to fix this in the next update for PS 8 and PS 1.7.8.

**Comment by AureRita** [comment]
Oh yes, indeed, you can [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/)  to help other person that have this issue

**Comment by doominio** [comment]
It seems I was commenting on a closed duplicate of this issue. Load Saved Configuration doesn't work for me on Safari or Firefox. The proposed fix above doesn't fix it for me on either browser. The delete button brings up an error window with the text "TECHNICAL ERROR Details: ".

**Comment by doominio** [comment]
Proposed fixes are here, they involve editing two files (js and php):

https://github.com/PrestaShop/PrestaShop/issues/32416#issuecomment-1533660028
https://github.com/PrestaShop/PrestaShop/issues/32416#issuecomment-1533728714

I can confirm they worked for me in 8.1.0 with php 7.4.33.

**Comment by ShaiMagal** [comment]
> Proposed fixes are here, they involve editing two files (js and php):
> 
> [#32416 (comment)](https://github.com/PrestaShop/PrestaShop/issues/32416#issuecomment-1533660028) [#32416 (comment)](https://github.com/PrestaShop/PrestaShop/issues/32416#issuecomment-1533728714)
> 
> I can confirm they worked for me in 8.1.0 with php 7.4.33.

I confirm, same here (3 eshops tested PS 8.x, PHP 8.1)

**Comment by ShaiMagal** [comment]
I think this can be closed, this should by fixed by PR #34438
