### ISSUE TITLE
Specific prices - drop down with combinations not populated by combinations

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33261]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a product with combinations
If you go to the pricing-tab
And want to add (or edit) a specific price
There is a drop-down which should give you the opportunity to choose a specific combination (to specifiy that the specific price rule should only be applied to that specific product combination).
But this drop-down is currently not populated correctly, as it only include 2 options: 

- A blank option (no value, no text, nothing, just blank)
- "All combinations"

![chrome_VQYHnKEEnU](https://github.com/PrestaShop/PrestaShop/assets/26773745/0f32d309-f4c1-460d-bd85-4a04843ace80)

I can then just add a price rule for "All combinations", and then manually edit the database by inserting the desired id_product_attribute for that specific price rule (in the "ps_specific_price"-table) ... and if I do so, the abovementioned drop-down is now still only populated with 2 options:

- A blank option
- And the specific combination that I specified manually in the database

![chrome_7e7UGh380E](https://github.com/PrestaShop/PrestaShop/assets/26773745/84038bef-4790-47a0-bc5a-de86c92d5e07)
bination that I specified manually in the database

### Steps to reproduce

1. Go to the "back office"
2. Go to Catalog > Products
3. Find a product with combinations (or create one if there isn't one already)
4. Edit that product and go to the pricing-tab
5. Add (or edit) a specific price
6. Notice that the drop-down where you should be able to select a specific combination is not populated correctly.

![chrome_VQYHnKEEnU](https://github.com/PrestaShop/PrestaShop/assets/26773745/4ddab609-5f55-4b19-8d23-fee4ce3fbb32)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by aniszr** [comment]
Hello @LarsGMortensen 

I managed to reproduce this issue only with 8.1.0, it's a regression as we have the expected behavior with PS804 and Product Page V2, see the attached screen record below:

https://github.com/PrestaShop/PrestaShop/assets/92626242/b26dfcde-cfd8-4d64-a57b-96dc62977585

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you.

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by boherm** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33458

**Comment by LarsGMortensen** [comment]
Hi @boherm It sounds great that it should now be fixed. Do you know when it will be released? :) ...I am currently on 8.1.1 and its still not working :)

**Comment by Naprosnia** [comment]
I apply the correction from #33458 to the files in PS8.1.1 on my store, and the problem still persists.

**Comment by claudiodex61** [comment]
I also modified the files, I deleted the cache but the problem persists. my PS is 8.1.0

**Comment by Naprosnia** [comment]
> I also modified the files, I deleted the cache but the problem persists. my PS is 8.1.0

When PS 8.1.2 was released, I updated it, and the problem was resolved.
