### ISSUE TITLE
Customers cannot delete their address / Error message 

### ISSUE THREAD

**Issue by MONA4GITHUB** [PrestaShop/PrestaShop#33353]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop version: 1.7.8.8 
Php version: 7.4.33
Server version :  Linux #1 SMP Sun Nov 21 10:56:33 EST 2021 x86_64

In the front office, the customers cannot delete their address, they got the error message : Could not delete address. 

I did a troubleshooting session to found the issue, I can reproduce the problem with the classic theme, so the problem is not related to the theme. 

Could you please help me to fix it ? 

Regards. 
Mikael 

### Expected behavior

Customers click on "Remove Address" then the address is removed with confirmation message. 

### Steps to reproduce

1. Connect to https://maisonmarylor.com
2. Create an account 
3. Log on 
4. Create Test address 
5. Try to delete Test address 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @MONA4GITHUB ,

Is your error this one : `Could not delete the address since it is used in the shopping cart.` ?
<img width="1104" alt="Screenshot 2023-07-24 at 14 33 16" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0ac55264-9930-4987-9b90-06e3aff74e0d">

If that's the case, that's normal. Your customer needs to have at least one valid address for the delivery. They can delete it in their cart directly.

**Comment by Hlavtox** [comment]
@florine2623 Yeah it's this one `Could not delete the address since it is used in the shopping cart.`

However, I did not add anything to cart, it should be deletable I think. 🤔

**Comment by MONA4GITHUB** [comment]
@florine2623 @Hlavtox No, it's not this one. Please check below 
![254870190-623f31fc-8ebe-481d-8570-a32bcd6ba645](https://github.com/PrestaShop/PrestaShop/assets/127497359/8e201bca-c80c-4d17-bf18-8c40a0761ead)

**Comment by florine2623** [comment]
@MONA4GITHUB ,

Can you try, as a customer, to add another address and see if you can delete the first address created ?
Also try from the checkout process - Step 2 address.

@Hlavtox ,

> However, I did not add anything to cart, it should be deletable I think. 


Indeed, I agree with you on this point

**Comment by MONA4GITHUB** [comment]
@florine2623 I already tested it and it's not possible to delete the address. That's why I posted my message and looking for help. From the customer account or checkout, same issue, same error message.

**Comment by venditdevs** [comment]
Same problem here, sometimes (maybe not related) when a customer tells this to us, we also see a product with the quantity of 0 in the cart which cannot be deleted by the customer also.

**Comment by florine2623** [comment]
Hello @MONA4GITHUB @venditdevs ,

This issue is fixed on later version like `8.0.4`, `8.1` and future version `develop`.

As this issue is only reproduced on 1.7.8., I will close it.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by venditdevs** [comment]
> s fixed on later version like `8.0.4`, `8.1` and future version

Hello Florine,

My information was just for pointing out that we encounter the same problem, but in this case on Prestashop 8.0.4 / PHP 8.1. So it is not fixed in 8.0.4. If you can confirm that the problem is indeed, 100% sure, found and solved in 8.1.1 then you can leave it for what it is, otherwise i would recommend to reopen this issue for further investigations.

**Comment by MONA4GITHUB** [comment]
Hi, 

Just for information, I occurred the same problem on another shop then the issue has been fixed with the upgrade 1.7.8.10

BR

**Comment by venditdevs** [comment]
> ly reproduced on 1.7.8., I will close it.
> 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
> 
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Hello @florine2623, this problem is still present on version 8.0.5. Can you please confirm it is indeed solved in version 8.1.X?

**Comment by venditdevs** [comment]
@Hlavtox, can you please take a look into it? Florine does not respond anymore.
