### ISSUE TITLE
PHP do not allow some values on products that DB do.

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#33371]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Database on product table for isbn, upc, ean13, mpn and reference all allow null values, default value is also null.
However, if these columns get a null value you will not be able to access the product in BO due to 
"Argument 1 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductDetails::__construct() must be of the type string, null given".

### Expected behavior

If the DB defaults a null value then it should also work in the code.

### Steps to reproduce

1. edit data in database table ps_product
2. set isbn to null on any product
3. access that product from BO

(It still works in FO)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.9

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by florine2623** [comment]
Hello @Prestaworks ,

I have reproduced your issue on PS 8.1. I'll add this to the backlog so it can be fixed.
It is a regression, as I couldn't reproduce it with 1.7.8.9 and 8.0.4.

Here's the exception on BO :
<img width="1064" alt="Screenshot 2023-07-25 at 14 57 57" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5e563421-abce-46ec-843d-c909e59023de">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Prestaworks** [comment]
the php code can be updated, all null values would change to empty strings when saving in BO. But not sure if that is the proper solution, maybe the DB should be altered to not accept null values instead? Maybe the devs have some ideas?

**Comment by Hlavtox** [comment]
Most information - https://github.com/PrestaShop/PrestaShop/issues/22215
Duplicates:
- https://github.com/PrestaShop/PrestaShop/issues/25996
- https://github.com/PrestaShop/PrestaShop/issues/22862
- https://github.com/PrestaShop/PrestaShop/issues/22386
- https://github.com/PrestaShop/PrestaShop/issues/22215

**Comment by Prestaworks** [comment]
> Duplicate of #22862

same issue, different views/objects. Guess the system probobly has more of these.

**Comment by MatShir** [comment]
fixed by https://github.com/PrestaShop/autoupgrade/pull/656

**Comment by Hlavtox** [comment]
@MatShir its not really fixed, the null values can reappear, for example by using a database created with the builtin tool

**Comment by maximus15102006** [comment]
I have got the same problem, after importing products to Prestahop from external stock software. Prestashop 8.1.4 PHP 8.1, so it is definitely not fixed.
