### ISSUE TITLE
Upgrade from 8.0.4 to 8.1 with 4.16.1 autoupgrade = There is no extension able to load the configuration for "api_platform"

### ISSUE THREAD

**Issue by xga91** [PrestaShop/PrestaShop#33504]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried php 8.1 / 7.4, same error upgrade is not working. with 4.16.1 autoupgrade module. Opcache disabled.

But not working at all

```
[INTERNAL] /home/xxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "api_platform" (in "/home/xxx/app/config/config.yml"). Looked for namespace "api_platform", found ""framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "prestashop", "translation_tools", "tactician", "fos_js_routing"" in /home/xxx/app/config/config.yml (which is being imported from "/home/xxx/app/config/config_prod.yml").
#0 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(104): Symfony\Component\Config\Loader\FileLoader->doImport()
https://github.com/PrestaShop/PrestaShop/pull/1 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(66): Symfony\Component\Config\Loader\FileLoader->import()
https://github.com/PrestaShop/PrestaShop/pull/2 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(197): Symfony\Component\DependencyInjection\Loader\FileLoader->import()
https://github.com/PrestaShop/PrestaShop/pull/3 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(133): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports()
https://github.com/PrestaShop/PrestaShop/pull/4 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load()
https://github.com/PrestaShop/PrestaShop/pull/5 /home/xxx/app/AppKernel.php(211): Symfony\Component\Config\Loader\DelegatingLoader->load()
https://github.com/PrestaShop/PrestaShop/pull/6 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(697): AppKernel->registerContainerConfiguration()
https://github.com/PrestaShop/PrestaShop/pull/7 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(593): Symfony\Component\HttpKernel\Kernel->buildContainer()
https://github.com/PrestaShop/PrestaShop/pull/8 /home/xxx/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer()
https://github.com/PrestaShop/PrestaShop/pull/9 /home/xxx/app/AppKernel.php(93): Symfony\Component\HttpKernel\Kernel->boot()
https://github.com/PrestaShop/PrestaShop/pull/10 /home/xxx/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot()
https://github.com/PrestaShop/PrestaShop/pull/11 /home/xxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
https://github.com/PrestaShop/PrestaShop/pull/12 /home/xxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants()
https://github.com/PrestaShop/PrestaShop/pull/13 /home/xxx/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
https://github.com/PrestaShop/PrestaShop/pull/14 /home/xxx/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
https://github.com/PrestaShop/PrestaShop/pull/15 /home/xxx/xxx/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
https://github.com/PrestaShop/PrestaShop/pull/16 {main}
```

![image](https://github.com/PrestaShop/PrestaShop/assets/101413251/14aa264f-aff0-453f-837d-9e1563c9ad8f)

### Expected behavior

I am trying to upgrade from 8.04 to 8.1

### Steps to reproduce

11 just using autoupgrade module last version 4.16.1, and get this message error.
There is no extension able to load the configuration for "api_platform"

### PrestaShop version(s) where the bug happened

8.04

### PHP version(s) where the bug happened

7.4 / 8.1

**Comment by ghost** [comment]
@xga91
Hello, take a look at this link it is a repeated topic and has been closed.. to be resolved in future updates
https://github.com/PrestaShop/PrestaShop/issues/33041

**Comment by xga91** [comment]
I no run on windows local server, it's online platform, and OPcache is desactivate.
It's not exactly the same error message, maybe related i am not sure...

You have requested a non-existent parameter "api_private_key". #0 
vs

Me i got this message
There is no extension able to load the configuration for "api_platform" (in "/home/xxx/app/config/config.yml").

**Comment by Hlavtox** [comment]
@kpodemski one new issue 🤔

**Comment by kpodemski** [comment]
@Hlavtox There is "Parameters file updated", maybe after this step, there should be Symfony container cleared again 🤔 

https://github.com/PrestaShop/autoupgrade/blob/dev/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php#L49

**Comment by xga91** [comment]
here extract from the log, all files copied ok, clean cache an then come this error message =

[2023-07-30 04:22:02] All files upgraded. Now upgrading database...
[2023-07-30 04:22:02] [SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[2023-07-30 04:22:02] [CLEANING CACHE] File pagecache removed
[2023-07-30 04:22:02] [CLEANING CACHE] File prod removed
[2023-07-30 06:22:03] Parameters file updated
[2023-07-30 06:22:03] [INTERNAL] /home/xxx/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "api_platform" (in "/home/xxx/app/config/config.yml"). Looked for namespace "api_platform", found ""framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "prestashop", "translation_tools", "tactician", "fos_js_routing"" in /home/xxx/app/config/config.yml (which is being imported from "/home/xxx/app/config/config_prod.yml").

**Comment by Hlavtox** [comment]
@kpodemski It should not affect anything. The only file that is getting updated after cache cleaning is `app/config/parameters.php` by adding api key, but the YML is still the same. 🤔

**Comment by sallemiines** [comment]
Hello @xga91 

I didn't manage to reproduce your issue , you can see the attached screen-recorder
`Auto-upgrade module V 4.16 .1 
`
**PS** : I launch the auto-upgrade with local archive option 


https://github.com/PrestaShop/PrestaShop/assets/31663369/00797b27-976c-4c51-973f-166a5238ae0c

Did I miss smthng ? 
Please check and feedback ! 
Thank you

**Comment by xga91** [comment]
i can try with local archive ? and not git download but i think the result will be the same ?
I tried php 7.4.33 or 8.1.19

**Comment by xga91** [comment]
exactly same message error on LOCAL file upgrade...

/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "api_platform"

**Comment by florine2623** [comment]
Hello @xga91 ,

A new version of the module autoupgrade has been released : https://github.com/PrestaShop/autoupgrade/releases/tag/v4.16.2

Could you check with this version and feedback please ?
Thanks!

**Comment by xga91** [comment]
I just tested with 4.16.2. Same error @florine2623 

<img width="347" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/d17787a8-d416-4ffd-9de2-a9d10ae59442">


[INTERNAL] /home/herlib/public_html/XXX/org/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "api_platform" (in "/home/herlib/public_html/XXX/app/config/config.yml").

**Comment by Hlavtox** [comment]
@xga91 Do you think you could post a full log here?

Its located in /adminblablabla/autoupgrade/tmp/log.txt. You can delete the backup part and copying files, and check if there isnt your admin dir somewhere. I want to see where exactly it crashes. 👍

**Comment by xga91** [comment]
yes i can upload the log, but let me time to edit, there's many sensitive infos.

**Comment by xga91** [comment]
@Hlavtox here the FULL LOG file attached
[log1.txt](https://github.com/PrestaShop/PrestaShop/files/12268074/log1.txt)

**Comment by xga91** [comment]
Just an update, Testing upgrade 8.0.5 passed and working. I am going to test upgrade to 8.1.1 and will show the results.
<img width="287" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/0461dae4-2d11-4afe-9951-8e2f94bdaffe">

**Comment by sallemiines** [comment]
Hello @xga91 

Thanx for the feedback ! glad to hear that your probleme is resolved 
We will close this issue 
Feel free to create a new issue if you have any other issues ,we will be glad to investigate it. 

Thank you

**Comment by xga91** [comment]
@sallemiines 
The problem is not resolved !!! the upgrade to 8.1 is not working ! thanks to reopen !!

**Comment by xga91** [comment]
![Sans titre1](https://github.com/PrestaShop/PrestaShop/assets/101413251/e5776f0b-d9fb-4a14-82dd-979704e09826)

Just retesting upgrade from 8.0.4 and from 8.05 still same error to upgrade to 8.1.1 or 8.1

**Comment by xga91** [comment]
@Hlavtox @sallemiines Please reopen the case and add 8.0.5, from 8.0.4, 8.05 same error bug thks here the 2th log file from the latest test.

[log (2).txt](https://github.com/PrestaShop/PrestaShop/files/12322622/log.2.txt)

**Comment by xga91** [comment]
any news ? problem still exist

**Comment by ghost** [comment]
@xga91 
> any news ? problem still exist

Prestashop should not be an open source solution.  Problem like this is not fixed yet!  I always review the open and closed issues and nothing new.  May be it's related to the natural psychological case of the human being who is always looking for something new: Sometimes if you consult the mellistones you can see that the last update for presta 9.0.0 was 1 hour ago, and for presta 8.1.2   3 days ago... I think that if we create a prestashop 10 they will forget the 9 before it ends.

**Comment by xga91** [comment]
I just tested last autoupgrade version 4.16.3, still SAME problem, not possible to upgrade...

Problem still here, any solutions ?

**Comment by kpodemski** [comment]
@xga91 have you ever tried on a different environment? It is **not a global issue**. Only some percent of people experienced it.

**Comment by xga91** [comment]
This is the environment, i tried php 8.1 / 7.4, but same problem..

Maybe i can try nginx ? or apache ?  what can you think is good to try ? @kpodemski 

<img width="1041" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/583ff4f7-29d4-48e6-9c48-2a73df71cda6">
<img width="1047" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/39d28268-2f38-40ea-bbc4-c44c7a922041">

**Comment by matks** [comment]
> @xga91
> 
> > any news ? problem still exist
> 
> Prestashop should not be an open source solution.

Then you want PrestaShop to be a proprietary software and you are ready to pay for it? 😄 Because if it's not open source then why should it be free.

EDIT: For anybody who wants to see this issue fixed, then you can invest into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. PrestaShop is open source and of the most important things about open source is that it gets better because anybody can participate in making it better. If you want more bug fixes, then join in! Please submit bug fixes. If you want more new features, submit new features. One side of the software will get better if people invest in this one side.

And this does not work with proprietary software 😉 . With proprietary software, the software only evolves in the direction set by the owner. Even if 99% of its users want something 😄 and are willing to invest in it, if the owner does not want it, it will not happen. With open source software you have the choice.

**Comment by DaniellaMonet** [comment]
> > @matks 
> > > any news ? problem still exist
> > 
> > 
> > Prestashop should not be an open source solution.
> 
> Then you want PrestaShop to be a proprietary software and you are ready to pay for it? 😄 Because if it's not open source then why should it be free.
> 
> EDIT: For anybody who wants to see this issue fixed, then you can invest into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. PrestaShop is open source and of the most important things about open source is that it gets better because anybody can participate in making it better. If you want more bug fixes, then join in! Please submit bug fixes. If you want more new features, submit new features. One side of the software will get better if people invest in this one side.
> 
> And this does not work with proprietary software 😉 . With proprietary software, the software only evolves in the direction set by the owner. Even if 99% of its users want something 😄 and are willing to invest in it, if the owner does not want it, it will not happen. With open source software you have the choice.
-------------------------
completely off topic, I will wait two days to give you time to edit your text a 3rd and 4th time because it seems that your psychological case requires urgent treatment and it is very clear from the "between the lines" of your text and the smiles that put you in a “serious” development space. so my response is after 48 hours.

**Comment by ghost** [comment]
> > @matks 
> > > any news ? problem still exist
> > 
> > 
> > Prestashop should not be an open source solution.
> 
> Then you want PrestaShop to be a proprietary software and you are ready to pay for it? 😄 Because if it's not open source then why should it be free.
> 
> EDIT: For anybody who wants to see this issue fixed, then you can invest into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. PrestaShop is open source and of the most important things about open source is that it gets better because anybody can participate in making it better. If you want more bug fixes, then join in! Please submit bug fixes. If you want more new features, submit new features. One side of the software will get better if people invest in this one side.
> 
> And this does not work with proprietary software 😉 . With proprietary software, the software only evolves in the direction set by the owner. Even if 99% of its users want something 😄 and are willing to invest in it, if the owner does not want it, it will not happen. With open source software you have the choice.
----------------------
Completely off topic, I will wait two days to give you time to retouch your text a 3rd and 4th time because it seems that your psychological case requires urgent treatment and this is very clear from the "between the lines" of your text and from the nature of the smiles that you place it in a “serious” development space. So my response is after 48 hours.

**Comment by eternoendless** [comment]
@ZoubaierHadden please keep the conversation constructive and respectful. Aggressive behavior will not be tolerated as per the project's [Code of conduct](https://www.prestashop-project.org/code-of-conduct/).

**Comment by xga91** [comment]
I prefer discussing around the problem with autoupgrade, and find a solution to fix it thks ! This guy come and pollute the thread for no reason.

thks in advance !

**Comment by ZoubaierHadden** [comment]
@eternoendless 
Please leave the conversation fair and respectful/.

**Comment by ghost** [comment]
@eternoendless 
Please keep the conversation fair and respectful/. Unfair accusations have serious consequences. [https://www.prestashop-project.org/code-of-conduct/]()

**Comment by DaniellaMonet** [comment]
@xga91
> I prefer discussing around the problem with autoupgrade, and find a solution to fix it thks ! This guy come and pollute the thread for no reason.
> 
> thks in advance !
-------------------------------------
This guy witch "polluate the discussion" gave me the solution for my problem #33985 witch is very similar to your problem, thanks to all the community.

**Comment by xga91** [comment]
@DaniellaMonet  ah interesting, what is the solution daniella ? i no see any reference on your ticket 33985 ?

**Comment by ChillCode** [comment]
@xga91 

Would you mind to post the complete (the list of overrides and modified core files also) result of your `Advanced Parameters->Information` page?

**Comment by xga91** [comment]
@ChillCode here all details

<img width="746" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/9bac3868-51f6-4cf1-a662-0b2689017c86">

<img width="581" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/e866eddc-45a4-4105-874e-80daf3d0729b">

<img width="482" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/e26a2b89-30cd-4c37-a0be-950ba36e4188">

<img width="461" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/101413251/55cfdcc1-9257-49b1-890c-8ee430584c52">

**Comment by DaniellaMonet** [comment]
@xga91 
> @DaniellaMonet ah interesting, what is the solution daniella ? i no see any reference on your ticket 33985 ?
------------
Someone @aniszr closed my issue #33985 as it is "duplicated" . My problem is similar to yours but not identical . I have an api_private_key problem but you have an api_platform problem. These two problems are different.
I found the same issue too of api_private_key  #33041 which was converted to discussion. Why ? I don't know.
Please reopen #33985 
----------------
As @ZoubaierHadden helped me to undrestand the problem ,  I will try to help you to do the upgrade step by step.
What files/folders you have exactly on /home/xxx/app/config/ ?

**Comment by ChillCode** [comment]
Hi @xga91 

I had the exact same issue while upgrading on a dev site. In my case it occurred after an unfinished upgrade because a file permissions issue in the core (which was my fault) caused the autoupgrade to fail. Then, the rollback completed with an strange error don't remember but the site worked. However, when I attempted to upgrade again, I encountered the same message as you did.

I didn't perform a rollback after api_platform issue, and I managed to resolve it. The problem was that the service was not added where it should have been. However, as I continued, I encountered other issues related to Symfony. After resolving two of them, two more appeared. At that point, I decided not to waste any more time and proceeded with a manual upgrade. Now, everything is working smoothly, and I was able to successfully upgrade to version 8.1.1 last week.

The steps i followed:

I removed all PrestaShop files and folders except for images, modules, download, and upload. I retained all folders containing site data. Following that, I performed the database upgrade as outlined in the instructions provided here: [link to the PrestaShop Upgrade documentation](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/).

**Comment by xga91** [comment]
@ChillCode Not good after an update that failed, you encounter many problem trying save it,  it's not a clean upgrade.

Me after the fail upgrade the whole site is in 500 error, all broken.

**Comment by jp-gouin** [comment]
Hi, 
I just ran into the exact same issue and managed to fix it by going into `Advanced Parameters -> Performance` and turn off the cache and cleared it , then I ran the upgrade from `8.0.5` to `8.1.3`

**Comment by gericfo** [comment]
Hello @jp-gouin 
Thanx for your feedback. We will close this discussion as clearing the cache is solving the issue.
Feel free to create a new issue if needed, we will be glad to investigate it.

Thank you!
