### ISSUE TITLE
Route does not exist 

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33550]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Concerning issue when generating a link to a Symfony module route from within a module.  An error is produced stating that the route does not exist even when it does.  The message disappears when enabling debug mode after which correct link to the route is generated,. Therefore the error only occurs when debug mode is disabled.

Attached is a sample module demonstrating the problem.

[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/12267055/testmodule.zip)

### Steps to reproduce

1.  Create a plain Prestashop 8.1.0 Installation
2. Ensure debug mode is disabled
3. Install the test module
4. Go to configure the test module
5. The error message related to route not existing is produced.
6. Now enable debug mode
7. Go to configure the test module
8. Now the routing is succesfull

So the error only occurs when debug mode is disabled.

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.0

**Comment by LouisAUTHIE** [comment]
I think this is a problem of namespace and/or route definition. Please check your module.

**Comment by musaffarpatel** [comment]
@LouisAUTHIE I've double checked the route definition and the controllers, they are correct.  Furthermore the problem disappears as soon as you enable debug mode which is the strange part.  Finally, only seems to occur in Prestashop 8, not 1.7.x.

I attached a test module to demonstrate and allow the problem to be reproduced.

**Comment by kpodemski** [comment]
Hi @musaffarpatel 

Could you try to rework your module to use a new Tabs registration system?
https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/tabs/#how-to-define-a-tab-in-the-menu

Please do that and check if that helps.

**Comment by musaffarpatel** [comment]
Hi

The tabs registration is unrelated to the problem, therefore I have removed it from the test module altogether.  The updated module is attached.  The issue still persists.

[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/12270443/testmodule.zip)

**Comment by ChillCode** [comment]
Hi @musaffarpatel 

Take a look at ps_linklist code and will see that you need a tab to register the route as @kpodemski advised.

**Comment by LouisAUTHIE** [comment]
@musaffarpatel feel free to use that example https://github.com/PacktPublishing/Practical-Module-Development-for-Prestashop-8/blob/main/Chapter%2011/whblog/whblog.php

**Comment by musaffarpatel** [comment]
@LouisAUTHIE Thanks, however I installed the whblog module on fresh Prestashop 8.1.0 but the tab does not appear anywhere in the menu.

@ChillCode I duplicated the tab registration code from ps_linklist module but this does not have any influence on the problem.  I do think this could be a Prestashop bug. 

Attached is the latest testmodule with identical tab registration code from ps_linklist.  As mentioned before the problem appears only when debug mode is disabled.  Enable debug module and the module route works as expected.

Please kindly test the attached module on a fresh PS 8.1.0 install.  The test module code itself is very basic and looks error free.

[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/12296225/testmodule.zip)

**Comment by musaffarpatel** [comment]
Learned a little more about the problem.

To recap, the problem seems to occur on fresh installs of Prestashop 8.0.4 and 8.1.0
The problem occurs when you install the test module while debug mode is **disabled**
After installing the module, if you try to configure the module, the route error is presented.  

Now, if we delete var/cache/prod/UrlGenerator.php the route works correctly.  Clearing the cache from the back office does not fix the issue.  Only deleting the mentioned file manually does.

The problem is that the client will see an error until they remove this file and the last thing a client will want to see is a broken back office after installing a module.

**Comment by kpodemski** [comment]
@musaffarpatel in that case it is related to cache clearing process, are you sure you don't have any issues with directory permissions? the cache should be automatically cleared after you install a module...

**Comment by kpodemski** [comment]
@musaffarpatel do `composer install --no-dev` and it should work just fine ;-) I just tested it and it works fine. There are some conflicts between our php-dev-tools and some of the packages existing in PS 8.1, this is why you should have it as `composer install --no-dev` if the module is ready to use and install

**Comment by musaffarpatel** [comment]
@kpodemski There are no problems with the cache folder permissions, it is cleared when I  clear the cache from the back office.
I already ran composer install --no-dev on the test module I provided.  Unfortunately, the same error.  

How did you test this, did you use the testmodule I attached or a different module?

**Comment by kpodemski** [comment]
@musaffarpatel I've tested the module you provided, `testmodule.zip`, I don't have any issues with routing, etc.

**Comment by kpodemski** [comment]
Could you try with this?
[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/12300413/testmodule.zip)

**Comment by musaffarpatel** [comment]
Hi

Same error when installing the module you attached, see screen shot attached.

I'll list the exact steps I perform:

Set up a fresh install of Prestashop 8.1.0
After install is complete, I change cache settings to recompile templates if templates have changed.
Next enabled the store (Shop Params > General > Maintenance)
Ensure debug mode is disabled.
Install the test module
From Module Manager access the testmodule configuration and the error attached is thrown.

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/1dc0bfaf-fc4d-4bbe-9ebc-6f9eaa93da5b)

**Comment by kpodemski** [comment]
I'm afraid I'm unable to reproduce this issue. I don't think the fact that it's a clean installation changes a lot. It's a basic feature we use in LinkList module, Wishlist, example modules, etc.

**Comment by kpodemski** [comment]
What's your PHP version?

**Comment by musaffarpatel** [comment]
Php 8.1.8

I'll test this on a different hosted server and let you know if the same problem occurs or not.

**Comment by milanjandric** [comment]
I have exactly the same problem here. Exactly.

**Comment by musaffarpatel** [comment]
@milanjandric now I know i'm not going crazy :)

**Comment by ChillCode** [comment]
I just opened your module with my IDE and I just get some errors, so I guess you have a composer issue, comment autoload.php line and see the results.

**Comment by musaffarpatel** [comment]
@ChillCode There is no issue with the composer files, there's a curious issue with Prestashop.  As stated, the module works fine when I clear the cache file manually (see previous message).

**Comment by kpodemski** [comment]
@musaffarpatel you can also try to change this place where you get router to just $this->get('router'), you have also some module_file property which is useless? 

but I'm really unsure if that's a PrestaShop bug, it really looks like some error with how the container/symfony cache is being cleared on your installation 🤔

finally: if we don't reproduce it, we won't fix it, simple as that 🤷🏼‍♂️

**Comment by kpodemski** [comment]
@musaffarpatel have you tried with example modules from our repo? :)

**Comment by musaffarpatel** [comment]
@kpodemski 

I tried the demo-grid module and similar issue, see attached.

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/69c4c7e6-f764-4c70-886a-6b4e30aaf0ad)

Installed the module and then immediately went to configure it and the error appears.

I've only started encountering these issues in Prestashop 8.0.4+

**Comment by kpodemski** [comment]
Could you check on the version downloaded from GitHub?
https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1

Maybe it's an issue coming from the corporate version.

**Comment by musaffarpatel** [comment]
@kpodemski Almost all of my clients from the Prestashop marketplace are using the corporate version of PS 8, therefore things really need to work there too.  It's beyond my power to ask them to switch versions

**Comment by kpodemski** [comment]
@musaffarpatel I understand, but we don't discuss issues around the corporate version here. We discuss the GitHub version here, so it is a must-have to know for us whether the error is reproducible on the GitHub version. If it's not, then we need to consult with the team responsible for the Edition to see what's wrong :)

As the error seems to be serious I decided to check it using PrestaShop Edition Basic 8.1.1 and... it works for me:
https://capture.dropbox.com/t5QNvO0y6QNlcHo0

**Comment by musaffarpatel** [comment]
@kpodemski Understood, I'll check it shortly on github version of Prestashop.
In the meantime, I am testing this on WAMP under Laragon, not sure if it could be related to that?

**Comment by ChillCode** [comment]
Can you take a capture of your module author/version from Module Manager before installing it?

**Comment by kpodemski** [comment]
@musaffarpatel of course, it's not a _real environment_

**Comment by sallemiines** [comment]
Hello @musaffarpatel 

Following your steps  and just at step 3 I'm blocked , I didn't manage to install the module ! 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/ec79fca2-4a48-46ad-9d4e-71b6c23577a0)

Please check and  feadback

**Comment by kpodemski** [comment]
@sallemiines this issue is already being handled, no need for QA 👍🏻

**Comment by musaffarpatel** [comment]
@kpodemski Just wondering if anything further is needed to move this along?  It seems like a major issue affecting the the basic (non open source version).  How can I report it to the Prestashop basic Edition team?

**Comment by kpodemski** [comment]
@musaffarpatel

It's been proved that this issue only exists on Windows, which means it is not a major issue.

**Comment by musaffarpatel** [comment]
@kpodemski I have learned a little more about this issue.  The issue also affects Linux setups.   The issue seems to only occur when you have a config folder in the module folder, which contains a subfolder and index.php file within it.

Eg:
modules/mymodule/config/services/
If the above contains a standard index.php file it breaks the module.
Removing the index.php file solves the issue.

**Comment by ChillCode** [comment]
Hi @musaffarpatel 

If I download your module (that cannot be installed) there are no subfolders on config folder so this is a different issue.

Don't know how you load those services but PrestaShop will look into the following folders:

FO

modules/mymodule/config/
modules/mymodule/config/front/

BO

modules/mymodule/config/
modules/mymodule/config/admin/
modules/mymodule/config/front/

And those folders can have an index.php php file on them, so I'd try  to use the default folders.

[More info](https://devdocs.prestashop-project.org/8/modules/concepts/services/#services-in-legacy-environment)

**Comment by Hlavtox** [comment]
@musaffarpatel This should be fixed on develop branch, it was caused by cache being cleaned only in the current environment, not both. Can you try? :-)

**Comment by florine2623** [comment]
ping @musaffarpatel

**Comment by musaffarpatel** [comment]
@florine2623 I tested this on a fresh install of Prestashop 8.1.2 but the problem still persists, I must manually clear the cache to kill the error - many of my clients are also running into the same issue when they install a module which uses routing,.

**Comment by Hlavtox** [comment]
@musaffarpatel It should be fixed on 8.1.3 because the guys backported the fix from v9 here - https://github.com/PrestaShop/PrestaShop/pull/34741/files

It now clears cache for all environments.

**Comment by musaffarpatel** [comment]
@Hlavtox That's great news, thanks.  Where can I download 8.1.3 from?

**Comment by Hlavtox** [comment]
From here :-) https://github.com/PrestaShop/PrestaShop/releases

Or it should be available for an upgrade right now in autoupgrade module.

**Comment by musaffarpatel** [comment]
@Hlavtox I just tested this on Prestashop 8.1.3 and unfortunately still encounter the same error

**Comment by danieleisenhardt** [comment]
Ran into a similar issue on Prestashop 8.1.7 today. Had to work this brute-force solution into my module `install()` function:
```
        // Prestashop can not find the module routes unless cache is deleted
        array_map('unlink', glob(_PS_CACHE_DIR_ . '/*.*'));
```

I know this is not elegant, but it works as a stop-gap measure until the Prestashop team has time to fix their cache.

**Comment by Hlavtox** [comment]
Cache issue, resolved by wiping it after every module action.
