### ISSUE TITLE
Product Comments v6.0.0 unzips incorrectly into the modules folder

### ISSUE THREAD

**Issue by Julian-Collins** [PrestaShop/PrestaShop#33728]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have tried to update the product comments module to v6.0.0 that was released yesterday and its unpacking the payload directing into the modules folder. i.e /modules and keeps repeatedy showing as the update is required

where it should be into /modules/productcomments

It looks like the release file has https://github.com/PrestaShop/productcomments/releases/tag/v6.0.0 not been zipped up correctly as its not got the directory structure within it

### Expected behavior

Updated module should unzip into modules/productcomments

### Steps to reproduce

1) Go into Module Manger
2) Select Updates
3) Click Update for Product Comments

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

productcomments v6.0.0

**Comment by leemyongpakvn** [comment]
I confirm this problem. The correct release zip must has productcomments folder inside, but this 6.0.0 release does not. Amazingly, the Artifacts zip in Build & Release draft at https://github.com/PrestaShop/productcomments/actions/runs/5951694823 is correct.

**Comment by Hlavtox** [comment]
@leemyongpakvn Yeah, but the release update workflow is broken and doesn't work. So somebody did it manually - badly.

**Comment by matks** [comment]
In order to un-publish productcomments 6.0.0 from Distribution API I just marked it as "pre-release" in https://github.com/PrestaShop/productcomments/releases/tag/v6.0.0 . It will not be featured by https://api.prestashop-project.org/modules/8.1.1 in one hour, when the cron behind Distribution API refreshes the data.

**Comment by matks** [comment]
The ZIP archive A in https://github.com/PrestaShop/productcomments/releases/tag/v6.0.0 seems correct while the ZIP 
 archive B downloadable through Distribution API https://api.prestashop-project.org//assets//modules//productcomments//v6.0.0//productcomments.zip seem not.

For example archive B contains `tests` folder and archive A does not.

Something wrong happened between the GitHub release artifact and Distribution API storing it for download.

**Comment by matks** [comment]
> @leemyongpakvn Yeah, but the release update workflow is broken and doesn't work

Indeed https://github.com/PrestaShop/PrestaShop/issues/33749

**Comment by leemyongpakvn** [comment]
@Hlavtox _build dependencies & create artifact_ is OK but _update_release_draft_ is Skipped. I think we can try @M0rgan01 solution in Slack.

**Comment by matks** [comment]
Productcomments 6.0.0 is no more pushed by Distribution API to PS instances https://api.prestashop-project.org/modules/8.1.1 

In order to resume pushing, the github release must be modified so it is not pre-release. Please only do this after solving the problem.

**Comment by M0rgan01** [comment]
I just saw, there are 3 concerns for me:
- the CI has a problem when building the zip. I created a ticket for this https://github.com/PrestaShop/PrestaShop/issues/33749
- the ZIP that I had to create manually must contain a folder. It can be fixed easily
- The Distribution API did not update the data during my various tries

**Comment by leemyongpakvn** [comment]
There are 2 steps in Github Build & Release Draft, both of them create zip file.
- Build dependencies & create artifact is Succeeded.
- Update Release Draft is Skipped
![GitHub_BuildRelease](https://github.com/PrestaShop/PrestaShop/assets/3759923/20316df4-ac58-4d64-89eb-73de025d34c5)
![GitHub_BuildArtifacts](https://github.com/PrestaShop/PrestaShop/assets/3759923/2caecc69-52b1-4785-84bf-3e73cdfd0974)

**Comment by M0rgan01** [comment]
Indeed, you can find the zip in the summary of actions (https://github.com/PrestaShop/productcomments/actions/runs/5953972519)

**Comment by leemyongpakvn** [comment]
@M0rgan01 My screenshots are in case of pre-release, and update_release_draft is skipped.

**Comment by M0rgan01** [comment]
@leemyongpakvn Yes I saw, but I think even when merging on master I could have retrieved the zip built by the build step if I would have known :+1:

**Comment by leemyongpakvn** [comment]
@M0rgan01 OK. Let's try to fix this issue with productcomments 6.0.1 at https://github.com/PrestaShop/productcomments/pull/181

**Comment by M0rgan01** [comment]
We are finally obligated to create a new release, 6.0.1, to fix the issue. Even if we manually update the zip file and republish the release, the zip download link will not be updated.

**Comment by leemyongpakvn** [comment]
FYI, at least 3 modules Release that built with current Organization Build & Release but still have correct structure:
1.  https://github.com/PrestaShop/contactform/releases/tag/v4.4.1
2. https://github.com/PrestaShop/ps_linklist/releases/tag/v6.0.3
3. https://github.com/PrestaShop/ps_languageselector/releases/tag/v2.1.3
These releases were built on March and June this year, a few months before https://github.com/PrestaShop/PrestaShop/issues/33749

**Comment by Hlavtox** [comment]
@leemyongpakvn I did it manually, that's why it's correct. :-) See https://github.com/PrestaShop/ps_linklist/actions/runs/5354084130

**Comment by leemyongpakvn** [comment]
@Hlavtox I see ;) How about 2 other releases in March ? 
Update: never mind ;), those 2 releases were built 2 months before [Organizaton Build & Release changed](https://github.com/PrestaShop/.github/commit/aba1484b021ac5a11f23c92bbc4ef1d31808bdd1)

**Comment by leemyongpakvn** [comment]
@Hlavtox We have clearer information when testing locally in productcomments repo with
https://github.com/PrestaShop/productcomments/actions/runs/6000817427 Annotations:
>
update_release_draft
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/upload-release-asset@v1.0.2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by leemyongpakvn** [comment]
It looks like we need to replace outdated upload-release-asset@v1.0.2 by https://github.com/softprops/action-gh-release

**Comment by M0rgan01** [comment]
I think the problem comes from the PR https://github.com/PrestaShop/.github/pull/7. When going from actions/download-artifact@v1 to actions/download-artifact@v2, the tree structure changed. See https://github.com/actions/download-artifact/tree/releases/v2#compatibility-between-v1-and-v2. @leemyongpakvn

**Comment by leemyongpakvn** [comment]
@M0rgan01 There are some thoughts, and we must try and fail till success ;) It is still risky with testing locally on productcomments. I see bot has just updated productcomments in https://github.com/PrestaShop/native-modules to v6.0.1. The client had problem with v6.0.0 upgrade, if they do v6.0.1 upgrade, then will be forced to downgrade back to 5.0.3, then they will be upset :angry:
So I suggest droping v6.0.1 as soon as possible, and switch to test on a non-native module like https://github.com/PrestaShop/ps_qualityassurance

**Comment by matks** [comment]
Hi @leemyongpakvn you're right to be careful 😉 but if I can reassure you
- the release git tag is valid ✅ verified
- the release ZIP archive is valid ✅ verified (@M0rgan01 performed the upgrade on his backoffice, the unzipping was successfull)

**Comment by matks** [comment]
Distribution API now successfully serves productcomments 6.0.1 https://api.prestashop-project.org/modules/8.1.1 and @M0rgan01 was able to successfully install it from the API 😉

**Comment by matks** [comment]
@Julian-Collins Can you retry? The problem should be fixed by release 6.0.1

**Comment by Julian-Collins** [comment]
@matks  - Its installs now into the right folder but errors when trying configure

Oops... looks like an unexpected error occurred.

You have requested a non-existent service "product_comment_repository".

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]

Im doing this on a test clone of my live site so im happy to provide more debug info if you require

**Comment by Julian-Collins** [comment]
Stack trace from debug mode:
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
You have requested a non-existent service "product_comment_repository".

  at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:289
  at Symfony\Component\DependencyInjection\Container->make()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:231)
  at Symfony\Component\DependencyInjection\Container->get()
     (classes/module/Module.php:3443)
  at ModuleCore->get()
     (modules/productcomments/productcomments.php:172)
  at ProductComments->_postProcess()
     (modules/productcomments/productcomments.php:260)
  at ProductComments->getContent()
     (controllers/admin/AdminModulesController.php:696)
  at AdminModulesControllerCore->postProcessCallback()
     (controllers/admin/AdminModulesController.php:921)
  at AdminModulesControllerCore->postProcess()
     (classes/controller/Controller.php:308)
  at ControllerCore->run()
     (classes/Dispatcher.php:510)
  at DispatcherCore->dispatch()
     (admin297mwm0l3l8di5fbzkh/index.php:95)

**Comment by matks** [comment]
OK so at least it installs 😄 now it's no more a install process bug, it's a "regular" behavior bug

The missing service `product_comment_repository` is defined here https://github.com/PrestaShop/productcomments/blob/dev/config/common.yml#L12 🤔 so it's declared. It's strange your PrestaShop is not able to find it. Could you clear the cache in var/cache ?

**Comment by leemyongpakvn** [comment]
@matks I'm not absolutely sure we fixed issue with productcomments v6.0.1 locally because in its [Actions](https://github.com/PrestaShop/productcomments/actions): Build workflow 409 - Failed because update_release_draft  job **Failed**, while Build workflow 410 - Success but update_release_draft job was **Skipped**.

**Comment by Julian-Collins** [comment]
@matks  - Clearing the cache made no difference , its still throwing the exception

**Comment by Julian-Collins** [comment]
I have managed to get it working again by reseting the module. 
This isnt a problem as we havent switched this on but it could be a problem for other users if they loose their user added coments by resetting the module

**Comment by matks** [comment]
> @matks I'm not absolutely sure we fixed issue with productcomments v6.0.1 locally because in its [Actions](https://github.com/PrestaShop/productcomments/actions): Build workflow 409 - Failed because update_release_draft job **Failed**, while Build workflow 410 - Success but update_release_draft job was **Skipped**.

Ah 😄 we dont talk about the same issue.

I talk about the issue "Product Comments v6.0.0 unzips incorrectly into the modules folder": this one is fixed by 6.0.1 . The latest release now correctly unzips.

But I agree there is another issue remaining, the one which created the situation 😉 the problem with the GitHub Action.

**Comment by leemyongpakvn** [comment]
@matks So we will continue with the remaining issue locally before apply globally in Organization Build&Release ?

**Comment by M0rgan01** [comment]
@leemyongpakvn We have targeted the problem, which is the update of the download-artifact action. I propose a fix directly on the repository .github https://github.com/PrestaShop/.github/pull/9

**Comment by leemyongpakvn** [comment]
@M0rgan01 It looks well. @matks Do you agree to test directly on the repository .github or we need to test locally first ? Whatever you choose, we still need a new Release of a native module to test it in action.

**Comment by leemyongpakvn** [comment]
@Julian-Collins @florine2623 This issue was solved by https://github.com/PrestaShop/productcomments/pull/186

**Comment by Julian-Collins** [comment]
v6.0.2 isnt visible to upgrade to in my modules yet - will check again later

**Comment by leemyongpakvn** [comment]
@Julian-Collins v6.0.2 is available in Module Updates now.

**Comment by Julian-Collins** [comment]
Thanks @leemyongpakvn  - I have seen it and updated

**Comment by matks** [comment]
@leemyongpakvn Is the problem solved for all modules or only productcomments?

**Comment by matks** [comment]
If it's fixed for every module 😄 we can close this issue

**Comment by leemyongpakvn** [comment]
@matks The problem is fixed locally for productcomments first, then apply globally for all modules via Organization .github. **Julian-Collins** updated productcomments to v6.0.2 and did not report any issue so we can consider it is OK now (it is really OK on my side :).

**Comment by matks** [comment]
Youhou! 🎉
