### ISSUE TITLE
Total products is different than order total

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#36369]
### Describe the bug and add attachments

Under certain conditions, the product total doesn't match the order total. It's very annoying problem, because the amount that gets sent into the payment gateway or shown in bankwire module is different than the amount our ERP software calculates. We then have to fix dozens of invoices manually.

![Snímek obrazovky 2024-06-17 085058](https://github.com/PrestaShop/PrestaShop/assets/6097524/f452493d-0273-4784-b56a-8785276c7acc)

### Expected behavior

I know that there are issues with rounding in Prestashop, but when there is no shipping and discounts involved, at least the products sum should be the same as the order total.

### Steps to reproduce

1. Setup a currency with 0 decimal places. Setup some free carrier.
2. Create three products.
3. Product A - "Campingaz Culinary Modular Pizza Stone"
a) 825,619800 tax exc.
b) 998,999958 tax inc.
c) specific price discount  30 %
4. Product B - "Grilovací sada Campingaz"
a) 412,396700 tax exc.
b) 499,000007 tax inc.
c) specific price discount 30 %
5. Product C - "Obal Campingaz BBQ Classic Cover L (3 series)"
a) 990,909100 tax exc.
b) 1199,000011 tax inc.
c) specific price discount 20 %
6. Order it in FO, with some free carrier.
7. Check BO, see that product total is 2 007, but order total is 2008.

### ps_orders
![sn__mek_obrazovky_2024-06-12_103607](https://github.com/PrestaShop/PrestaShop/assets/6097524/ad121707-2ae9-4877-a82a-3e15c3bdb950)

### ps_order_detail
![sn__mek_obrazovky_2024-06-12_103537](https://github.com/PrestaShop/PrestaShop/assets/6097524/50dc2176-de8e-4d1d-ad0a-190cbbd82ec7)

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

[TRENDO s.r.o.](https://www.trendo.cz/)

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional can somebody reproduce this issue? it's quite an important one

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I have reproduced your issue in PS 8.1.x, I'll add this to the backlog so it can be fixed.

<img width="1116" alt="Screenshot 2024-07-03 at 15 55 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/132c05bc-6f1c-49a4-a804-400fbf2bd9fe">

<img width="989" alt="Screenshot 2024-07-03 at 15 56 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/2b3963a9-08f4-4be9-8662-917e68c8a5fc">

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment]
cc @matks @amine-O 

Fixing this bug **does not require** entire rework of the prices in the front office, it requires adjustments related to this setting:
> Setup a currency with 0 decimal places.

You see the hint in the `unit_price_x` columns in the screenshot @Hlavtox provided.

**Comment by Hlavtox** [comment]
2007 is the correct value.

If you call this and go inside getOrderTotal method.

```php
$this->context->cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
$this->context->cart->getOrderTotal(true);
```

It returns following in the `switch ($type) {`

```php
2007.0 for Cart::ONLY_PRODUCTS
2007.799985 for Cart::BOTH (default value)
```

Which gets rounded to this before the return of the method.

```php
2007.0 for Cart::ONLY_PRODUCTS
2008.0 for Cart::BOTH
```

Modifying the appropriate method in Calculator to appoint for rounding works

```php
public function getRowTotalWithoutDiscount()
    {
        $amount = new AmountImmutable();
        foreach ($this->cartRows as $cartRow) {
            $amount = $amount->add($this->rounded($cartRow->getInitialTotalPrice(), $this->computePrecision));
        }

        return $amount;
    }
```
but tax is wrong, kill me

![Snímek obrazovky 2024-07-03 200432](https://github.com/PrestaShop/PrestaShop/assets/6097524/5733184c-b764-47e3-b5c3-46f477a62f93)

ok, but if we round only the displayed price and keep precision of the tax excluded one, it works

```
private function roundedTaxIncluded(AmountImmutable $amount, int $computePrecision)
    {
        return new AmountImmutable(
            Tools::ps_round($amount->getTaxIncluded(), $computePrecision),
            $amount->getTaxExcluded()
        );
    }
```

![Snímek obrazovky 2024-07-03 201743](https://github.com/PrestaShop/PrestaShop/assets/6097524/9a9c5e96-1744-43bd-9f93-27c6a639b071)

Lets see what tests say

**Comment by jf-viguier** [comment]
@Hlavtox thanks for the issue. Not so easy to fix.

**Comment by SharakPL** [comment]
It's even bigger issue when the price is calculated for another currency, and especially on small priced items bought by 100s. Then the differences in the order and between the order and automatically generated invoice become huge, like a couple €/$ instead of only a few cents. And the reason for that is rounding is made in many different places and use numbers like 1.524913 as a base price. It makes the total very specific, but doesn't match the sum of all products' rounded totals that need to be shown for the customer. It's simply impossible to have the right values everywhere this way.

IMHO the fix is rather simple, at least from the logical point of view 😉
Base prices should be rounded to 2 places right where the price is set on the product. Let's say I have tax included price 5.99 with tax 23%. Currently PS sets tax excluded price as 4.869912, but it should set 4.87. The tax also should be calculated only for this single tax excluded price and also limited to .2 digits. After that several items bought will always match the values because when buy a 1000 items it will be 1000 x 4.87 = 4870,00 (exactly what the customer expects to see) and not 1000 x 4.869912 = 4869.91. The most important part: **tax included price should be simple sum of base and tax and cart totals should be also a simple sum of product line totals and taxes instead of being calculated again and again from each product's base price.** 

If a product has a special price or the order is in non-default currency then it also should be calculated for the base price only and rounded right away to 2 digits after coma. Everything after that should use this new price and again simple sums of .2 digit numbers.

**Comment by Hlavtox** [comment]
@SharakPL Yes, nothing more to add. I have written some price specifications based on my knowledge of the core, but I was not able to get in contact with anyone from Prestashop to discuss it.

**Comment by boo-code** [comment]
This looks fixed and only still open because the fix went to a non-default branch, so nothing auto-closed it.

#40925 carries `Fixes #36369`, was merged into `9.2.x` on 2026-08-11, and its merge commit `09901619b1f` is an ancestor of both `upstream/9.2.x` and `upstream/develop`. It changed `src/Core/Cart/Calculator.php` and extended `Cart/Rounding/RoundingType/round_line.feature` and `round_total.feature`.

Checked on `9.2.x` at `698da4f7a4f`:

| | result |
| --- | --- |
| `round_line.feature` | 5 scenarios, 49 steps, passed |
| `round_total.feature` | 5 scenarios, 49 steps, passed |
| whole `cart` Behat suite | 242 scenarios, 3538 steps, passed |

Worth noting for anyone screening this tracker: #37925 and #40925 both report as `closed` through the issue timeline API, which has no merged state, so a quick pass over the cross-references reads as "three abandoned attempts" when two of them actually landed.

**Comment by SharakPL** [comment]
Thanks @boo-code for pointing that out.

Fixed in #40925

**Comment by boo-code** [comment]
This still reproduces on 9.2.0 (`upstream/9.2.x` @ `07d7f07`) on the tax excluded side. #40925 fixed the tax included half.

Same shape as the original report — no shipping, no discount, product total different from order total. Cart of 4.995 and 3.325 tax excluded, rounding type "line", EUR precision 2:

```
Cart::getOrderTotal(false, Cart::ONLY_PRODUCTS)   8.33
Cart::getOrderTotal(false, Cart::BOTH)            8.32
Cart::getOrderTotal(true,  Cart::ONLY_PRODUCTS)   9.65
Cart::getOrderTotal(true,  Cart::BOTH)            9.65
```

With a 7.00 carrier the excluded gap survives (15.32 against 15.33 for products plus shipping); the included side stays consistent. Rounding types "item" and "total" are consistent on both sides — only "line" is affected.

Ordered, this leaves `total_paid_tax_excl` 8.32 against `total_products` 8.33, and the invoice footer's "Total Tax" (`total_paid_tax_incl - total_paid_tax_excl`, `classes/pdf/HTMLTemplateInvoice.php:282`) reads 1.33 against a tax detail table summing to 1.32.

`Calculator::getRowTotalWithoutDiscount()` (`src/Core/Cart/Calculator.php:229`) re-rounds only the tax included side of each row, and `CartRow::processCalculation()` stores the line unrounded for `ROUND_MODE_LINE`, so the tax excluded line total is never rounded anywhere before the final sum. `CartRow::applyRound()` already rounds both sides for the final price, so rounding both sides of the initial total under `ROUND_MODE_LINE` closes it and leaves every tax included figure identical.

Checked locally against that change: full `cart` Behat suite 242/242, and `round_line.feature` — which asserts the tax included total only, which is why this survived #40925 — goes red on an added `162.41 tax excluded` assertion (`Expects 162.41, got 162.4`) once the change is reverted.

**Comment by Hlavtox** [comment]
@boo-code This is normal, because the tax-excluded price is always estimated a bit in different parts of the calculation process and is subjects to natural differences due to rounding.

**Comment by boo-code** [comment]
@Hlavtox the rounding difference itself, yes — but the invariant this issue was opened for is the one that is broken, in your own words from the description:

> I know that there are issues with rounding in Prestashop, but when there is no shipping and discounts involved, at least the products sum should be the same as the order total.

That is exactly the case measured: no shipping, no discount, and `total_products` 8.33 against `total_paid_tax_excl` 8.32. #40925 enforced it on the tax included side, where both now agree at 9.65.

It is also not intrinsic to rounding, because two of the three rounding types already satisfy it on both sides:

```
                X:both  X:products+shipping  delta        I:both  I:products+shipping  delta
ITEM            8.33    8.33                 +0.00        9.65    9.65                 +0.00
LINE            8.32    8.33                 -0.01        9.65    9.65                 +0.00
TOTAL           8.32    8.32                 +0.00        9.65    9.65                 +0.00
```

Only "line" disagrees, and it disagrees because `CartRow` stores the line unrounded for `ROUND_MODE_LINE` while `Calculator::getRowTotalWithoutDiscount()` re-rounds the tax included side only — so under a mode whose whole definition is "round each line", the tax excluded side is the one place no line rounding happens.

The user-visible consequence is a document contradicting itself rather than a cent of drift: on that order the invoice prints "Total Tax" 1.33 while its own tax detail table sums to 1.32.
