### ISSUE TITLE
CCC removes units for CSS variables with default values which makes wrong calculations

### ISSUE THREAD

**Issue by dangelion** [PrestaShop/PrestaShop#36574]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

CCC removes units for CSS variables with default values which makes wrong calculations.

Here is a related issue: https://github.com/matthiasmullie/minify/issues/408

### Steps to reproduce

Put in your css file a CSS variable like:
`--test-var: 0px;`
then enable CCC and check again the variable, it's:
`--test-var: 0;`

So when you use this variable (for example inside `calc()`) it causes wrong calculations

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @dangelion ,

I can't reproduce your issue. I clear the cache as well, but the variable is still intact.
Could you specify which file exactly you modified ?

Waiting for your feedback.
Thanks!

**Comment by dangelion** [comment]
Hi @florine2623 How you clear the cache?

I use the starter theme https://github.com/Oksydan/falcon with its CSS structure, I write CSS inside one of those files

**Comment by florine2623** [comment]
Sorry for the long awaited answer.

I cleared the cache from BO in Advanced parameters > Performances > Clear cache + clear cache and hard reload from my browser.

Could you send a screen record of your issue ?

**Comment by kpodemski** [comment]
@florine2623 

I can confirm that this issue requires upgrading [this dependency](https://github.com/matthiasmullie/minify) to its latest version to fix the problem.

cc @Oksydan @Hlavtox @Prestaworks

**Comment by Prestaworks** [comment]
This is fixed in 9.1.4.

**Comment by boo-code** [comment]
Still reproduces on 9.2.x, but not in the shape reported, and neither remedy proposed in this thread works.

Measured through the real CCC entry point - `CssMinifier::minify(array $files, $destination)`, called from `classes/assets/CccReducer.php:56`, with a file on disk so the concat / import / path-rewrite passes all run.

Input:

```css
:root {
  --a: 1px;
  /* section */ --gap: 0px;
  --safe: 0px;
}
.b { width: calc(100% - var(--gap)); }
```

Output:

```css
:root{--a:1px;--gap:0;--safe:0px}.b{width:calc(100% - var(--gap))}
```

`--gap` loses its unit, `--safe` in the same block keeps it. The difference is the comment. `MatthiasMullie\Minify\CSS::extractCustomProperties()` shields custom-property values with

```
/(?<=^|[;}{])\s*(--[^:;{}"\'\s]+)\s*:([^;{}]+)/m
```

and `Minify::replace()` runs every registered pattern against the *original* content. Once the comment pattern has consumed `/* section */`, the character preceding the next declaration is still `/` in the subject, the lookbehind rejects that position, the property is never extracted, and `shortenZeroes()` strips the `px`. `calc(100% - 0)` is invalid, so the whole declaration is dropped.

Three corrections to the thread:

- The minimal repro in the description (`--test-var: 0px;` on its own) does not reproduce, and did not on 8.1.3 either - 1.3.69, which 8.1.3 shipped, already preserves it. @florine2623's non-reproduction was correct; the starter theme's own CSS structure is what mattered.
- Upgrading the dependency does not fix it. 9.0.0 onward pins 1.3.73, and the latest release, 1.3.75, is already inside the existing `~1.3.0` constraint. Both leak on the shape above; measured on both.
- matthiasmullie/minify#408, linked in the description, is a different shape (`var(--x, 0px)` as a custom-property value). That one is fixed in the shipped 1.3.73 - matthiasmullie/minify#434 is a regression test for it, still open.

No stylesheet shipped by PrestaShop is affected: of 80 CSS files under `themes/`, `admin-dev/` and `modules/` (excluding `node_modules`), 15 declare custom properties and 0 put a comment and a declaration on the same line. The exposure is third-party themes and modules, which fits this being reported against a starter theme.

The defect is in the vendor library, and the fix is one lookbehind alternative:

```diff
-            '/(?<=^|[;}{])\s*(--[^:;{}"\'\s]+)\s*:([^;{}]+)/m',
+            '/(?<=^|[;}{]|\*\/)\s*(--[^:;{}"\'\s]+)\s*:([^;{}]+)/m',
```

Verified against matthiasmullie/minify master with a test case for this input: full suite green (356 tests), and reverting that one line fails exactly the new case and nothing else. Nothing needs to change in this repository - `~1.3.0` picks the fix up on the next `composer update` once it is released upstream.
